export const fakeData = [
  // {
  //   devices: {
  //     "0 kg": {
  //       drones: [
  //         {
  //           type: "Drone",
  //           color: "#ff0000",
  //           device: "DR-001",
  //           status: "available",
  //           location: { latitude: 37.5665, longitude: 126.9780 }, // Seoul center
  //         },
  //         {
  //           type: "Drone",
  //           color: "#00ff00",
  //           device: "DR-002",
  //           status: "inactive",
  //           location: { latitude: 37.5705, longitude: 126.9820 }, // Seoul north-east
  //         },
  //       ],
  //       robots: [
  //         {
  //           type: "Robot",
  //           color: "#0000ff",
  //           device: "RB-001",
  //           status: "available",
  //           location: { latitude: 37.5600, longitude: 126.9900 }, // Seoul south
  //         },
  //         {
  //           type: "Robot",
  //           color: "#ff9900",
  //           device: "RB-002",
  //           status: "critical",
  //           location: { latitude: 37.5520, longitude: 126.9750 }, // Seoul west
  //         },
  //       ],
  //     },
  //   },
  //   docking_station: {
  //     name: "Seoul Docking Station",
  //     active: true,
  //     latitude: "37.5665",
  //     longitude: "126.9780",
  //   },
  //   linked_terminals: [
  //     {
  //       name: "Incheon Terminal",
  //       active: true,
  //       latitude: "37.4563",
  //       longitude: "126.7052",
  //     },
  //     {
  //       name: "Gangnam Hub",
  //       active: true,
  //       latitude: "37.4979",
  //       longitude: "127.0276",
  //     },
  //   ],
  // },
  // {
  //   devices: {
  //     "20.0 kg": {
  //       drones: [
  //         {
  //           type: "Drone",
  //           color: "#ffff00",
  //           device: "DR-010",
  //           status: "available",
  //           location: { latitude: 35.1796, longitude: 129.0756 }, // Busan center
  //         },
  //       ],
  //       robots: [
  //         {
  //           type: "Robot",
  //           color: "#a0a0a0",
  //           device: "RB-010",
  //           status: "inactive",
  //           location: { latitude: 35.1900, longitude: 129.0800 }, // Busan north
  //         },
  //       ],
  //     },
  //   },
  //   docking_station: {
  //     name: "Busan Docking Station",
  //     active: true,
  //     latitude: "35.1796",
  //     longitude: "129.0756",
  //   },
  //   linked_terminals: [
  //     {
  //       name: "Busan North Terminal",
  //       active: true,
  //       latitude: "35.2000",
  //       longitude: "129.1000",
  //     },
  //   ],
  // },
  // {
  //   devices: {
  //     "45.0 kg": {
  //       drones: [],
  //       robots: [
  //         {
  //           type: "Robot",
  //           color: "#ff00ff",
  //           device: "RB-020",
  //           status: "available",
  //           location: { latitude: 35.8714, longitude: 128.6014 }, // Daegu center
  //         },
  //         {
  //           type: "Robot",
  //           color: "#00ffff",
  //           device: "RB-021",
  //           status: "inactive",
  //           location: { latitude: 35.8600, longitude: 128.5900 }, // Daegu south-west
  //         },
  //       ],
  //     },
  //   },
  //   docking_station: {
  //     name: "Daegu Docking Station",
  //     active: true,
  //     latitude: "35.8714",
  //     longitude: "128.6014",
  //   },
  //   linked_terminals: [
  //     {
  //       name: "Daegu East Terminal",
  //       active: true,
  //       latitude: "35.8800",
  //       longitude: "128.6200",
  //     },
  //   ],
  // },
  // {
  //   devices: {
  //     "55.0 kg": {
  //       drones: [
  //         {
  //           type: "Drone",
  //           color: "#00ffcc",
  //           device: "DR-030",
  //           status: "available",
  //           location: { latitude: 35.1600, longitude: 126.8514 }, // Gwangju center
  //         },
  //       ],
  //       robots: [
  //         {
  //           type: "Robot",
  //           color: "#ff6600",
  //           device: "RB-030",
  //           status: "critical",
  //           location: { latitude: 35.1500, longitude: 126.8400 }, // Gwangju south
  //         },
  //       ],
  //     },
  //   },
  //   docking_station: {
  //     name: "Gwangju Docking Station",
  //     active: true,
  //     latitude: "35.1600",
  //     longitude: "126.8514",
  //   },
  //   linked_terminals: [
  //     {
  //       name: "Gwangju South Terminal",
  //       active: true,
  //       latitude: "35.1400",
  //       longitude: "126.8300",
  //     },
  //   ],
  // },
  // {
  //   devices: {
  //     "10.0 kg": {
  //       drones: [],
  //       robots: [
  //         {
  //           type: "Robot",
  //           color: "#33cc33",
  //           device: "RB-040",
  //           status: "available",
  //           location: { latitude: 36.3504, longitude: 127.3845 }, // Daejeon center
  //         },
  //       ],
  //     },
  //   },
  //   docking_station: {
  //     name: "Daejeon Docking Station",
  //     active: true,
  //     latitude: "36.3504",
  //     longitude: "127.3845",
  //   },
  //   linked_terminals: [
  //     {
  //       name: "Daejeon Tech Hub",
  //       active: false,
  //       latitude: "36.3700",
  //       longitude: "127.4000",
  //     },
  //   ],
  // },
  // {
  //   devices: {
  //     '0 kg': {
  //       robots: [],
  //       drones: [
  //         {
  //           type: 'Drone',
  //           color: '#4DABF7',
  //           device: 'D-1754559572886',
  //           status: 'available',
  //           location: {
  //             latitude: 37.5665,
  //             longitude: 126.978,
  //           },
  //         },
  //         {
  //           type: 'Drone',
  //           color: '#FFD43B',
  //           device: 'D-1754559572886',
  //           status: 'available',
  //           location: {
  //             latitude: 0,
  //             longitude: 0,
  //           },
  //         },
  //       ],
  //     },
  //   },
  //   docking_station: {
  //     name: 'Ulsan Docking Station12',
  //     active: true,
  //     latitude: '35.5384',
  //     longitude: '129.3114',
  //   },
  //   linked_terminals: [
  //     {
  //       name: 'Ulsan Industry Terminal',
  //       active: true,
  //       latitude: '35.5550',
  //       longitude: '129.3300',
  //     },
  //     {
  //       name: 'Ulsan Industry Terminal123333323',
  //       active: false,
  //       latitude: 35.1796,
  //       longitude: 129.0756,
  //     },
  //   ],
  // },
  // {
  //   devices: {
  //     '100.0 kg': {
  //       drones: [],
  //       robots: [
  //         {
  //           type: 'Robot',
  //           color: '#9933ff',
  //           device: 'RB-060',
  //           status: 'available',
  //           location: { latitude: 37.2636, longitude: 127.0286 }, // Suwon
  //         },
  //       ],
  //     },
  //   },
  //   docking_station: {
  //     name: '12',
  //     active: true,
  //     latitude: 0, // Seoul
  //     longitude: 0,
  //   },
  //   linked_terminals: [
  //     {
  //       name: 'Suwon Terminal A',
  //       active: true,
  //       latitude: '37.2800',
  //       longitude: '127.0500',
  //     },
  //   ],
  // },
  {
    devices: {
      '200.0 kg': {
        drones: [],
        robots: [
          {
            type: 'Robot',
            color: '#00ff5e',
            device: 'RB-070',
            status: 'available',
            location: { latitude: 33.4996, longitude: 126.5312 }, // Jeju
          },
        ],
      },
    },
    // docking_station: {
    //   name: "Jeju Docking Station",
    //   active: true,
    //   latitude: "33.4996",
    //   longitude: "126.5312",
    // },
    // linked_terminals: [
    //   {
    //     name: "Jeju East Terminal",
    //     active: true,
    //     latitude: "33.5100",
    //     longitude: "126.5200",
    //   },
    // ],
  },
];

export const fakeDataRoute = [
  {
    id: 8,
    deleted: null,
    deleted_by_cascade: false,
    created_on: '05/06/2025 21:27',
    modified_on: '05/06/2025 21:27',
    created_by_id: 17,
    modified_by_id: 17,
    name: 'Route 2',
    is_active: true,
    code: 'R-1749133639223',
    description: null,
    status: 'active',
    total_stops: 2,
    terminal_from_id: null,
    note: '',
    two_way: false,
    img_map_id: null,
    route_terminals: [
      {
        terminal_id: 13,
        name: 'Ter 3',
        terminal_type__name: 'Transit Point',
        function_names: null,
        address: '서울, 중구, 세종대로 110',
        latitude: '37.5665',
        longitude: '126.978',
        note: '',
        stop: true,
        order: 1,
        for_robot: false,
        command_line: null,
        frame: null,
      },
      {
        terminal_id: 14,
        name: 'Ter4',
        terminal_type__name: 'Transit Point',
        function_names: null,
        address: '서울, 종로구, 종로 6',
        latitude: '37.5699',
        longitude: '126.978',
        note: '',
        stop: true,
        order: 2,
        for_robot: false,
        command_line: null,
        frame: null,
      },
    ],
    delivery_operations: [],
    assignments: [],
    modified_by__userprofilelink: 'Chi',
    modified_by__settings: null,
    modified_by__followings: [],
    modified_by__user_menus: [],
    modified_by__user_grids: [],
    modified_by__gridsettinguser: null,
    modified_by__search_conditions: [],
    modified_by__cancelled_deliveries: [],
    modified_by__delivery_status_changes: [],
    modified_by__sender_user: [],
    modified_by__recipient_user: [],
    modified_by__created_orders: [],
    modified_by__order_comments: [],
    modified_by__drawingsession: null,
    modified_by__drawingelement: null,
    modified_by__drawingparticipant: null,
    modified_by__upload_statuses: [],
    modified_by__partner_profile: null,
    modified_by__id: 17,
    modified_by__first_name: 'Chi',
    modified_by__last_name: 'Nguyen',
    modified_by__is_active: true,
    modified_by__date_joined: '30/05/2025 15:36',
    modified_by__deleted: null,
    modified_by__deleted_by_cascade: false,
    modified_by__username: 'chi',
    modified_by__email: 'chi@yopmail.com',
    modified_by__created_on: '30/05/2025 15:36',
    modified_by__modified_on: '13/08/2025 09:03',
    modified_by__modified_by: null,
    modified_by__language: 'Language object (1)',
    modified_by__theme: 'Theme object (2)',
    modified_by__timezone: null,
    modified_by__last_activity: null,
    modified_by__account_locked_until: null,
    modified_by__mfa_enabled: false,
    modified_by__last_ip_address: '127.0.0.1',
    modified_by__user_agent:
      'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36',
    modified_by__otp_is_verified: false,
    modified_by__otp_exempt: false,
    modified_by__opt_mandatory: true,
    modified_by__is_account_lock: false,
    modified_by__time_account_lock: null,
    modified_by__is_rejected: false,
    modified_by__reject_reason: null,
    modified_by__reject_on: null,
    modified_by__groups: [],
    modified_by__user_permissions: [],
    modified_by__roles: [],
    measurements: [],
    modified_by: 'chi@yopmail.com',
    terminal_from: null,
    img_map: null,
  },
  {
    id: 9,
    deleted: null,
    deleted_by_cascade: false,
    created_on: '06/06/2025 06:52',
    modified_on: '18/06/2025 14:57',
    created_by_id: 17,
    modified_by_id: 17,
    name: 'Route 4',
    is_active: true,
    code: 'R-1749167537430',
    description: null,
    status: 'active',
    total_stops: 2,
    terminal_from_id: null,
    note: 'note description',
    two_way: false,
    img_map_id: null,
    route_terminals: [
      {
        terminal_id: 16,
        name: 'Ter 6',
        terminal_type__name: 'Docking Station',
        function_names: null,
        address: '제주특별자치도, 제주시, 관덕로8길 24-1',
        latitude: '33.5110222053145',
        longitude: '126.523109099092',
        note: 'note description',
        stop: true,
        order: 1,
        for_robot: false,
        command_line: null,
        frame: null,
      },
      {
        terminal_id: 15,
        name: 'Ter 5',
        terminal_type__name: 'Warehouse',
        function_names: null,
        address: '제주특별자치도, 제주시, 만덕로6길 32',
        latitude: '33.5141',
        longitude: '126.5295',
        note: '',
        stop: true,
        order: 2,
        for_robot: false,
        command_line: null,
        frame: null,
      },
    ],
    delivery_operations: [],
    assignments: [],
    modified_by__userprofilelink: 'Chi',
    modified_by__settings: null,
    modified_by__followings: [],
    modified_by__user_menus: [],
    modified_by__user_grids: [],
    modified_by__gridsettinguser: null,
    modified_by__search_conditions: [],
    modified_by__cancelled_deliveries: [],
    modified_by__delivery_status_changes: [],
    modified_by__sender_user: [],
    modified_by__recipient_user: [],
    modified_by__created_orders: [],
    modified_by__order_comments: [],
    modified_by__drawingsession: null,
    modified_by__drawingelement: null,
    modified_by__drawingparticipant: null,
    modified_by__upload_statuses: [],
    modified_by__partner_profile: null,
    modified_by__id: 17,
    modified_by__first_name: 'Chi',
    modified_by__last_name: 'Nguyen',
    modified_by__is_active: true,
    modified_by__date_joined: '30/05/2025 15:36',
    modified_by__deleted: null,
    modified_by__deleted_by_cascade: false,
    modified_by__username: 'chi',
    modified_by__email: 'chi@yopmail.com',
    modified_by__created_on: '30/05/2025 15:36',
    modified_by__modified_on: '13/08/2025 09:03',
    modified_by__modified_by: null,
    modified_by__language: 'Language object (1)',
    modified_by__theme: 'Theme object (2)',
    modified_by__timezone: null,
    modified_by__last_activity: null,
    modified_by__account_locked_until: null,
    modified_by__mfa_enabled: false,
    modified_by__last_ip_address: '127.0.0.1',
    modified_by__user_agent:
      'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36',
    modified_by__otp_is_verified: false,
    modified_by__otp_exempt: false,
    modified_by__opt_mandatory: true,
    modified_by__is_account_lock: false,
    modified_by__time_account_lock: null,
    modified_by__is_rejected: false,
    modified_by__reject_reason: null,
    modified_by__reject_on: null,
    modified_by__groups: [],
    modified_by__user_permissions: [],
    modified_by__roles: [],
    measurements: [],
    modified_by: 'chi@yopmail.com',
    terminal_from: null,
    img_map: null,
  },
  {
    id: 11,
    deleted: null,
    deleted_by_cascade: false,
    created_on: '20/08/2025 15:39',
    modified_on: '06/09/2025 14:49',
    created_by_id: 9,
    modified_by_id: 9,
    name: 'Route hub1 -> docking1',
    is_active: true,
    code: 'R-1755679133366',
    description: null,
    status: 'active',
    total_stops: 2,
    terminal_from_id: null,
    note: '',
    two_way: false,
    img_map_id: null,
    route_terminals: [
      {
        terminal_id: 23,
        name: 'hub1',
        terminal_type__name: 'Delivery Hub, Docking Station',
        function_names: 'Fixed, Other',
        address: '경기, 안양시 만안구, 임곡로 245',
        latitude: '37.4113953691355',
        longitude: '126.926031711027',
        note: '',
        stop: true,
        order: 1,
        for_robot: false,
        command_line: {
          '16': {
            MAV_CMD_NAV_WAYPOINT: [
              '0',
              '0',
              '0',
              '0',
              '37.4113953691355',
              '126.926031711027',
              '368.48',
            ],
          },
        },
        frame: {
          '0': 'FRAME_0',
        },
      },
      {
        terminal_id: 24,
        name: 'docking station 1',
        terminal_type__name: 'Docking Station',
        function_names: 'Fixed',
        address: '경기, 안양시 동안구, 예술공원로 496',
        latitude: '37.432274834605906',
        longitude: '126.96006338483684',
        note: '',
        stop: true,
        order: 2,
        for_robot: false,
        command_line: {
          '16': {
            MAV_CMD_NAV_WAYPOINT: [
              '0',
              '0',
              '0',
              '0',
              '37.432274834605906',
              '126.96006338483684',
              '378.48',
            ],
          },
        },
        frame: {
          '0': 'FRAME_0',
        },
      },
    ],
    delivery_operations: [],
    assignments: [],
    modified_by__userprofilelink: 'Phat',
    modified_by__settings: 'Settings for phatlh',
    modified_by__followings: [],
    modified_by__user_menus: [],
    modified_by__user_grids: [],
    modified_by__gridsettinguser: null,
    modified_by__search_conditions: [],
    modified_by__cancelled_deliveries: [],
    modified_by__delivery_status_changes: [],
    modified_by__sender_user: [],
    modified_by__recipient_user: [],
    modified_by__created_orders: [],
    modified_by__order_comments: [],
    modified_by__drawingsession: null,
    modified_by__drawingelement: null,
    modified_by__drawingparticipant: null,
    modified_by__upload_statuses: [],
    modified_by__partner_profile: null,
    modified_by__id: 9,
    modified_by__first_name: 'Phat',
    modified_by__last_name: 'Le',
    modified_by__is_active: true,
    modified_by__date_joined: '12/05/2025 11:45',
    modified_by__deleted: null,
    modified_by__deleted_by_cascade: false,
    modified_by__username: 'phatlh',
    modified_by__email: 'phatlh@yopmail.com',
    modified_by__created_on: '12/05/2025 11:45',
    modified_by__modified_on: '06/09/2025 10:45',
    modified_by__modified_by: null,
    modified_by__language: 'Language object (1)',
    modified_by__theme: 'Theme object (2)',
    modified_by__timezone: null,
    modified_by__last_activity: null,
    modified_by__account_locked_until: null,
    modified_by__mfa_enabled: false,
    modified_by__last_ip_address: '127.0.0.1',
    modified_by__user_agent:
      'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36',
    modified_by__otp_is_verified: false,
    modified_by__otp_exempt: true,
    modified_by__opt_mandatory: true,
    modified_by__is_account_lock: false,
    modified_by__time_account_lock: null,
    modified_by__is_rejected: false,
    modified_by__reject_reason: null,
    modified_by__reject_on: null,
    modified_by__groups: [],
    modified_by__user_permissions: [],
    modified_by__roles: [],
    measurements: [],
    modified_by: 'phatlh@yopmail.com',
    terminal_from: null,
    img_map: null,
  },
];
