# Generated by Django 5.1.2 on 2025-05-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_format', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='printformat',
            unique_together={('model_name', 'is_default')},
        ),
        migrations.AddField(
            model_name='printformat',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
