# Generated by Django 5.1.2 on 2025-05-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_format', '0002_alter_printformat_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printformat',
            name='display_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
