# Generated by Django 5.1.2 on 2025-05-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_format', '0003_printformat_display_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printformat',
            name='display_field',
        ),
        migrations.AddField(
            model_name='printformatfield',
            name='display_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='printformattablecolumn',
            name='display_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
