# Generated by Django 5.1.2 on 2025-05-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_format', '0004_remove_printformat_display_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printformattablecolumn',
            name='field_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
