# Generated by Django 5.1.2 on 2025-05-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('print_format', '0005_printformattablecolumn_field_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='printformat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='printformat',
            name='models_supported',
            field=models.ManyToManyField(related_name='print_formats', to='contenttypes.contenttype'),
        ),
        migrations.RemoveField(
            model_name='printformat',
            name='model_name',
        ),
    ]
