# Generated by Django 5.1.2 on 2025-05-21 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('print_format', '0006_alter_printformat_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printformat',
            name='models_supported',
        ),
    ]
