# Generated by Django 5.1.2 on 2025-05-21 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('print_format', '0007_remove_printformat_models_supported'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printformattablecolumn',
            name='print_format_field',
        ),
        migrations.RemoveField(
            model_name='printformattablecolumn',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='printformattablecolumn',
            name='modified_by',
        ),
        migrations.DeleteModel(
            name='PrintFormatField',
        ),
        migrations.DeleteModel(
            name='PrintFormatTableColumn',
        ),
    ]
