# Generated by Django 5.1.2 on 2025-05-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_format', '0008_remove_printformattablecolumn_print_format_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printformat',
            name='usage_count',
            field=models.IntegerField(default=0),
        ),
    ]
