# Generated by Django 5.1.2 on 2025-11-21 05:55

import core.base
import core.multilanguage.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0024_country_group_currencyformat_group_dateformat_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('task_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('task_type', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('generic', 'Generic'), ('download', 'Download'), ('upload', 'Upload'), ('message', 'Message'), ('background', 'Background Task')], default='generic', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('action', models.CharField(blank=True, max_length=255, null=True)),
                ('task_channel', models.CharField(blank=True, max_length=255, null=True)),
                ('trigger_source', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('message_title', models.CharField(blank=True, max_length=255, null=True)),
                ('message_body', models.TextField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('progress', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('download_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('file_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('record_count', models.IntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('error_details', models.JSONField(blank=True, null=True)),
                ('related_model', models.CharField(blank=True, max_length=255, null=True)),
                ('related_object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Status',
                'verbose_name_plural': 'Task Statuses',
                'ordering': ['-created_on'],
                'indexes': [models.Index(fields=['task_id'], name='task_status_task_id_554aa8_idx'), models.Index(fields=['task_type', 'status'], name='task_status_task_ty_5db964_idx'), models.Index(fields=['category', 'status'], name='task_status_categor_16fd59_idx'), models.Index(fields=['user', 'status'], name='task_status_user_id_8f783e_idx')],
            },
            bases=(models.Model, core.multilanguage.models.MultiLanguageContentMixin, core.base.DependencyCheckMixin),
        ),
    ]
