# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: frame_detection.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'frame_detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66rame_detection.proto\x12\x0f\x66rame_detection\"]\n\x05\x46rame\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x12\x0e\n\x06\x66ormat\x18\x05 \x01(\t\"Y\n\nFrameBatch\x12&\n\x06\x66rames\x18\x01 \x03(\x0b\x32\x16.frame_detection.Frame\x12\x10\n\x08\x62\x61tch_id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"r\n\tDetection\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\x12\r\n\x05label\x18\x05 \x01(\t\x12\x12\n\nconfidence\x18\x06 \x01(\x02\x12\r\n\x05\x63olor\x18\x07 \x01(\t\"l\n\x13\x46rameWithDetections\x12%\n\x05\x66rame\x18\x01 \x01(\x0b\x32\x16.frame_detection.Frame\x12.\n\ndetections\x18\x02 \x03(\x0b\x32\x1a.frame_detection.Detection\"\x96\x01\n\x13ProcessedFrameBatch\x12>\n\x10processed_frames\x18\x01 \x03(\x0b\x32$.frame_detection.FrameWithDetections\x12\x10\n\x08\x62\x61tch_id\x18\x02 \x01(\t\x12\x1a\n\x12processing_time_ms\x18\x03 \x01(\x03\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x32k\n\x15\x46rameDetectionService\x12R\n\rProcessFrames\x12\x1b.frame_detection.FrameBatch\x1a$.frame_detection.ProcessedFrameBatchb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'frame_detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAME']._serialized_start=42
  _globals['_FRAME']._serialized_end=135
  _globals['_FRAMEBATCH']._serialized_start=137
  _globals['_FRAMEBATCH']._serialized_end=226
  _globals['_DETECTION']._serialized_start=228
  _globals['_DETECTION']._serialized_end=342
  _globals['_FRAMEWITHDETECTIONS']._serialized_start=344
  _globals['_FRAMEWITHDETECTIONS']._serialized_end=452
  _globals['_PROCESSEDFRAMEBATCH']._serialized_start=455
  _globals['_PROCESSEDFRAMEBATCH']._serialized_end=605
  _globals['_FRAMEDETECTIONSERVICE']._serialized_start=607
  _globals['_FRAMEDETECTIONSERVICE']._serialized_end=714
# @@protoc_insertion_point(module_scope)
