# Generated by Django 5.1.2 on 2025-09-17 09:20

import core.base
import core.multilanguage.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0049_alter_devicestatus_code'),
        ('orders', '0027_orderstatusmapping_name'),
        ('terminals', '0048_routes_img_map'),
        ('user', '0023_alter_coreuser_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('drone_state_prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_logs_drone_state_prediction', to='devices.devicestatus')),
                ('end_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_logs_end_point', to='terminals.terminal')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_logs_order_item', to='orders.orderitem')),
                ('start_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_logs_start_point', to='terminals.terminal')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, core.multilanguage.models.MultiLanguageContentMixin, core.base.DependencyCheckMixin),
        ),
    ]
