# Generated by Django 5.1.2 on 2025-12-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_log', '0004_droneanomalyprediction_group_alter_flightlog_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightlog',
            name='log_file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
