# Generated by Django 5.1.2 on 2025-12-11 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0055_remove_device_registration_number_and_more'),
        ('flight_log', '0005_flightlog_log_file_path'),
        ('orders', '0028_bank_group_deliveryevent_group_deliveryoption_group_and_more'),
        ('surveillance', '0024_videoanalysis_created_by_videoanalysis_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightlog',
            name='drone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_logs_drone', to='devices.device'),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='fetch_count',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='fetch_data_status',
            field=models.CharField(blank=True, default='done', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='profile_drone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_logs_profile_drone', to='surveillance.surveillanceprofiledrone'),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_logs_order_item', to='orders.orderitem'),
        ),
    ]
