# Generated by Django 5.1.2 on 2025-12-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_log', '0006_flightlog_drone_flightlog_fetch_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightlog',
            name='service_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
