# Generated by Django 5.1.14 on 2025-12-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_log', '0007_flightlog_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightlog',
            name='fetch_anomaly_count',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='fetch_anomaly_status',
            field=models.CharField(blank=True, default='done', max_length=255, null=True),
        ),
    ]
