"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import sys
from pathlib import Path
from datetime import timedelta
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
print("BASE_DIR", BASE_DIR)
# Initialize environ
env = environ.Env()
# Đọc file .env từ thư mục BASE_DIR
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY", default="your-secret-key-here")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DJANGO_DEBUG", default=True)

# ALLOWED_HOSTS = env.list('DJANGO_ALLOWED_HOSTS', default=['*', 'host.internal.example'])
ALLOWED_HOSTS = ["*"]

# CSRF Trusted Origins
# W0-10: 배포처 주소는 코드 기본값이 아니라 환경변수로만 들어온다.
#        기본값은 로컬 개발 2개뿐이다 — 미설정 시 사내 주소로 조용히 붙지 않는다.
#        배포 origin 목록은 backend/.env.example 의 DJANGO_CSRF_TRUSTED_ORIGINS 참조.
CSRF_TRUSTED_ORIGINS = env.list(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    default=["http://localhost:8000", "http://127.0.0.1:8000"],
)
# CSRF_COOKIE_SAMESITE = 'Lax'  # Thay đổi về Lax để tương thích tốt hơn với cross-site
# CSRF_COOKIE_SECURE = (not DEBUG)  # Bật trong production
# SESSION_COOKIE_SAMESITE = 'Lax'  # Thay đổi về Lax để tương thích tốt hơn với cross-site
# SESSION_COOKIE_SECURE = (not DEBUG)  # Bật trong production
# Custom user model - phải định nghĩa trước INSTALLED_APPS
AUTH_USER_MODEL = "user.CoreUser"

# Application definition
INSTALLED_APPS = [
    # Core apps - phải đặt trước django.contrib.auth
    # Django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps
    "corsheaders",
    "ninja_extra",
    "simple_history",
    "guardian",
    "ninja_jwt",
    "ninja_jwt.token_blacklist",
    "safedelete",
    "rules",
    "django_ratelimit",
    "channels",
    "django_celery_beat",
    # Core apps
    "core",
    "core.user",
    "core.tag",
    "core.article",
    "core.discuss",
    "core.notifications",
    "core.file_management",
    "core.configuration",
    "core.logger",
    "core.menu",
    "core.role",
    "core.advanced_table",
    "core.multilanguage",
    "core.apikey_account",
    # 'geolocation',
    "terminals",
    # guardianx
    "common",  # 🚀 Core optimizations app
    "optimization",  # 🔢 Background processing optimizations
    "devices",
    "drone_communication",
    "delivery",
    "orders",
    # 'waybill',
    "print_format",
    "operation_settings",
    "dashboard",
    "report_template",
    "third_api",  # Third party integration APIs
    "stream_monitors",
    "checklist_setting",
    "operational_data",
    "partner",
    "flight_log",
    "surveillance",
    "proxy",  # Proxy for external content
    "handover",  # Handover Management APIs
    "task_status",  # Task status tracking for socket workflows
]

MIDDLEWARE = [
    # ★ [P-164 · 2026-09-17 턴 T · 차선 U56] 스키마 버전 헤더 `X-GX-Schema: 1.1` 한 겹.
    #   **줄을 새로 넣었다**(기존 줄은 한 자도 안 고쳤다). 자리는 **맨 위** — 바깥일수록
    #   안쪽 어느 겹이 답하든(캐시 적중 · 관문 401 · 5xx 표지) 전부 지난다.
    #   본문·상태줄은 안 만진다. 되돌리기는 `SCHEMA_HEADER_ENABLED = False` 한 줄이다.
    "common.schema_header.SchemaHeaderMiddleware",
    # ★ [P-198 · PERF-04 · 2026-09-20 턴 X · 차선 F] 설정 읽기를 **요청 한 벌 안에서
    #   한 번만** 한다. **줄을 새로 넣었다**(기존 줄은 한 자도 안 고쳤다).
    #   자리는 `SchemaHeaderMiddleware` 바로 아래 — 설정을 읽는 겹(인증·관문·로그·
    #   파트너)보다 **전부 바깥**이어야 그 읽기들이 기억 안에 든다. 스키마 헤더는
    #   이 겹보다 바깥에 남겨 둔다(그 겹의 「맨 위」 계약을 건드리지 않는다).
    #   응답·상태줄은 한 자도 안 만진다. 쓰기 요청(GET·HEAD·OPTIONS 밖)은 통과만 한다.
    #   [실측 2026-09-20] link-state 요청당 질의 **22 → 14** (그중 `adminconfig`
    #   12 → 4) · 설정 읽기 **6회 → 2회**(물음이 2종이다) · 6요청 누적 파이썬 −20%.
    #   되돌리기는 `CONFIG_READ_CACHE_ENABLED = False` 한 줄이다.
    "common.config_read_cache.ConfigReadCacheMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    'core.middleware.superuser_must_change_pass.EnforceSuperuserPasswordChangeMiddleware',
    "django.middleware.common.CommonMiddleware",
    "django.middleware.gzip.GZipMiddleware",  # 🚀 PERFORMANCE: Compress responses to reduce network transfer time
    # ★ [P-100 · 2026-09-07 턴 K · 차선 B] 5xx 본문에서 내부를 걷어내는 한 겹.
    #   **줄을 새로 넣었다**(기존 줄은 한 자도 안 고쳤다). 자리는 GZip **바로 아래**:
    #     ① GZip 보다 안쪽 — 압축 전 본문을 봐야 표지를 읽는다.
    #     ② 5xx 를 만드는 다른 어떤 겹보다도 바깥 — 그래야 그 본문이 이 겹을 지난다.
    #   상태줄은 안 고친다. 하는 일은 「무엇이 샜나」뿐이다.
    #   되돌리기는 `SAFE_ERROR_BODY = False` 한 줄이다.
    "common.error_body.SafeErrorBodyMiddleware",
    # ★ [SEC-21 · 2026-09-17 턴 T · 차선 F] 율제한 초과(`Ratelimited`)를 **429 JSON · 한국어 ·
    #   남은 초**로 낸다. **줄을 새로 넣었다**(기존 줄은 한 자도 안 고쳤다). 자리는
    #   `SafeErrorBodyMiddleware` **바로 아래** — `process_exception` 은 안쪽부터 불리므로
    #   이 겹이 먼저 `Ratelimited` 를 받고, 그 밖의 예외는 그대로 위로 지나간다.
    #   dj-core 의 `@ratelimit` 은 §0.4 라 못 고친다 — 길목에서 답 모양만 바꾼다(D-348).
    #   되돌리기는 이 줄 하나를 빼는 것이다(영문 HTML 403 으로 돌아간다).
    "common.rate_limit_body.RateLimitBodyMiddleware",
    "core.middleware.csrf_exempt_swagger.CSRFExemptSwaggerMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "core.middleware.jwt_user_restore.JWTUserRestoreMiddleware",  # 🔧 FIX: Restore user sau khi AuthenticationMiddleware reset
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "proxy.middleware.RemoveXFrameOptionsMiddleware",  # Remove X-Frame-Options for proxy endpoints
    # ★ [P-274 · 2026-09-25 턴 AG] 못 푸는 `Bearer` 한 줄을 **500 이 아니라 401** 로 낸다.
    #   **줄을 새로 넣었다**(기존 줄은 한 자도 안 고쳤다). 자리는 바로 아래 dj-core
    #   `TokenRefreshMiddleware` **바로 위**다 — 그 파일의 `except Exception` 안에서
    #   `jwt.decode` 를 try 없이 다시 불러 **잡는 자리에서 새로 터지고**, 미들웨어라
    #   모든 요청에 걸려 읽기 면 **364자리 전부가 500** 이 된다 [실측 2026-09-23 턴 AF].
    #   dj-core 는 §0.4 라 한 줄도 못 고친다 — 그래서 **앞에서 답한다.**
    #   ★ 자리를 여기로 잡은 근거: 해독하는 dj-core 겹은 `refresh_token.py` **하나뿐**이다
    #     [실측: `core/middleware/*.py` 중 `jwt.decode|AccessToken` 을 쓰는 파일 1개].
    #     더 바깥에 두면 세션·CSRF·인증 겹이 이 401 뒤로 밀린다.
    #   ★ 만료 토큰은 **안 건드린다** — 구조적으로 풀리는 토큰은 그냥 지나간다.
    #   되돌리기는 `JWT_GUARD_ENABLED = False` 한 줄이다.
    "common.jwt_guard.JwtGuardMiddleware",
    "core.middleware.refresh_token.TokenRefreshMiddleware",
    # ★ [UX-24a · 2026-09-05 턴 F · 차선 S] 월(wall) 표시 토큰 한 겹. **줄을 새로 넣었다**
    #   (기존 줄은 한 자도 안 고쳤다). 자리는 `AccessGateMiddleware` **바로 위** —
    #   응답 캐시보다 바깥이어야 두 가지가 성립한다:
    #     ① 캐시에 적중한 월 요청도 이 겹을 지난다 (D-341 착시 ⑦)
    #     ② `request.user` 를 여기서 세워야 캐시 열쇠가 **그 사용자 것**이 된다
    #   하는 일은 하나다: 월 토큰을 들고 온 요청의 **쓰기와 목록 밖 경로를 403 으로 끊는다**
    #   (§0.4 라우트까지 전부 덮는다). 월 토큰이 없는 요청은 한 자도 안 만진다.
    #   되돌리기는 `WALL_TOKEN_ENABLED = False` 한 줄이다.
    "common.wall_token.WallTokenMiddleware",
    # ★ 전역 접근 관문 (D-348 · D-343 ③). **캐시보다 바깥이어야 한다**(D-341 착시 ⑦) —
    #   캐시 안쪽에 두면 열려 있던 동안 익명으로 채워진 항목이 관문을 지나지 않고 그대로 나간다.
    #   §0.4 금지구역의 라우트도 이 한 겹이 덮는다. 파일은 한 줄도 건드리지 않는다.
    "common.access_gate.AccessGateMiddleware",
    # ★ [P-105 · 2026-09-07 턴 M · 차선 B] **역할 0 관문.** 줄을 새로 넣었다
    #   (기존 줄은 한 자도 안 고쳤다). 자리는 `AccessGateMiddleware` **바로 아래** —
    #   세 조건을 동시에 만족하는 자리가 여기뿐이다:
    #     ① 응답 캐시(`UniversalCacheMiddleware`)보다 **바깥** — 안쪽에 두면 역할이
    #        있던 동안 채워진 항목이 관문을 지나지 않고 그대로 나간다(D-341 착시 ⑦)
    #     ② `AccessGateMiddleware` **다음** — 익명은 401, 역할 0 은 403.
    #        순서가 「누구인지 모른다」와 「누구인지는 아는데 안 된다」를 가른다(D-290)
    #     ③ dj-core `JWTUserRestoreMiddleware`(위쪽)보다 **아래** — 그 겹이 세워 준
    #        `request.user` 만 본다. 토큰을 또 풀면 인증기가 둘이 된다(D-337 계열)
    #   반경 [실측 2026-09-07 · 런타임 열거]: 705 오퍼레이션 / 578 경로 / 876 URL 패턴.
    #   되돌리기는 `ROLE_GATE_ENABLED = False` 한 줄이다.
    "common.role_gate.RoleGateMiddleware",
    # ★ [UX-24 · 2026-09-05 턴 E · 차선 S] 동시 세션 상한 한 겹. **줄을 새로 넣었다**
    #   (기존 줄은 한 자도 안 고쳤다). 자리는 `ApiContractStatusMiddleware` 바로 위 —
    #   같은 두 조건을 만족해야 한다: 캐시보다 바깥 · GZip 보다 안쪽(본문을 JSON 으로
    #   읽는다). 이 한 겹이 하는 일은 둘뿐이다:
    #     ① 로그인 성공 응답에서 세션을 대장에 남기고 상한을 넘으면 가장 오래된 것을 끊는다
    #     ② dj-core 의 영문 401 "Token from different session" 에 사전 문구를 붙인다
    #   **상태코드는 안 바꾼다.** 되돌리기는 `SESSION_LIMIT_ENABLED = False` 한 줄이다.
    "common.session_limit.SessionLimitMiddleware",
    # ★ 반드시 UniversalCacheMiddleware **바로 위** (W0-18 · D-248). 두 조건이 있다:
    #   ① 캐시보다 바깥 — UniversalCacheMiddleware 는 캐시 적중 시 저장된 본문을
    #      **항상 JsonResponse(200)** 으로 다시 만든다(universal_optimization.py:872).
    #      캐시 안쪽에 두면 적중한 요청에서 승격이 통째로 사라진다.
    #   ② GZipMiddleware 보다 안쪽 — 압축되기 전 본문을 봐야 JSON 을 읽을 수 있다.
    #   API_CONTRACT_PROMOTE_ERROR_STATUS 가 False 면 아무것도 바꾸지 않는다.
    "common.api_contract.ApiContractStatusMiddleware",
    "common.universal_optimization.UniversalCacheMiddleware",  # 🌍 UNIVERSAL: System-wide optimization cho ALL models & views
    "ninja.compatibility.files.fix_request_files_middleware",
    "core.middleware.dependency_check.DependencyCheckMiddleware",
    'core.middleware.connection_management.DatabaseConnectionMiddleware',  # Database connection management
    "partner.middleware.PartnerAuthMiddleware",  # Disabled: Partner auth handled in CustomJWTAuth
    'core.logger.middleware.CoreLoggingMiddleware',

    # 'core.middleware.remove_group_field.GroupFeatureMiddleware',
]

# ── 응답 계약 (W0-18 · D-248 · D-212) ────────────────────────────────────────
# 권한거부를 HTTP 200 + 본문 403 이 아니라 **실제 HTTP 403** 으로 내보낼 것인가.
#
#   False (기본)  기존 동작 그대로. 미들웨어는 경로에 있으나 통과만 한다.
#   True          `{"success": false, …, "status_code": 4xx}` 를 실제 상태로 승격.
#
# 되돌리기는 이 한 줄이다. 켜기 전에 반드시 읽을 것:
#   docs/agent/evidence/W0-18/backward_compat_impact.md
#     §2-2  승격 시 무증상 실패 후보 21곳 (프론트 · 대부분 delivery 화면)
#     §5    단계적 롤아웃 순서와 되돌림 기준
API_CONTRACT_PROMOTE_ERROR_STATUS = (
    os.environ.get("API_CONTRACT_PROMOTE_ERROR_STATUS", "false").lower() == "true"
)

# ── P-198 · PERF-04 — 설정 읽기 기억 (2026-09-20 턴 X · 차선 F) ───────────────
#
# 요청 한 벌 안에서 같은 설정 물음을 한 번만 묻는다(`common/config_read_cache.py`).
# 답은 바꾸지 않고 **묻는 횟수만** 줄인다. 기본값은 **켜짐**이다.
#
#   False  겹이 `MiddlewareNotUsed` 로 경로에서 빠진다. 제품은 고치기 전과 똑같이 돈다
#
# ★ 이름을 **환경에서도** 받는 이유는 되돌리기가 아니라 **재기 위해서**다:
#   같은 코드·같은 데이터·같은 창에서 이 한 칸만 바꿔 두 벌을 재야 「좋아진 것이
#   코드 덕인가」를 말할 수 있다. 저장소 파일을 고쳐서 A/B 를 하면 그 사이에 남이
#   다른 파일을 고치고, 그러면 잰 차가 **무엇의 차인지 모르게 된다** [실측: 이 턴에
#   실제로 그랬다 — 차선 U1 이 `kernels/k1_event/services.py` 를 내 두 벌 사이에 고쳤다].
#
#     docker exec -e CONFIG_READ_CACHE_ENABLED=false gx-shell python manage.py runserver …
CONFIG_READ_CACHE_ENABLED = (
    os.environ.get("CONFIG_READ_CACHE_ENABLED", "true").lower() == "true"
)

# ── SEC-18 ⑥ **예외 응답이 본문에 내부를 싣지 않는다** (P-100 · 2026-09-07 · 차선 B) ──
#
# 운영 프로필 계약의 여섯째 수다. 앞의 다섯(`config/settings_prod.py` ①~⑤ ·
# `scripts/verify_prod_settings.py` 가 **실제로 띄워서** 재는 그 다섯)은 전부
# 「닫힌 쪽이 기본이고 열린 값은 선언으로만 열린다」는 같은 모양이다. 이 수도 같다.
#
#   ⑥ 5xx 응답 본문에 `Traceback` · `pydantic` · `File "` · 내부 파일경로가
#      **한 자도 없다.** 기본 True(닫힌 쪽) · 선언으로만 끌 수 있다.
#
# 왜 다섯이 아니라 여섯이어야 했나 — **출생 표본** [실측 2026-09-07 · P-100]
#     GET /api/report-template/  (권한 없는 계정)  ->  HTTP 500 · text/plain 951바이트
#         Traceback (most recent call last):
#           File "/usr/local/lib/python3.11/site-packages/ninja_extra/operation.py", line 216
#           ... pydantic_core._pydantic_core.ValidationError
#   ②(DEBUG=False)만으로는 이 자리가 안 닫힌다: 개발 프로필로 뜬 판이 **바로 이 본문**을
#   내보내고 있었고, 운영 프로필로 떠도 `DEBUG=False` 는 django-ninja 의 역추적만 막을 뿐
#   「본문에 무엇이 실렸나」를 아무도 재지 않았다. 재지 않는 것은 계약이 아니다(D-301).
#
# ★ 관측 이름 — 판정기가 읽을 자리는 `settings.SAFE_ERROR_BODY` 하나다.
#   (`scripts/verify_prod_settings.py` 의 PROBE 는 지금 다섯 수의 이름만 찍는다.
#    여섯째를 세려면 그 PROBE 와 `judge()` 에 이 이름 한 줄이 더 있어야 하고,
#    그 파일은 게이트 소유라 이 차선이 건드리지 않는다 — P-100 보고에 그대로 적었다.)
#
# 구현·사유는 `common/error_body.py`. 되돌리기는 이 한 줄이다(D-212).
SAFE_ERROR_BODY = (
    os.environ.get("SAFE_ERROR_BODY", "true").lower() == "true"
)

# ── P-105 역할 0 관문 (2026-09-07 턴 M · 차선 B) ─────────────────────────────
#
#   True (기본)  `user.roles` 가 비어 있는 계정은 API 면에서 **403** 을 받는다.
#                닿는 자리는 `common/role_gate.py::ROLE_ZERO_ALLOWED` 에 손으로
#                적어 둔 것들(로그인 절차 + 역할 대기 문 하나)뿐이다.
#   False        미들웨어가 경로에 있어도 **한 요청도 안 막는다.** 역할 대기 문은 남는다.
#
# 무엇이 이 줄을 만들게 했나 [실측 2026-09-07 · `gxprobe_e2e` · roles == []]:
#   화면이 실제로 부르는 53자리 중 **21자리가 200 + 실자료**였다 — 사건 목록(카메라명·
#   시각·판정) · 배송 · 사용자 그룹 · **남의 계정 전문**(`get-user-detail/115`).
#   같은 순간 역할 보유 계정이 본 수는 22 였다. 즉 역할 0 은 운영자와 **거의 같은 것**을
#   보고 있었고, 「인증됐다」와 「봐도 된다」 사이에 아무것도 서 있지 않았다.
#
# ★ 이 판정을 `getattr(u, "role", None)` 으로 내지 않는다 — 이 제품에 그 필드는 **없고**,
#   없는 것을 읽으면 언제나 None 이 나온다. 그 None 을 측정으로 읽은 것이 이 사고를
#   세 턴 동안 덮었다. 역할은 M2M `user.roles` 다.
#
# 구현·사유는 `common/role_gate.py`. 계약은
# `docs/agent/evidence/P-105/backend/CONTRACT.md`. 되돌리기는 이 한 줄이다(D-212).
ROLE_GATE_ENABLED = (
    os.environ.get("ROLE_GATE_ENABLED", "true").lower() == "true"
)

#: 역할을 줄 수 있는 관리자를 DB 에서 못 찾았을 때 화면이 부를 이름. **비어 있으면
#: 이름 없는 문장**으로 나간다 — 아무 이름이나 지어 넣으면 화면이 틀린 사람에게
#: 연락하라고 말한다(D-290 · D-301).
# ⚠ **`ROLE_REQUEST_ADMIN_NAME` 을 두지 않았다** [실측 2026-09-07 · `verify_dormant.py`
#   가 잡았다: "㉢ 설정 빔 — 새로 만드는 것은 켜진 상태로 태어나야 한다"].
#   처음에는 「관리자를 DB 에서 못 찾았을 때 쓸 이름」으로 이 값을 두었다. 그런데
#   기본값이 빈 문자열이면 그 분기는 **한 번도 안 도는 코드**이고, 값을 채워 넣으면
#   그때부터 화면이 **DB 가 아니라 설정 파일이 말하는 사람**에게 연락하라고 말한다.
#   둘 다 원하지 않는다. 못 찾으면 `source="none"` 으로 **없다고 낸다**(D-290 · D-301).

# ── UX-24 동시 세션 상한 (2026-09-05 턴 E · 차선 S) ─────────────────────────
#
#   True (기본)  로그인 성공을 대장에 남기고, dj-core 의 영문 401
#                "Token from different session" 에 사전 문구를 붙인다.
#   False        미들웨어가 경로에 있으나 통과만 한다. **되돌리기는 이 한 줄이다.**
#
# ⚠ 이 값을 켜도 **동시 접속은 여전히 1개다.** 그 1개는 dj-core 의 자료구조이고
#   §0.4 라 우리가 못 고친다 — 사유와 실측은 `docs/agent/authn_paths.md` §8 에 있다.
#   여기서 켜지는 것은 「상한 정책」과 「끊긴 이유를 말하기」뿐이다.
SESSION_LIMIT_ENABLED = (
    os.environ.get("SESSION_LIMIT_ENABLED", "true").lower() == "true"
)

# ★ [UX-24a · 2026-09-05 턴 F · 차선 S] 월(wall) 표시 토큰 — 세종 판정 P-62.
#   **세션이 아니다.** 읽기 전용 · 12시간 · 화면 `/wall` 하나 · **쓰기 0**.
#   대장은 `docs/agent/authn_paths.md` §9, 구현과 사유는 `common/wall_token.py`.
#   끄면 이 문은 통째로 401 이다 — 다른 어떤 문도 영향받지 않는다(되돌리기 한 줄).
WALL_TOKEN_ENABLED = (
    os.environ.get("WALL_TOKEN_ENABLED", "true").lower() == "true"
)

# ★ **전부 회수**의 자리. 이 시각(epoch 초) **이전에 발급된 월 토큰은 전부 죽는다.**
#   캐시가 아니라 설정값인 이유: 재기동해도 살아 있어야 하는 판정이기 때문이다.
#   `python manage.py wall_token revoke --all` 이 넣을 값을 알려 준다.
WALL_TOKEN_EPOCH = int(os.environ.get("WALL_TOKEN_EPOCH", "0") or 0)

# ★ D-349 착시 ⑧ — 봉투. **F-05 진입면은 래칫에서 제외한다.**
#
#   전역 승격은 무증상 실패 후보 21곳(대부분 delivery 화면)을 건드린다 — 그래서 위 플래그는
#   아직 꺼져 있다. 그러나 **계약 상대가 읽는 면은 다르다**:
#   에스비 App 이 HTTP 200 을 보고 실패를 성공으로 읽으면 그건 계약 사고다.
#   게이트웨이·모니터링·재시도 로직이 전부 속고, **우리 판정기가 첫 피해자였다**(18 → 11).
#
#   그래서 승격을 **경로로 좁혀** 먼저 건다. 전역 플래그가 꺼져 있어도 이 경로들은 승격된다.
#   되돌리기는 이 목록을 비우는 것이다.
#   ★ [A2 접두 · 2026-09-04] **한 번에 하나씩 넓힌다.** 그 턴에 `/api/stream-monitors/`
#     를 더했다(라우트 28건 · 화면이 실제로 부르는 호출 3건 · 시험 2파일 [실측]).
#     왜 하나씩인가 — 전역으로 켜면 652자리의 거절 모양이 **같은 순간에** 바뀌고,
#     그때 깨지는 화면이 어느 접두 때문인지 아무도 못 가른다. 되돌리기도 전부냐 전무냐가 된다.
#
#   ★ [A2 접두 · 2026-09-26 · 차선 S · SEC-11] `/api/surveillance/` 를 더한다.
#     ★★ **먼저 잰 것부터 적는다: 앞의 두 접두는 296건 중 0건을 갚았다** [실측].
#        인벤토리를 다시 뜨니 `promoted` 가 11 → 61 로 늘었는데, 그 61건 중
#        `authz_path_permission` 을 가진 것은 **0건**이었다 — 승격된 자리는 전부
#        원래 `clean` 이던 라우트다. 봉투가 갈리는 296건은 다른 접두 아래 산다:
#        surveillance 48 · delivery 48 · terminals 38 · devices 33 · handover 25 ….
#        「대부분 갚았다」고 적었으면 그것이 거짓말이 됐을 자리다(지시서 §4-3).
#     왜 이 접두인가 — 갚을 수 있는 것 중 **가장 크고**(48건), §0.4 금지구역이 아니며,
#     **화면이 실제로 지나간다**(캡처 24장의 호출 중 7건 · `D-386/screen_routes.json`).
#     `/api/handover/`(25건)는 화면이 한 번도 부르지 않아 켜도 지나가는 것이 없다.
#     delivery·terminals(86건)는 §0.4 이고 무증상 실패 후보가 몰려 있는 자리다.
#
#   ★ [A2 접두 셋 · 2026-09-05 · 차선 S · SEC-11a] `/api/advanced-table/` ·
#     `/api/config-management/` · `/api/user-groups/` 을 더한다.
#     왜 이 셋인가 — **추측이 아니라 교집합이다.** 둘을 겹쳐 골랐다:
#       ① 신선본 인벤토리(`D-343/route_inventory.json` · 측정일 2026-09-05)의
#          `envelope=authz_envelope` — 봉투가 갈리는 248건이 사는 자리
#       ② 화면 캡처 24장이 **실제로 부른** 호출(`D-386/screen_routes.json`)
#     교집합은 다섯 접두였고, 그중 큰 셋이 이 셋이다 [실측]:
#       advanced-table 12건(화면호출 24) · config-management 7건(24) · user-groups 5건(51)
#       — 남은 둘은 flight-log 4건(호출 1) · departments 3건(호출 1)로 작다.
#     이 셋은 **화면 열리는 순간 세 접두가 다 불린다**(테마·설정·권한 스키마) —
#     즉 거부가 200 으로 나가면 그 거부를 **모든 화면이** 삼킨다.
#     안전 근거 [실측]: W0-18 §2-2 의 무증상 실패 후보 21곳(15파일) 중
#     이 세 접두를 부르는 파일은 **0개**다.
#     손 밖(SEC-11b): delivery 48 · terminals 38 · orders 11 은 §0.4 금지구역이고,
#     devices 33 · handover 25 는 화면이 한 번도 부르지 않는다 — 인수자 판단이다.
#   ★ [A2 접두 둘 · 2026-09-05 TC · 차선 S · SEC-11a] `/api/flight-log/` ·
#     `/api/departments/` 를 더한다. **이 둘이 남은 마지막이다.**
#     지난 턴이 이름으로 적어 둔 그대로다: 남은 224건 중 **화면이 실제로 부르는 것은
#     7건**이고 그 7건이 이 두 접두 아래 전부 있다 —
#       flight-log 4 (`GET …/flight-log` · `DELETE …/delete/{ids}` ·
#                     `GET …/detail/{id}` · `GET …/download-log/{id}`)
#       departments 3 (`POST /api/departments` · `DELETE …/delete/{department_ids}` ·
#                      `PUT …/{department_id}`)
#     켜면 **부르는 자리(SEC-11a)의 `authz_envelope` 가 0** 이 된다.
#     ★ `POST /api/departments` 는 **끝의 `/` 가 없는 모음 라우트**다. `startswith`
#       접두로는 안 걸리고, `common.api_contract.path_in_scope()` 의 둘째 규칙이
#       그것을 메운다 — 지난 턴의 출생 표본(225 vs 224)이 바로 이 자리였다.
#       그래서 접두는 반드시 **끝에 `/` 를 붙여** 적는다. 떼면 그 규칙이 죽는다.
#     ★ **미리 적어 둔다 — `clean` 도 둘 줄어든다** [산술]. `envelope_state()` 는
#       승격 접두 안이면 `authz_path_permission` 여부와 무관하게 `promoted` 로 적는다.
#       그래서 원래 `clean` 이던 `GET /api/departments` · `GET …/{department_id}` 도
#       `promoted` 로 옮겨 간다. 이상이 아니라 판정 순서다 — 안 적어 두면 다음 사람이
#       「clean 이 왜 줄었나」로 읽는다(지난 턴 「승격 61건 중 authz 0건」과 같은 모양).
#     ★ `departments` 의 뷰는 `core.user.api`(dj-core · §0.4)다. **그 파일을 고치지
#       않는다** — 고치는 것은 우리 쪽 접두 문자열 하나이고, 미들웨어가 밖에서 상태줄을
#       바꾼다. 금지구역 안으로 손을 넣지 않는 것이 이 방식을 고른 이유다.
#     안전 근거 [실측]: W0-18 §2-2 무증상 실패 후보 15파일 중 이 두 접두를 부르는
#     파일 **0개**. flight-log 호출부는 `features/FlightLogAnalysis/**` 5파일이고
#     그 어느 것도 후보 목록에 없다. departments 는 `frontend/src` 호출부 0건이다.
#   ★ [A2 접두 둘 · 2026-09-05 턴 E · 차선 S · SEC-11a] `/api/partner/` ·
#     `/api/third-api/` 을 더한다. **12건.**
#     ★★ 먼저 잰 것부터 적는다 — **화면이 부르는 라우트의 봉투 잔여는 이미 0 이다**
#        [실측 2026-09-05]. 캡처 24장이 부른 고유 호출 33건을 인벤토리와 대조하니
#        promoted 27 · clean 5 · **authz_envelope 0** · 미대조 1(`POST /api/proxy/notam`).
#        그러니 「화면」쪽으로는 더 갚을 것이 없다. 남은 217건은 다른 곳에 산다.
#     그래서 **SEC-11a 의 정의로 되돌아갔다**(P-35): 이 절의 몫은 「화면 · 계약 ·
#     **외부 진입면**」이다. 잔여 217 중 외부 진입면은 이 둘이고, 그 둘의 정체는:
#        /api/partner/    11건 — 파트너 API 키 **발급·회전·폐기·상태전환**
#        /api/third-api/   1건 — 제3자 연동 주문 생성
#     바깥의 기계가 읽는 면이다. 거부가 200 으로 나가면 연동자·게이트웨이·재시도 로직이
#     전부 실패를 성공으로 읽는다 — **F-05 계약 사고와 정확히 같은 모양**이다(D-349).
#
#     ★ 함께 **안 더한 것**과 그 사유 — 이것이 이번 판단의 절반이다:
#        delivery 48 · terminals 38 · orders 11  §0.4 금지구역 (97건)
#        devices 33 · handover 25                 **이미 판정이 있다** — SEC-11b(손 밖) ·
#          `tests/test_api_contract.py::test_forbidden_zone_prefixes_stay_out` 이
#          「우리가 승격하지 않는다」를 못박아 두었다. 승격은 인수자 판단이다(P-35)
#        dashboard 7 · checklist-setting 5        W0-18 §2-2 무증상 실패 후보 21곳이
#          실제로 부르는 자리다(`useDashboard.ts` · `CheckListSetting.tsx`)
#        report-template 5 · operational-data 8   기존 계약 시험이 **플래그 OFF 에서
#          200/500** 을 못박고 있다. 여기를 접두로 켜면 그 시험이 빨개지는데, 그것은
#          「고쳤다」가 아니라 **계약을 말없이 바꾼 것**이다 (D-327)
#        roles 9 · user-profiles 5 · levels·positions·teams 9 · genders·nationalities 2
#          rj-core 가 그리는 인수 관리 화면의 마스터 자료다. 그 화면의 오류 처리를
#          **이 저장소에서 읽을 수 없다**(rj-core 는 node_modules 에도 없다) —
#          못 재는 것을 켜는 것은 판정이 아니라 도박이다. SEC-11b 로 남긴다
API_CONTRACT_PROMOTE_PATHS = tuple(
    p for p in os.environ.get(
        "API_CONTRACT_PROMOTE_PATHS",
        "/api/dsm/,/api/stream-monitors/,/api/surveillance/"
        ",/api/advanced-table/,/api/config-management/,/api/user-groups/"
        ",/api/flight-log/,/api/departments/"
        ",/api/partner/,/api/third-api/"
        # ★ [P-88 · 2026-09-07 턴 J · 조율자] **반경 1.** 접두는 `/api/devices/` 가
        #   아니라 `/api/devices/devices-management` 다 — 세종이 이의 ②를 수용했다.
        #   `/api/devices/` 를 켰다면 인벤토리 **66건**이 같이 뒤집힌다(cameras 9 ·
        #   packaging-specifications 9 · libraries-management 7 · 부품표 5×6 …).
        #   빨간 자리는 **1건**이고, 그 자리를 덮는 가장 작은 접두가 이것이다(11건).
        #   「전/후 없이 켜지 않는다」를 지키려면 전/후를 잰 만큼만 켜야 한다.
        #
        #   전/후 [실측 2026-09-07 · 계정 `gxprobe_e2e` · 같은 요청]:
        #     전  HTTP **200** + `{"success": false, "status_code": 403,
        #         "message": "Permission denied."}`  → 화면은 **빈 표**를 그린다.
        #         사람은 「자료가 없다」로 읽는다. 오류율 대시보드도 성공으로 센다(D-358)
        #     후  HTTP **403**                        → 「볼 권한이 없습니다」
        #
        #   ★ 세 턴 동안 「거절 계정이 없어 못 잰다」고 적혀 있었다 — **있었다.**
        #     `.env.gates` 의 `gxprobe_e2e`(route-alive 탐침)가 이 라우트에서
        #     그대로 거절당한다. 없다고 적힌 것을 찾아보지 않은 것이 세 턴의 값이다.
        #   ⚠ 되돌리기: 이 줄을 뺀다. 되돌릴 조건 — `/device` 화면에서 권한 거절이
        #     **스피너 고착**으로 나타나면. 지금은 우리 층 전역 거절 처리기가 받는다.
        ",/api/devices/devices-management"
        # ★ [D-462 · 2026-09-15 턴 P · `verify_envelope` 가 잡음] 역할 관리 화면의 목록 실재 문구
        #   (`ListRealityNote` · `App.tsx:754` `countUrl="/api/roles/"`)가 이 문을 부른다 —
        #   **화면이 부르는 라우트는 봉투 갈림 0**(SEC-11a · P-35). dj-core 의 거절은 200 봉투라
        #   상태줄만 403 으로 올린다(본문 불변 · C 차선 실측). 화면은 `.catch` 로 「세지 못했습니다」를 그린다.
        ",/api/roles/"
        # ★ [SEC-11a · 2026-09-05 턴 F · 차선 S] 잔여 205 → 193.
        #   이 둘은 잔여 안에서 **우리가 읽을 수 있는 화면**이 부르는 유일한 자리다.
        #   승격을 정하기 전에 그 화면들의 오류 처리를 전부 읽었다 [실측]:
        #     features/Dashboard/hooks/useDashboard.ts        `response.success` 를 본다
        #     DeliveryDashboard/{index,indexV2,indexV3,AnYang}.tsx
        #                                                    try/**finally** 로 스피너를 끈다
        #     features/checklistSetting/hooks/useChecklistSetting.ts
        #                                                    호출마다 try/**catch**/finally ·
        #                                                    `error.response.data.message` 를 그린다
        #   즉 승격 뒤에 사람이 보는 것은 지금과 **같고**(빈 화면),
        #   달라지는 것은 HTTP 상태가 참이 되는 것뿐이다. 승격 전에는 거절이 200 으로
        #   나가 오류율 대시보드가 그것을 **성공으로 센다**(D-358).
        #   ⚠ 되돌리기: 이 두 줄을 뺀다. 되돌릴 조건 — 이 화면들에서 권한 거절이
        #     **스피너 고착**으로 나타나면(W0-18 §2-1) 그때가 되돌릴 때다.
        #     지금은 네 화면 전부 `finally` 로 스피너를 끄고, 전역
        #     `unhandledrejection` 처리기는 저장소에 **0건**이다 [실측].
        ",/api/dashboard/,/api/checklist-setting/"
        # ★ [SEC-11a · 2026-09-07 턴 J · 차선 S] 잔여 185 → 136. **접두 넷 · 49건.**
        #   세 턴 동안 「거절 계정이 없어 승격 안전성을 못 잰다」로 잠겨 있던 자리다.
        #   `.env.gates` 의 `gxprobe_e2e` 가 **역할이 하나도 없는 계정**이고
        #   (`user.roles.all()` 이 빈 쿼리셋 → `core/role/permission.py:_check_path_permission`
        #   이 `has no roles` 로 False 를 낸다), 그래서 `@path_permission` 이 붙은
        #   모든 라우트에서 **방법·경로와 무관하게** 거절된다. 그 계정으로 쟀다.
        #
        #   전/후 [실측 2026-09-07 · gxprobe_e2e · 같은 요청 · GET 만]:
        #     전  HTTP **200** + `{"success": false, "status_code": 403, ...}`  (17자리)
        #     후  HTTP **403**
        #   ⚠ 쓰기(POST/PUT/DELETE)는 두드리지 않았다 — 같은 데코레이터·같은 계정이라
        #     판정이 같다는 것은 **추론**이고 실측이 아니다. 그렇게 적어 둔다.
        #
        #   접두마다 **반경을 세고** 켰다(빨강의 반경만큼만 자른다 · 턴 K §1 이의 ①):
        #     /api/operational-data/                반경 17 (authz 8 · clean 9 무영향)
        #     /api/handover/handover/               반경 25 (authz 25)
        #     /api/devices/libraries-management/    반경  7 (authz 7)
        #     /api/devices/packaging-specifications/ 반경 9 (authz 9)
        #   ★ `/api/handover/` 가 아니라 `/api/handover/handover/` 인 이유:
        #     `test_forbidden_zone_prefixes_stay_out` 이 `/api/handover/list` 가
        #     승격되지 않는 것을 못박는다. 실재 25건은 전부 `handover/handover/` 아래라
        #     한 칸 더 들어가면 그 시험을 건드리지 않고 25건을 전부 덮는다.
        #   ★ `/api/devices/` 가 아닌 이유: 그 접두의 반경은 66이고 cameras 9 가
        #     그 안에 있다(아래 「안 켠 것」).
        #
        #   화면 쪽 [실측 · 원본 줄 단위]: 이 넷을 부르는 훅 전부가 `try/catch` 로
        #   **되던지지 않고 값을 돌려준다** — 그래서 거절이 컴포넌트까지 안 올라간다.
        #     useHandover · useComments · useCompletedNotice · useHandoverManagement ·
        #     useNoticeManagement · useLibrary · packaging/useAPI · partnerManagement/useAPI ·
        #     operationalData/useAPI · useOperationalNotice · useFileManagement
        #   `showLoading()` 을 켜는 자리는 전부 `finally { hideLoading() }` 를 갖는다 —
        #   턴 I 가 「finally 가 하나씩 모자란다」고 적어 둔 그 한 자리는 셋 다
        #   **스피너를 켜지 않는 함수**였다(`getFieldsTemplate` ×2 는 `/api/print-format/`
        #   을 부르고, `uploadFileOperationalData` 는 showLoading 자체가 없다).
        #
        #   ⚠ 되돌리기: 이 네 줄 중 해당 줄을 뺀다. 되돌릴 조건 — 그 화면에서
        #     권한 거절이 **스피너 고착**으로 나타나면(W0-18 §2-1).
        #
        #   ★ 안 켠 것 — 사유를 이름으로 (SEC-11a 잔여 136 중 우리 층 14):
        #     `/api/devices/cameras/` 9건 — **턴 안에서 사유가 사라졌다. 그래서 켰다.**
        #        처음 적은 사유: `features/otherEquipments/hooks/useEquipment.ts` 의 다섯 함수
        #        (`getEquipmentList` · `getDetailEquipment` · `createEquipment` ·
        #        `updateEquipment` · `changeStatusEquipment`)가 `showLoading()` 뒤
        #        `await API.*` 를 **try 없이** 불렀다 → 승격하면 `hideLoading()` 이
        #        영원히 안 돌아 **스피너 고착**. 그 파일은 `frontend/` 라 차선 S 의 손 밖이었다.
        #        ★ 같은 턴에 **차선 C 가 다섯 다 `try/catch/finally` 로 감쌌다** — 이 주석에
        #          이름으로 적어 둔 것을 그대로 읽고 고쳤다. 다시 세었다 [실측 2026-09-07]:
        #          `await API.*` 를 부르는 7함수 **전부** try·finally·hideLoading 을 갖는다.
        #          부르는 쪽(`OtherEquipments.tsx` · `DetailEquipment.tsx`)도 `success` 로 갈린다.
        #          벽이 없어졌으므로 **사유를 지우고 켠다** — 사유가 사라졌는데 줄만 남기면
        #          그 줄이 다음 턴의 거짓 벽이 된다.
        #        전/후 [실측 · gxprobe_e2e]: 200+봉투403 → HTTP 403 (아래 넷과 같은 방식)
        # ★ [P-100 · 2026-09-07 턴 K · 차선 B] **반경 5.** `/api/report-template/` 를 켠다.
        #   앞판이 「다음 턴에 표본을 옮기면 켤 수 있다」고 이름으로 적어 둔 그 줄이다.
        #   막고 있던 것은 제품이 아니라 **계약 시험의 표본 소유**였고, 이번 턴에
        #   `backend/tests/test_api_contract.py` 의 표본을 실제로 옮겼다:
        #     ROUTE_LIST_SCHEMA        /api/report-template  →  /api/delivery/processing/drones
        #       (§0.4 안이라 우리가 **앞으로도 승격하지 않는다** — ROUTE_NO_SCHEMA 를
        #        턴 J 에 옮긴 것과 같은 사유다. B 부류 7건 중 5건이 delivery 다)
        #     ROUTE_FORMERLY_SWALLOWED /api/report-template/1 은 **그대로 둔다** —
        #       C→A 로 고친 8건 중 GET 인 것이 이 하나뿐이다. 대신 되돌림 시험이
        #       **지렛대 둘**(플래그 OFF + 이 접두 제거)을 다 내리고 200 을 확인한다.
        #       기대를 403 으로 고쳐 지우지 않았다(D-327).
        #   무엇이 닫히나 [실측 2026-09-07 · gxseed_u4_official(view_only)]:
        #     GET /api/report-template/  500 + pydantic 역추적 전문 → **403 + 봉투**
        #   ⚠ 화면 쪽은 안전하다 — `useReportTemplate.ts` 6함수 전부 try/catch/finally.
        ",/api/report-template/"
        ",/api/operational-data/"
        ",/api/handover/handover/"
        ",/api/devices/libraries-management/"
        ",/api/devices/packaging-specifications/"
        ",/api/devices/cameras/").split(",")
    if p.strip()
)

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8080",
    "http://127.0.0.1:8080",
    "https://aim.koca.go.kr",
    "https://aip.caat.or.th",
    "https://localhost:8000",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django_jinja.backend.Jinja2",
        "DIRS": [
            os.path.join(BASE_DIR, "templates", "jinja2"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "match_extension": ".jinja2",  # hoặc .html nếu muốn
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        }
    },
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
APPLICATION_NAME = "guardianx_backend"

# Database
DATABASES = {
    "default": {
        "ENGINE": "dj_db_conn_pool.backends.postgresql",
        "NAME": env("DB_NAME", default="guardianx-v2"),
        "USER": env("DB_USER", default="postgres"),
        # W0-0: 자격증명 기본값 제거 — 미설정 시 즉시 실패시킨다
        "PASSWORD": env("DB_PASSWORD"),
        # W0-10: 사내 주소를 코드 기본값으로 두지 않는다 (.example TLD 는 해석되지 않아 즉시 드러난다)
        "HOST": env("DB_HOST", default="db.internal.example"),
        "PORT": env("DB_PORT", default="5432"),
        "CONN_MAX_AGE": 0,
        "POOL_OPTIONS": {
            "POOL_SIZE": 10,           # Giảm pool size
            "MAX_OVERFLOW": 20,       # Giảm overflow
            "RECYCLE": 1800,           # Recycle sau 5 phút
            "TIMEOUT": 30,            # Giảm timeout
            "PRE_PING": True,
        },
        "OPTIONS": {
            "connect_timeout": 10,
            "application_name": APPLICATION_NAME,
            "client_encoding": "UTF8",
            "options": "-c statement_timeout=30000",
        },
        "ATOMIC_REQUESTS": False,  # Tắt atomic requests
        "AUTOCOMMIT": True,  # Bật autocommit để đảm bảo transaction consistency
        # ── P-18 (정정 · 2026-09-21) 차선마다 **시험 DB 이름을 가른다** ──────────
        # 병렬 차선을 막고 있던 것은 자원이 아니라 **이름 하나**였다 [실측 09-10]:
        # 두 차선이 시험을 동시에 돌리면 둘 다 `test_<DB_NAME>` 을 만들려 해서
        # `DuplicateDatabase` / `ObjectInUse` 로 죽었고, **그 빨강은 코드 결함처럼
        # 보이지만 환경 충돌**이다. 컨테이너를 복제하지 않는다 — 이름만 가른다.
        #     DB_TEST_NAME=test_gx_c  (차선 C) · test_gx_d · test_gx_e · test_gx_v
        # 비우면 Django 기본(`test_` + NAME)이라 지금까지와 **똑같이** 돈다.
        "TEST": {"NAME": env("DB_TEST_NAME", default=None) or None},
    }
}
# SESSION_SERIALIZER = "core.common.security.session_serializer.EncryptedSessionSerializer"
# Database connection management settings
DB_CONNECTION_MANAGEMENT = {
    'AUTO_CLOSE_IDLE': True,           # Auto close idle connections
    'IDLE_TIMEOUT': 300,               # Close connections idle for 5 minutes
    'MAX_CONNECTIONS_PER_APP': 15,     # Max connections per application
    'HEALTH_CHECK_INTERVAL': 180,      # Health check every 5 minutes
    'FORCE_CLOSE_ON_EXCEPTION': True,  # Force close on exceptions
    'LOG_CONNECTION_EVENTS': True,     # Log connection events
}

# Celery database connection settings
CELERY_DB_CONNECTION = {
    'MAX_CONNECTIONS': 5,              # Max connections for Celery
    'CONNECTION_TIMEOUT': 30,          # Connection timeout
    'AUTO_CLOSE': True,                # Auto close after tasks
}

# Check if running management command
def _is_management_command():
    """Check if we're running a Django management command."""
    try:
        argv = sys.argv
        if len(argv) < 2:
            return False
        for arg in argv:
            if 'manage.py' in arg:
                return True
        return False
    except Exception:
        return False

# Determine if db logging should be enabled
# Disable db logging when running management commands to avoid log storms
DB_LOGGING_ENABLED = not _is_management_command()

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'db_handler': {
            # Filter out noisy infra logs (esp. `backend/common/universal_optimization.py`)
            # so they are NOT persisted into AuditLogs via Celery task_add_log.
            'class': 'common.logging.filtered_db_log_handler.FilteredDatabaseLogHandler',
            'level': 'DEBUG',
        },
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'level': 'INFO',
        },
        'null': {
            # Null handler to disable logging when running management commands
            'class': 'logging.NullHandler',
        },
    },
    'loggers': {
        # Logger 'db' - được sử dụng trong middleware để log vào database
        # Disable db_handler when running management commands to prevent task_add_log storms
        'db': {
            'handlers': ['db_handler'] if DB_LOGGING_ENABLED else ['null'],
            'level': 'DEBUG',
            'propagate': False,  # Không propagate để tránh duplicate logs
        },
        # Logger 'console' - để log ra console
        'console': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Logger cho Django - chỉ log console, không log database (quá nhiều logs)
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,  # Không propagate để tránh duplicate
        },
        # Logger cho Django requests - chỉ log console
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        # Logger cho Django server - chỉ log console
        'django.server': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Cache invalidation is extremely chatty; never persist these to DB logs (prevents task_add_log recursion)
        'cache_invalidation': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Redis pool init logs: keep on console only (Celery can call this frequently in worker processes)
        'redis_pool': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Celery redirects stdout/stderr prints into this logger; keep it out of db_handler to prevent log loops
        'celery.redirected': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Logger cho các third-party libraries - chỉ log console
        'urllib3': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'requests': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Các logger khác sẽ tự động propagate lên root logger
        # và được log vào cả console và database
    },
    'root': {
        # Root logger: mặc định CHỈ log ra console để tránh vòng lặp DB handler → task_add_log → log storm.
        # Nếu muốn persist toàn bộ logs vào DB (KHÔNG KHUYẾN NGHỊ ở production), bật env:
        #   DB_LOG_ROOT_ENABLED=True
        'handlers': (['console', 'db_handler'] if env.bool("DB_LOG_ROOT_ENABLED", default=False) else ['console']),
        'level': 'INFO',
    },
}



# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]
NINJA_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=200),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "CHECK_BLACKLIST": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "AUTH_TOKEN_CLASSES": ("ninja_jwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "JTI_CLAIM": "jti",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=200),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=7),
}

# Redis Settings
REDIS_HOST = env("REDIS_HOST", default="redis://localhost:6379")
REDIS_PORT = int(env("REDIS_PORT", default="6379"))
REDIS_DB = int(env("REDIS_DB", default="0"))

# Redis Cache Settings
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"{REDIS_HOST}/{REDIS_DB}",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

# Channels Configuration
ASGI_APPLICATION = "config.asgi.application"
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [f"{REDIS_HOST}/1"],
            "capacity": 1500,  # Giới hạn số message trong channel
            "expiry": 3600,  # Expire messages sau 1 giờ
            "group_expiry": 86400,  # Expire groups sau 24 giờ
            "channel_capacity": {
                "http.request": 100,
                "http.response!*": 100,
                "websocket.send!*": 100,
            },
        },
    },
}

AUTHENTICATION_BACKENDS = (
    "rules.permissions.ObjectPermissionBackend",
    "django.contrib.auth.backends.ModelBackend",
    "guardian.backends.ObjectPermissionBackend",
)

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = env("TIME_ZONE", default="Asia/Ho_Chi_Minh")
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Additional locations of static files
STATICFILES_DIRS = (
    [
        os.path.join(BASE_DIR, "static"),
    ]
    if os.path.exists(os.path.join(BASE_DIR, "static"))
    else []
)

# Static files finders
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

# Media files
MEDIA_URL = "media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# OpenSearch Settings
OPENSEARCH_INDEX = env("OPENSEARCH_INDEX", default="drone_logs")

# MinIO Storage Configuration
# W0-10: 사내 주소를 코드 기본값으로 두지 않는다
MINIO_ENDPOINT = env("MINIO_ENDPOINT", default="minio.internal.example")
# W0-0: 자격증명 기본값 제거 — 미설정 시 즉시 실패시킨다
MINIO_ACCESS_KEY = env("MINIO_ACCESS_KEY")
MINIO_SECRET_KEY = env("MINIO_SECRET_KEY")
MINIO_USE_HTTPS = env.bool("MINIO_USE_HTTPS", default=False)
MINIO_URL_EXPIRY_HOURS = timedelta(hours=24)  # Change to timedelta
MINIO_CONSISTENCY_CHECK_ON_START = True

# Default Storage
DEFAULT_FILE_STORAGE = "django_minio_backend.models.MinioBackend"
MINIO_STORAGE_MEDIA_BUCKET_NAME = env("MINIO_BUCKET_NAME", default="guardianx")
MINIO_BUCKET_CHECK_ON_SAVE = True
MINIO_BUCKET_AUTO_CREATE = True

# Backend URL
BACKEND_URL = env("BACKEND_URL", default="http://localhost:8000")


# MinIO Backend Buckets
MINIO_PRIVATE_BUCKETS = []
MINIO_PUBLIC_BUCKETS = [MINIO_STORAGE_MEDIA_BUCKET_NAME, "lms-media"]

# File Management Settings
FILE_NAME_MAX_LENGTH = 255  # Độ dài tối đa cho tên file


# Thiết lập Comment, Rating, Topic
COMMENT_CACHE_TTL = 300  # 5 minutes
COMMENT_MAX_ALLOWED_IMG = 10
RATING_CACHE_TTL = 300  # 5 minutes
RATING_MAX_ALLOWED_IMG = 5
FEATURED_RATING = 10
TOPIC_CACHE_TTL = 300  # 5 minutes

# Content type mappings
CONTENT_TYPE_MAPPING = {
    "article": "article",
    "topic": "topic",
    "comment": "comment",
}

# Core Settings
CORE_SETTINGS = {
    "API_VERSION": "v1",
    "API_PREFIX": "api",
    "API_DOCS_URL": "docs/",
    "API_OPENAPI_URL": "openapi.json",
    "API_TITLE": "GuardianX API",
    "API_DESCRIPTION": "API documentation for GuardianX",
    "API_AUTH": {
        "JWT": {
            "AUTH_HEADER_TYPES": ("Bearer",),
            "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
            "USER_ID_FIELD": "id",
            "USER_ID_CLAIM": "user_id",
            "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
            "TOKEN_TYPE_CLAIM": "token_type",
            "JTI_CLAIM": "jti",
        }
    },
}


CELERY_BROKER_URL = f"{REDIS_HOST}/{REDIS_DB}"
CELERY_RESULT_BACKEND = f"{REDIS_HOST}/{REDIS_DB}"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE


CELERY_WORKER_CONCURRENCY = 2  # Max 2 concurrent tasks per worker (prevent overload)
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # Only prefetch 1 task at a time
CELERY_TASK_ACKS_LATE = True  # Acknowledge after task completion
CELERY_WORKER_DISABLE_RATE_LIMITS = False  # Enable rate limiting


CELERY_TASK_SOFT_TIME_LIMIT = 300  # 5 minutes soft limit
CELERY_TASK_TIME_LIMIT = 600  # 10 minutes hard limit
CELERY_WORKER_MAX_TASKS_PER_CHILD = 50  # Restart worker after 50 tasks (prevent memory leaks)
CELERY_WORKER_MAX_MEMORY_PER_CHILD = 200000  # 200MB memory limit per worker


CELERY_TASK_REJECT_ON_WORKER_LOST = True  # Reject tasks if worker crashes
CELERY_TASK_DEFAULT_RETRY_DELAY = 60  # 1 minute between retries
CELERY_TASK_MAX_RETRIES = 3  # Maximum 3 retries


CELERY_SEND_TASK_EVENTS = True  # Enable task monitoring
CELERY_WORKER_SEND_TASK_EVENTS = True
CELERY_TASK_TRACK_STARTED = True  # Track when tasks start
CELERY_TASK_PUBLISH_RETRY = True  # Retry publishing failed tasks


CELERY_TASK_ROUTES = {
    # 🔧 FIX: Route optimization tasks to default queue
    # 'optimization.tasks.*': {'queue': 'default'},
    # Default queue for urgent tasks
    'celery.*': {'queue': 'celery'},
}

# Explicitly include operational data tasks
CELERY_IMPORTS = [
    'operational_data.tasks',
    'partner.tasks',
]

# 📋 QUEUE PRIORITIES & LIMITS
CELERY_TASK_PRIORITY_STEPS = list(range(10))  # Priority levels 0-9
CELERY_ACKS_LATE = True  # Safer task acknowledgment
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'priority_steps': list(range(10)),
    'visibility_timeout': 3600,  # 1 hour visibility timeout
    'fanout_prefix': True,
    'fanout_patterns': True,
}


CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# ─────────────────────────────────────────────────────────────────────────────
# 운영 자동화 (D-373) — **감시는 켜고, 백업은 끈 채로 둔다**
# ─────────────────────────────────────────────────────────────────────────────
# 백업을 기본으로 켜지 않는 이유는 겁이 나서가 아니다. 백업은 **어디에 얼마나 오래
# 쌓을 것인가**를 정해야 도는 일이고, 그 답은 고객 환경마다 다르다. 기본값으로 켜면
# 우리가 남의 디스크에 대해 그 답을 정하는 것이 된다.
# 켤 때는 둘을 **함께** 준다 — 보관처 없이 켜면 태스크가 판정 불가로 멈춘다.
OPS_BACKUP_SCHEDULE_ENABLED = env.bool("OPS_BACKUP_SCHEDULE_ENABLED", default=False)
OPS_BACKUP_DIR = env.str("OPS_BACKUP_DIR", default="")
#: ★ OPS-07b — 감사 로그 파기의 **되돌림 저널**도 이 칸 아래에 산다
#:   (`<OPS_BACKUP_DIR>/audit_purge_journal/`). **설정 이름을 하나 더 만들지
#:   않았다** — 아무도 안 채우는 이름은 아무도 안 켠 스위치이고(D-377 착시 ⑨),
#:   저널의 자리는 백업과 갈라질 이유가 없다. 이 칸이 비면 파기는 **돌지
#:   않는다** — 되돌릴 수 없는 파기는 하지 않는다. 규약:
#:   `backend/common/audit_purge_journal.py`.
CELERY_BEAT_SYNC_EVERY = 30  # Sync every 30 seconds (reduced load)
CELERY_BEAT_MAX_LOOP_INTERVAL = 300  # Max 5 minutes between checks

from celery.schedules import crontab





# Email Settings
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = env("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = int(env("EMAIL_PORT", default="587"))
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="your-email@gmail.com")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="your-app-password")
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="your-email@gmail.com")

# ─────────────────────────────────────────────────────────────────────────────
# K2 경보 이메일 — OPS-10 「발송까지」 (2026-09-24 · 차선 E)
# ─────────────────────────────────────────────────────────────────────────────
# [실측 2026-09-24] 개발 DB 의 알림 규칙 4건은 **전부 채널이 `log`** 다. `log` 는
# 사람이 아니라 로그에 도달한다(`kernels/k2_notify/channels.py::LogChannel`) — 즉
# **사람에게 도달하는 경보가 0건**이다. 그리고 `info`·`warning` 등급에는 규칙이
# 아예 0건이다. 배선은 살아 있고, 켜져 있지 않았다.
#
# ★ 이 블록이 하는 일은 **주소 하나만 넣으면 나가는 상태**를 만드는 것이다.
#   수신 주소는 저장소에 오지 않는다(대표가 로컬 `.env` 로 준다 · D-204).
#
# ⚠ **위 EMAIL_* 의 기본값은 자리 표시자다** (`your-email@gmail.com` ·
#   `your-app-password`). 그 값으로 SMTP 는 서지 않는다. 그런데 `getattr` 로 읽으면
#   **값이 있다**로 보인다 — 「설정했다」와 「자리 표시자가 남아 있다」가 같아진다(D-290).
#   그래서 자리 표시자의 목록을 **이름으로** 둔다. 판정기·어댑터가 이 목록을 읽고
#   「SMTP 미설정」을 **회색**으로 말한다. 회색은 초록이 아니다.
EMAIL_PLACEHOLDER_VALUES = (
    "your-email@gmail.com",
    "your-app-password",
    "CHANGE_ME",
    "",
)

#: 규칙이 기본으로 고를 채널. `log` 로 두면 **사람에게 도달하지 않는다** — 그 사실은
#: 발송 이력의 `channel` 칸에 그대로 남는다. 운영에서는 `email` 로 준다.
#: 값을 바꾸는 것만으로 규칙이 바뀌지는 않는다 — `manage.py seed_alert_routing` 이
#: 이 값을 읽어 규칙을 **다시 세운다**. 설정은 의도이고, 규칙이 사실이다.
K2_ALERT_CHANNEL = env.str("K2_ALERT_CHANNEL", default="log")

#: 경보를 받을 **사람의 주소**. 대표가 줄 값이고, 저장소에는 **이름만** 있다.
#: 비어 있으면 `seed_alert_routing --channel email` 은 **심지 않고 멈춘다** —
#: 주소 없이 규칙만 email 로 바꾸면 발송 이력이 전부 실패 행이 되고, 그것은
#: 배선의 사실이 아니라 환경의 사실이다(P-20 ①과 같은 판정).
K2_ALERT_EMAIL_TO = env.list("K2_ALERT_EMAIL_TO", default=[])

#: 도달할 수 없는 주소의 도메인. RFC 2606 이 「절대 존재하지 않는다」고 못 박은 TLD 다.
#: 시드 사람의 주소가 여기에 있다 — **주소가 있다**와 **사람이 받는다**를 가르는 칸이다.
UNDELIVERABLE_EMAIL_SUFFIXES = (".invalid",)

#: 실발송을 **허용하는 도메인** (P-41 · 2026-09-05). 여기 **없는** 도메인은 규칙의
#: 채널이 `email` 이어도 `EmailChannel` 이 **로그 어댑터로 떨어뜨린다** — 보내고 나서
#: 세는 것은 늦다.
#:
#: ⚠ **비어 있으면 아무 도메인도 실발송하지 않는다**(전부 로그). 「목록을 잊었다」가
#:   「전부 허용」이 되면 첫 발송이 곧 사고다 — [실측 2026-09-05 · 턴 B] 규칙이 고르는
#:   수신자 42명 중 **개발 계정이 30명**(yopmail.com 24 · seed.invalid 6)이다.
#:
#: ⚠ **차단 목록이 아니라 허용 목록이다.** 막을 것을 세는 방식은 내일 생길 43번째
#:   개발 계정을 자동으로 통과시킨다. 강제: `scripts/verify_send_allowlist.py`.
#:
#: ★ 대조는 **정확히 같은 도메인**이다. `org.kr` 을 적어도 `city.org.kr` 은 안 나간다 —
#:   꼬리 일치는 `notyopmail.com` 이 `yopmail.com` 을 통과하는 고전적 구멍을 만든다.
#:   보낼 도메인은 **하나씩 적는다.**
K2_SEND_ALLOWED_DOMAINS = env.list("K2_SEND_ALLOWED_DOMAINS", default=[])

#: 운영 경보(`ops_monitor --check` 의 exit 1)를 받을 역할 코드. **U5 시스템관리자만**
#: (P-41). 당직 관제요원에게 디스크 사용률을 보내면 그 사람은 할 수 있는 일이 없고,
#: 다음부터 경보를 안 읽는다. 재난 알림(K2)은 이 값이 아니라 **등급 규칙**이 고른다.
#: 「U5 시스템관리자」의 코드는 `config/k3_roles.K3_ROLE_SYSOPS` 한 곳이 답한다 —
#: 여기 목록을 손으로 베끼면 두 벌이 되고, 두 벌은 반드시 어긋난다 (D-369).
K2_OPS_ALERT_ROLE_CODES = env.list("K2_OPS_ALERT_ROLE_CODES", default=[])

ALLOWED_IMG_EXTENSIONS = [
    ".jpg",
    ".jpeg",
    ".png",
    ".gif",
    ".bmp",
    ".tiff",
    ".ico",
    ".webp",
]
# Django Ninja settings
NINJA_PAGINATION_CLASS = "ninja.pagination.PageNumberPagination"
NINJA_PAGINATION_PER_PAGE = 10
NINJA_PAGINATION_MAX_LIMIT = 100
NINJA_NUM_PROXIES = 0
NINJA_DEFAULT_THROTTLE_RATES = {
    "user": "10/minute",
    "anon": "5/minute",
}

# Third-party API Settings
# Anyang Integration Settings
ANYANG_SERVICE_KEY = env("ANYANG_SERVICE_KEY", default="")

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True  # Cho phép tất cả các origin trong môi trường phát triển


CORS_ALLOW_CREDENTIALS = True

#: ★ [실측 2026-09-05 TC · 차선 Q · `scripts/walk_scenarios.py` 가 잡았다]
#:   **이벤트 스냅샷이 브라우저에서 한 장도 안 뜬다.** 화면에는
#:   「스냅샷을 받지 못했습니다 / Network Error」만 남고, 콘솔은 이렇게 말한다:
#:       Access to XMLHttpRequest at '…/api/dsm/events/4803/snapshot'
#:       has been blocked by CORS policy: Request header field **x-no-cache**
#:       is not allowed by Access-Control-Allow-Headers in preflight response
#:   그런데 **같은 주소를 토큰으로 직접 부르면 200 JPEG 이 온다** [실측].
#:   즉 서버도 이미지도 멀쩡하고, 막힌 것은 **프리플라이트**다.
#:
#:   왜 이 헤더를 보내나 — 일부러다. `frontend/src/features/dsm/components/
#:   EventSnapshot.tsx` 는 캐시된 바이트가 남의 이벤트 사진이 되지 않게
#:   `X-No-Cache: true` 로 부른다(D-341 착시 ⑦). 서버도 그 헤더를 읽는다
#:   (`common/universal_optimization.py`). **읽는 쪽과 보내는 쪽은 맞는데
#:   브라우저가 그 사이를 막고 있었다** — 세 자리가 다 옳아 보여서 아무도 안 봤다.
#:
#:   ⚠ `django-cors-headers` 의 기본 허용 헤더 목록에는 이 이름이 없다. 기본값을
#:     **덮지 않고 더한다** — 덮으면 authorization·content-type 이 함께 사라진다.
from corsheaders.defaults import default_headers as _cors_default_headers

#: ★ [실측 2026-09-06 · P-74 · 차선 C] **두 번째로 같은 자리에 걸렸다.**
#:
#:   월 표시 토큰(UX-24a)은 서버 면이 완전히 서 있었다 — 서명·수명·회수·쓰기 0 을
#:   탐침이 전부 재서 초록이었다. 그런데 그 탐침은 **서버에서 서버로** 부른 것이었고,
#:   브라우저를 처음 붙인 이번 턴에 화면이 이렇게 나왔다:
#:
#:       월 화면은 뜬다 · 「월 표시 토큰으로 열림」도 뜬다 ·
#:       그런데 **우리 API 로 나간 요청이 0건이다** (실측 · 기록된 우리 호출 1건)
#:
#:   막힌 자리는 서버도 화면도 아니라 **프리플라이트**였다. 커스텀 헤더는 CORS
#:   허용 목록에 이름이 있어야 브라우저가 보낸다. 위 `x-no-cache` 와 **똑같은 모양**이고,
#:   그 주석이 「세 자리가 다 옳아 보여서 아무도 안 봤다」고 적어 둔 그 자리다.
#:
#:   ★ 이름을 손으로 적지 않는다 — `common.wall_token.WALL_TOKEN_HEADER` 한 곳에서
#:     읽는다. 두 벌로 적으면 헤더 이름이 바뀌는 날 한쪽만 바뀌고, 그때 증상은
#:     **똑같이 「요청 0건」**이다(원인은 안 보이고 결과만 같다).
try:
    from common.wall_token import WALL_TOKEN_HEADER as _WALL_TOKEN_HEADER
except Exception:                                   # noqa: BLE001
    # settings 를 세우는 도중이라 앱 모듈을 못 읽을 수 있다. 그때는 이름을 적되
    # **못 읽었다는 사실이 이 갈래 자체로 남는다** — 조용히 비우지 않는다.
    _WALL_TOKEN_HEADER = "X-GX-Wall-Token"

#: ★ [P-78 ③ · 2026-09-06 · 차선 C] **세 번째로 같은 자리다.**
#:
#:   판정·접수·회신 세 문에 멱등 키(`Idempotency-Key`)를 싣기로 했다. 그 이름이
#:   이 목록에 없으면 브라우저는 프리플라이트에서 막고 **요청 자체를 안 보낸다** —
#:   증상은 「단추를 눌렀는데 아무 일도 안 일어난다」이고, 콘솔에도 서버에도
#:   원인이 안 남는다. 위 두 주석(`x-no-cache` · 월 표시 토큰)이 적어 둔 함정이
#:   그대로다.
#:
#:   ★ [P-87 · 2026-09-06 턴 I · 차선 C] **이제 서버가 이 이름을 읽는다.**
#:     위 문단은 턴 H 까지 「서버는 아직 이 이름을 읽지 않는다」였고 그것이 참이었다.
#:     `common/idempotency.py` 의 `@idempotent` 가 **판정·접수·회신·발송** 네 문에
#:     붙었다 — 창 안의 같은 (사람·문·키) 는 손을 대지 않고 그때 준 답을 받는다.
#:     허용 목록에 이름이 있다는 것과 그 규약이 산다는 것은 다른 사실이고,
#:     지금은 **둘 다** 참이다.
CORS_ALLOW_HEADERS = list(_cors_default_headers) + [
    "x-no-cache",
    _WALL_TOKEN_HEADER.lower(),
    "idempotency-key",
]

CORS_EXPOSE_HEADERS = [
    "X-New-Token",
    "Token-Refreshed",
    "X-Token-Status",
    "Content-Disposition",
    "Content-Length",
    "X-Force-Password-Change"
]


# W0-10: 스트림·AI 엔드포인트도 사내 주소를 코드 기본값으로 두지 않는다
STREAM_URL = env("STREAM_URL", default="http://streaming.internal.example")

# GCS API Configuration
GCS_APIKEY = env("GCS_APIKEY", default="")
FLIGHTBRID_URL = env("FLIGHTBRID_URL", default="http://localhost:8009")
CAPTURE_URL = f"{STREAM_URL}/stream/api/streams/capture"
RECORD_URL = f"{STREAM_URL}/stream/api/streams/record"
RTSP_URL = env("RTSP_URL", default="rtsp://rtsp.internal.example:8554")
RTSP_PATH = f"{RTSP_URL}/stream"
RTSP_PATH_AI = f"{RTSP_URL}/stream"

AI_ANALYSIS_URL = env("AI_ANALYSIS_URL", default="https://ai-analysis.internal.example")
AI_RTSP_PATH = env("AI_RTSP_PATH", default="https://ai.internal.example/api/process_stream")
AI_GRPC_URL = env("AI_GRPC_URL", default="https://media-ai.internal.example")


# Environment
GUARDIANX_ENVIRONMENT = env("GUARDIANX_ENVIRONMENT", default="development")

IS_USE_WEBRTC = env("IS_USE_WEBRTC", default=True)

IMG_DIR = env("IMG_DIR", default=os.path.join(BASE_DIR, "stream_monitors", "media", "images"))

RECORD_DIR = env("RECORD_DIR", default=os.path.join(BASE_DIR, "stream_monitors", "media", "record"))
REDIS_RECORDING_STATUS_KEY = env("REDIS_RECORDING_STATUS_KEY", default="recording_status")


# ─────────────────────────────────────────────────────────────────────────────
# 테넌트 스코프 강제 (W0-14)
# ─────────────────────────────────────────────────────────────────────────────
# False = 경고 모드. 차단하지 않고 "차단됐을 요청"을 logger.warning 으로만 남긴다.
# True  = 차단 모드. group 이 없는 요청을 NoTenantGroupError 로 끊는다.
#
# 착수 시점 커버리지가 0/466 이라 기본값은 False 다. 미분류 라우트가 0 에
# 수렴한 뒤 이 값 하나로 차단으로 넘어간다 — 코드 되돌림 없이 되돌릴 수 있는
# 유일한 지점이므로, 스코프 판정을 코드 여러 곳에 흩지 말 것 (D-212).
TENANT_SCOPE_ENFORCE = env.bool("TENANT_SCOPE_ENFORCE", default=False)


# ─────────────────────────────────────────────────────────────────────────────
# 전역 관리 역할 정의 (W0-16 · D-243 · D-247)
# ─────────────────────────────────────────────────────────────────────────────
# "누가 전역 superuser 인가"를 **여기 한 곳에서만** 정의한다 (D-212).
# W0-14 의 뷰 레벨 스코프가 이 정의를 그대로 읽어 판정한다 — 판정식을 코드
# 여러 곳에 흩지 말 것. 흩는 순간 우회 지점이 그 수만큼 늘어난다.
#
# 배경(실측 · evidence/W0-16/superuser_accounts.md): 레거시 `superuser` **역할**을
# 13계정이 갖고 있고 그중 7계정이 **고객 테넌트(Anyang) 안**에 있다. 그 역할은
# dj-core 의 ORM 필터(core/base.py:308)와 권한 검사(core/role/permission.py:475)를
# 통째로 통과시킨다 — 둘 다 §0.4 라 고칠 수 없다. 그래서 **역할을 갈라낸다.**

# 전역(GAION 운영) 역할 코드. 이 역할만 테넌트 경계를 넘을 수 있다.
TENANT_GLOBAL_ADMIN_ROLE_CODES = env.list(
    "TENANT_GLOBAL_ADMIN_ROLE_CODES", default=["gaion_global_admin"]
)

# 레거시 `superuser` 역할을 전역으로 계속 인정할 것인가 (무중단 전환용 · D-243 ②).
# True  = 지금까지와 동일 동작. 대체역할 부여가 끝나기 전 단계의 기본값.
# False = `superuser` 역할은 더 이상 전역이 아니다 — 테넌트 스코프가 적용된다.
# 회수 순서: 대체역할 부여 → 이 값을 False → 검증 → 역할 회수 (evidence/W0-16/revocation_runbook.md)
TENANT_TRUST_LEGACY_SUPERUSER = env.bool("TENANT_TRUST_LEGACY_SUPERUSER", default=True)

# 테넌트 운영 역할(자기 테넌트 관리)의 코드 접두어. `<prefix>_<group_id>` 규약.
TENANT_ADMIN_ROLE_PREFIX = env.str("TENANT_ADMIN_ROLE_PREFIX", default="tenant_admin")


# ─────────────────────────────────────────────────────────────────────────────
# K3 역할별 대시보드 프레임의 배선 (D-371 ① · P-K3-1 해소)
# ─────────────────────────────────────────────────────────────────────────────
# 커널(`kernels/k3_dashboard/presets.py`)은 매핑을 코드에 박지 않고 **여기서 읽는다**
# — 실측되지 않은 매핑을 박지 않기 위해서다(D-280). 그 설정이 여태 없었고, 그래서
# 프레임은 서 있는데 **모든 사람이 같은 화면**을 봤다.
#
# 근거·판정·비운 것의 목록은 전부 `config/k3_roles.py` 에 있다. 여기서 값을 다시
# 적지 않는다 — 두 벌은 반드시 어긋난다(D-369).
from config.k3_roles import (  # noqa: E402
    K3_ROLE_PRESET_MAP,
    K3_UNMAPPED_BY_DECISION,
    K3_WIDGET_MATRIX,
)


# ─────────────────────────────────────────────────────────────────────────────
# 외부 의존 저하 운전 (W0-17 · D-212)
# ─────────────────────────────────────────────────────────────────────────────
# 타임아웃 값을 **여기 한 곳에서만** 정한다. 호출부에 숫자를 흩지 말 것 —
# 흩어진 5초·30초가 실제로 몇 초인지 아무도 모르게 되는 것이 지금 상태다.
#
# 배경(실측 · evidence/W0-17/timeout_inventory.md): requests 호출 75건 중 17건에
# 타임아웃이 없다. 하나가 늦으면 워커가 잡히고, 잡힌 워커가 쌓이면 서비스가 선다.
# 실제로 목록 API 는 스트리밍 서버가 없으면 **통째로 HTTP 500** 이었다.

# (연결, 응답) 초. 연결은 짧게 — 죽은 호스트는 빨리 포기하는 것이 옳다.
EXTERNAL_HTTP_TIMEOUT = (
    env.float("EXTERNAL_HTTP_CONNECT_TIMEOUT", default=3.0),
    env.float("EXTERNAL_HTTP_READ_TIMEOUT", default=5.0),
)

# 업로드·다운로드처럼 본래 오래 걸리는 호출용. 그래도 무한은 아니다.
EXTERNAL_HTTP_TIMEOUT_LONG = (
    env.float("EXTERNAL_HTTP_CONNECT_TIMEOUT", default=3.0),
    env.float("EXTERNAL_HTTP_LONG_READ_TIMEOUT", default=60.0),
)


# ─────────────────────────────────────────────────────────────────────────────
# UX-19 나가는 웹훅 — CAP 1.2 (2026-09-05 TC · 차선 S)
# ─────────────────────────────────────────────────────────────────────────────
# ★ **서명키 값은 저장소에 없다** (D-204). 여기 있는 것은 **이름 → 값**의 표이고,
#   값은 환경에서만 온다. 환경에 없으면 표가 비고, 표가 비면 그 이름의 구독은
#   **등록 단계에서 거절**된다 — 「등록은 됐는데 보낼 수 없는 구독」을 만들지 않는다.
#
#   넣는 모양(환경변수 하나 · 쉼표로 여럿):
#       WEBHOOK_SIGNING_KEYS="sdn=<값>,agency=<값>"
#
#   ⚠ 이 값을 `.env.example` 이나 저장소 어디에도 적지 말 것. 웹훅 서명키가 새면
#     **누구나 우리 이름으로 경보를 낼 수 있다** — 그것이 SEC-16 이 존재하는 이유다.
def _parse_webhook_signing_keys(raw: str) -> dict:
    table = {}
    for chunk in (raw or "").split(","):
        name, sep, value = chunk.partition("=")
        if sep and name.strip() and value.strip():
            table[name.strip()] = value.strip()
    return table


WEBHOOK_SIGNING_KEYS = _parse_webhook_signing_keys(
    os.environ.get("WEBHOOK_SIGNING_KEYS", ""))

# 등록을 받아 주는 수신 URL 의 방식. **평문 http 는 기본으로 열지 않는다** —
# 서명은 위조를 막지만 평문은 내용을 읽히는 것을 막지 못하고, CAP 본문에는
# 위치와 시각이 들어 있다. 개발 환경에서만 `WEBHOOK_ALLOWED_SCHEMES=https,http`.
WEBHOOK_ALLOWED_SCHEMES = tuple(
    s.strip() for s in os.environ.get("WEBHOOK_ALLOWED_SCHEMES", "https").split(",")
    if s.strip()
)

# CAP `<sender>` — 받는 쪽이 「누가 보냈나」로 읽는 값. **공백·쉼표를 넣을 수 없다**
# (CAP 1.2 가 금지한다 · `common/cap_1_2.py` 가 거절한다).
CAP_SENDER = os.environ.get("CAP_SENDER", "guardianx.local")
CAP_SENDER_NAME = os.environ.get("CAP_SENDER_NAME", "GuardianX 관제")


# ─────────────────────────────────────────────────────────────────────────────
# P-67 — **보존 일수·백업의 기본값은 없다. 선언만 있다** (2026-09-06 · 차선 E)
# ─────────────────────────────────────────────────────────────────────────────
#
# ★ 위 `OPS_BACKUP_SCHEDULE_ENABLED`/`OPS_BACKUP_DIR` 두 줄이 「끈 채로 · 빈 채로」
#   서 있던 자리다. 그것은 기본값이 아니라 **미선언**이었고, 그래서 백업이
#   한 번도 저장된 적이 없었다(OPS-19). 고치는 방법은 코드에 수를 적는 것이
#   아니라 **선언한 사람과 환경을 적는 것**이다.
#
# ★ 순서가 곧 내용이다 (지시서 §4 함정 ①): 시드가 **먼저** 서고, 그 다음에
#   `apps/dsm/retention.py` 의 코드 기본값이 사라진다. 거꾸로 하면 그 사이
#   개발 환경의 파기·백업이 조용히 멈춘다.
#
# ★ 환경변수가 언제나 이긴다 — `os.environ` 에 그 이름이 있으면 시드는 비켜선다.
#   그래서 「이미 선언된 이름」을 `settings` 가 아니라 **환경**에서 읽는다:
#   위에서 `env.bool(..., default=False)` 로 읽은 False 는 「거짓으로 선언했다」와
#   「아무도 안 정했다」를 구별하지 못한다(D-290).
from config.retention_seed import declarations as _retention_declarations  # noqa: E402

_RETENTION_DECLARED = _retention_declarations(
    GUARDIANX_ENVIRONMENT,
    [name for name in ("AUDIT_LOG_RETENTION_DAYS", "VIDEO_RETENTION_DAYS",
                       "OPS_BACKUP_SCHEDULE_ENABLED", "OPS_BACKUP_DIR",
                       "OPS_BACKUP_VOLUME", "OPS_BACKUP_RETENTION_DAYS",
                       "OPS_RESTORE_DRILL_ENABLED")
     if os.environ.get(name) not in (None, "")],
)
for _name, _value in _RETENTION_DECLARED.items():
    globals()[_name] = _value

#: 이 환경이 **무엇을 선언했는지** 그대로 남긴다. 판정기·화면(U5 미선언 배지)이
#: 「누가 정했는가」를 되짚는 자리다 — 값만 보이면 다음 사람이 출처를 못 찾는다.
RETENTION_DECLARATION_SOURCE = (
    "개발·스테이징 선언 (세종 P-67 · config/retention_seed.py)"
    if _RETENTION_DECLARED else
    "선언 없음 — 고객이 U5 설정 화면에서 선언한다"
)
