"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import sys
from pathlib import Path
from datetime import timedelta
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
print("BASE_DIR", BASE_DIR)
# Initialize environ
env = environ.Env()
# Đọc file .env từ thư mục BASE_DIR
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY", default="your-secret-key-here")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DJANGO_DEBUG", default=True)

# ALLOWED_HOSTS = env.list('DJANGO_ALLOWED_HOSTS', default=['*', 'host.internal.example'])
ALLOWED_HOSTS = ["*"]

# CSRF Trusted Origins
# W0-10: 배포처 주소는 코드 기본값이 아니라 환경변수로만 들어온다.
#        기본값은 로컬 개발 2개뿐이다 — 미설정 시 사내 주소로 조용히 붙지 않는다.
#        배포 origin 목록은 backend/.env.example 의 DJANGO_CSRF_TRUSTED_ORIGINS 참조.
CSRF_TRUSTED_ORIGINS = env.list(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    default=["http://localhost:8000", "http://127.0.0.1:8000"],
)
# CSRF_COOKIE_SAMESITE = 'Lax'  # Thay đổi về Lax để tương thích tốt hơn với cross-site
# CSRF_COOKIE_SECURE = (not DEBUG)  # Bật trong production
# SESSION_COOKIE_SAMESITE = 'Lax'  # Thay đổi về Lax để tương thích tốt hơn với cross-site
# SESSION_COOKIE_SECURE = (not DEBUG)  # Bật trong production
# Custom user model - phải định nghĩa trước INSTALLED_APPS
AUTH_USER_MODEL = "user.CoreUser"

# Application definition
INSTALLED_APPS = [
    # Core apps - phải đặt trước django.contrib.auth
    # Django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps
    "corsheaders",
    "ninja_extra",
    "simple_history",
    "guardian",
    "ninja_jwt",
    "ninja_jwt.token_blacklist",
    "safedelete",
    "rules",
    "django_ratelimit",
    "channels",
    "django_celery_beat",
    # Core apps
    "core",
    "core.user",
    "core.tag",
    "core.article",
    "core.discuss",
    "core.notifications",
    "core.file_management",
    "core.configuration",
    "core.logger",
    "core.menu",
    "core.role",
    "core.advanced_table",
    "core.multilanguage",
    "core.apikey_account",
    # 'geolocation',
    "terminals",
    # guardianx
    "common",  # 🚀 Core optimizations app
    "optimization",  # 🔢 Background processing optimizations
    "devices",
    "drone_communication",
    "delivery",
    "orders",
    # 'waybill',
    "print_format",
    "operation_settings",
    "dashboard",
    "report_template",
    "third_api",  # Third party integration APIs
    "stream_monitors",
    "checklist_setting",
    "operational_data",
    "partner",
    "flight_log",
    "surveillance",
    "proxy",  # Proxy for external content
    "handover",  # Handover Management APIs
    "task_status",  # Task status tracking for socket workflows
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    'core.middleware.superuser_must_change_pass.EnforceSuperuserPasswordChangeMiddleware',
    "django.middleware.common.CommonMiddleware",
    "django.middleware.gzip.GZipMiddleware",  # 🚀 PERFORMANCE: Compress responses to reduce network transfer time
    "core.middleware.csrf_exempt_swagger.CSRFExemptSwaggerMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "core.middleware.jwt_user_restore.JWTUserRestoreMiddleware",  # 🔧 FIX: Restore user sau khi AuthenticationMiddleware reset
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "proxy.middleware.RemoveXFrameOptionsMiddleware",  # Remove X-Frame-Options for proxy endpoints
    "core.middleware.refresh_token.TokenRefreshMiddleware",
    # ★ 전역 접근 관문 (D-348 · D-343 ③). **캐시보다 바깥이어야 한다**(D-341 착시 ⑦) —
    #   캐시 안쪽에 두면 열려 있던 동안 익명으로 채워진 항목이 관문을 지나지 않고 그대로 나간다.
    #   §0.4 금지구역의 라우트도 이 한 겹이 덮는다. 파일은 한 줄도 건드리지 않는다.
    "common.access_gate.AccessGateMiddleware",
    # ★ 반드시 UniversalCacheMiddleware **바로 위** (W0-18 · D-248). 두 조건이 있다:
    #   ① 캐시보다 바깥 — UniversalCacheMiddleware 는 캐시 적중 시 저장된 본문을
    #      **항상 JsonResponse(200)** 으로 다시 만든다(universal_optimization.py:872).
    #      캐시 안쪽에 두면 적중한 요청에서 승격이 통째로 사라진다.
    #   ② GZipMiddleware 보다 안쪽 — 압축되기 전 본문을 봐야 JSON 을 읽을 수 있다.
    #   API_CONTRACT_PROMOTE_ERROR_STATUS 가 False 면 아무것도 바꾸지 않는다.
    "common.api_contract.ApiContractStatusMiddleware",
    "common.universal_optimization.UniversalCacheMiddleware",  # 🌍 UNIVERSAL: System-wide optimization cho ALL models & views
    "ninja.compatibility.files.fix_request_files_middleware",
    "core.middleware.dependency_check.DependencyCheckMiddleware",
    'core.middleware.connection_management.DatabaseConnectionMiddleware',  # Database connection management
    "partner.middleware.PartnerAuthMiddleware",  # Disabled: Partner auth handled in CustomJWTAuth
    'core.logger.middleware.CoreLoggingMiddleware',

    # 'core.middleware.remove_group_field.GroupFeatureMiddleware',
]

# ── 응답 계약 (W0-18 · D-248 · D-212) ────────────────────────────────────────
# 권한거부를 HTTP 200 + 본문 403 이 아니라 **실제 HTTP 403** 으로 내보낼 것인가.
#
#   False (기본)  기존 동작 그대로. 미들웨어는 경로에 있으나 통과만 한다.
#   True          `{"success": false, …, "status_code": 4xx}` 를 실제 상태로 승격.
#
# 되돌리기는 이 한 줄이다. 켜기 전에 반드시 읽을 것:
#   docs/agent/evidence/W0-18/backward_compat_impact.md
#     §2-2  승격 시 무증상 실패 후보 21곳 (프론트 · 대부분 delivery 화면)
#     §5    단계적 롤아웃 순서와 되돌림 기준
API_CONTRACT_PROMOTE_ERROR_STATUS = (
    os.environ.get("API_CONTRACT_PROMOTE_ERROR_STATUS", "false").lower() == "true"
)

# ★ D-349 착시 ⑧ — 봉투. **F-05 진입면은 래칫에서 제외한다.**
#
#   전역 승격은 무증상 실패 후보 21곳(대부분 delivery 화면)을 건드린다 — 그래서 위 플래그는
#   아직 꺼져 있다. 그러나 **계약 상대가 읽는 면은 다르다**:
#   에스비 App 이 HTTP 200 을 보고 실패를 성공으로 읽으면 그건 계약 사고다.
#   게이트웨이·모니터링·재시도 로직이 전부 속고, **우리 판정기가 첫 피해자였다**(18 → 11).
#
#   그래서 승격을 **경로로 좁혀** 먼저 건다. 전역 플래그가 꺼져 있어도 이 경로들은 승격된다.
#   되돌리기는 이 목록을 비우는 것이다.
API_CONTRACT_PROMOTE_PATHS = tuple(
    p for p in os.environ.get("API_CONTRACT_PROMOTE_PATHS", "/api/dsm/").split(",") if p.strip()
)

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8080",
    "http://127.0.0.1:8080",
    "https://aim.koca.go.kr",
    "https://aip.caat.or.th",
    "https://localhost:8000",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django_jinja.backend.Jinja2",
        "DIRS": [
            os.path.join(BASE_DIR, "templates", "jinja2"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "match_extension": ".jinja2",  # hoặc .html nếu muốn
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        }
    },
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
APPLICATION_NAME = "guardianx_backend"

# Database
DATABASES = {
    "default": {
        "ENGINE": "dj_db_conn_pool.backends.postgresql",
        "NAME": env("DB_NAME", default="guardianx-v2"),
        "USER": env("DB_USER", default="postgres"),
        # W0-0: 자격증명 기본값 제거 — 미설정 시 즉시 실패시킨다
        "PASSWORD": env("DB_PASSWORD"),
        # W0-10: 사내 주소를 코드 기본값으로 두지 않는다 (.example TLD 는 해석되지 않아 즉시 드러난다)
        "HOST": env("DB_HOST", default="db.internal.example"),
        "PORT": env("DB_PORT", default="5432"),
        "CONN_MAX_AGE": 0,
        "POOL_OPTIONS": {
            "POOL_SIZE": 10,           # Giảm pool size
            "MAX_OVERFLOW": 20,       # Giảm overflow
            "RECYCLE": 1800,           # Recycle sau 5 phút
            "TIMEOUT": 30,            # Giảm timeout
            "PRE_PING": True,
        },
        "OPTIONS": {
            "connect_timeout": 10,
            "application_name": APPLICATION_NAME,
            "client_encoding": "UTF8",
            "options": "-c statement_timeout=30000",
        },
        "ATOMIC_REQUESTS": False,  # Tắt atomic requests
        "AUTOCOMMIT": True  # Bật autocommit để đảm bảo transaction consistency
    }
}
# SESSION_SERIALIZER = "core.common.security.session_serializer.EncryptedSessionSerializer"
# Database connection management settings
DB_CONNECTION_MANAGEMENT = {
    'AUTO_CLOSE_IDLE': True,           # Auto close idle connections
    'IDLE_TIMEOUT': 300,               # Close connections idle for 5 minutes
    'MAX_CONNECTIONS_PER_APP': 15,     # Max connections per application
    'HEALTH_CHECK_INTERVAL': 180,      # Health check every 5 minutes
    'FORCE_CLOSE_ON_EXCEPTION': True,  # Force close on exceptions
    'LOG_CONNECTION_EVENTS': True,     # Log connection events
}

# Celery database connection settings
CELERY_DB_CONNECTION = {
    'MAX_CONNECTIONS': 5,              # Max connections for Celery
    'CONNECTION_TIMEOUT': 30,          # Connection timeout
    'AUTO_CLOSE': True,                # Auto close after tasks
}

# Check if running management command
def _is_management_command():
    """Check if we're running a Django management command."""
    try:
        argv = sys.argv
        if len(argv) < 2:
            return False
        for arg in argv:
            if 'manage.py' in arg:
                return True
        return False
    except Exception:
        return False

# Determine if db logging should be enabled
# Disable db logging when running management commands to avoid log storms
DB_LOGGING_ENABLED = not _is_management_command()

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'db_handler': {
            # Filter out noisy infra logs (esp. `backend/common/universal_optimization.py`)
            # so they are NOT persisted into AuditLogs via Celery task_add_log.
            'class': 'common.logging.filtered_db_log_handler.FilteredDatabaseLogHandler',
            'level': 'DEBUG',
        },
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'level': 'INFO',
        },
        'null': {
            # Null handler to disable logging when running management commands
            'class': 'logging.NullHandler',
        },
    },
    'loggers': {
        # Logger 'db' - được sử dụng trong middleware để log vào database
        # Disable db_handler when running management commands to prevent task_add_log storms
        'db': {
            'handlers': ['db_handler'] if DB_LOGGING_ENABLED else ['null'],
            'level': 'DEBUG',
            'propagate': False,  # Không propagate để tránh duplicate logs
        },
        # Logger 'console' - để log ra console
        'console': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Logger cho Django - chỉ log console, không log database (quá nhiều logs)
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,  # Không propagate để tránh duplicate
        },
        # Logger cho Django requests - chỉ log console
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        # Logger cho Django server - chỉ log console
        'django.server': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Cache invalidation is extremely chatty; never persist these to DB logs (prevents task_add_log recursion)
        'cache_invalidation': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Redis pool init logs: keep on console only (Celery can call this frequently in worker processes)
        'redis_pool': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Celery redirects stdout/stderr prints into this logger; keep it out of db_handler to prevent log loops
        'celery.redirected': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Logger cho các third-party libraries - chỉ log console
        'urllib3': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'requests': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Các logger khác sẽ tự động propagate lên root logger
        # và được log vào cả console và database
    },
    'root': {
        # Root logger: mặc định CHỈ log ra console để tránh vòng lặp DB handler → task_add_log → log storm.
        # Nếu muốn persist toàn bộ logs vào DB (KHÔNG KHUYẾN NGHỊ ở production), bật env:
        #   DB_LOG_ROOT_ENABLED=True
        'handlers': (['console', 'db_handler'] if env.bool("DB_LOG_ROOT_ENABLED", default=False) else ['console']),
        'level': 'INFO',
    },
}



# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]
NINJA_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=200),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "CHECK_BLACKLIST": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "AUTH_TOKEN_CLASSES": ("ninja_jwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "JTI_CLAIM": "jti",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=200),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=7),
}

# Redis Settings
REDIS_HOST = env("REDIS_HOST", default="redis://localhost:6379")
REDIS_PORT = int(env("REDIS_PORT", default="6379"))
REDIS_DB = int(env("REDIS_DB", default="0"))

# Redis Cache Settings
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"{REDIS_HOST}/{REDIS_DB}",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

# Channels Configuration
ASGI_APPLICATION = "config.asgi.application"
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [f"{REDIS_HOST}/1"],
            "capacity": 1500,  # Giới hạn số message trong channel
            "expiry": 3600,  # Expire messages sau 1 giờ
            "group_expiry": 86400,  # Expire groups sau 24 giờ
            "channel_capacity": {
                "http.request": 100,
                "http.response!*": 100,
                "websocket.send!*": 100,
            },
        },
    },
}

AUTHENTICATION_BACKENDS = (
    "rules.permissions.ObjectPermissionBackend",
    "django.contrib.auth.backends.ModelBackend",
    "guardian.backends.ObjectPermissionBackend",
)

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = env("TIME_ZONE", default="Asia/Ho_Chi_Minh")
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Additional locations of static files
STATICFILES_DIRS = (
    [
        os.path.join(BASE_DIR, "static"),
    ]
    if os.path.exists(os.path.join(BASE_DIR, "static"))
    else []
)

# Static files finders
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

# Media files
MEDIA_URL = "media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# OpenSearch Settings
OPENSEARCH_INDEX = env("OPENSEARCH_INDEX", default="drone_logs")

# MinIO Storage Configuration
# W0-10: 사내 주소를 코드 기본값으로 두지 않는다
MINIO_ENDPOINT = env("MINIO_ENDPOINT", default="minio.internal.example")
# W0-0: 자격증명 기본값 제거 — 미설정 시 즉시 실패시킨다
MINIO_ACCESS_KEY = env("MINIO_ACCESS_KEY")
MINIO_SECRET_KEY = env("MINIO_SECRET_KEY")
MINIO_USE_HTTPS = env.bool("MINIO_USE_HTTPS", default=False)
MINIO_URL_EXPIRY_HOURS = timedelta(hours=24)  # Change to timedelta
MINIO_CONSISTENCY_CHECK_ON_START = True

# Default Storage
DEFAULT_FILE_STORAGE = "django_minio_backend.models.MinioBackend"
MINIO_STORAGE_MEDIA_BUCKET_NAME = env("MINIO_BUCKET_NAME", default="guardianx")
MINIO_BUCKET_CHECK_ON_SAVE = True
MINIO_BUCKET_AUTO_CREATE = True

# Backend URL
BACKEND_URL = env("BACKEND_URL", default="http://localhost:8000")


# MinIO Backend Buckets
MINIO_PRIVATE_BUCKETS = []
MINIO_PUBLIC_BUCKETS = [MINIO_STORAGE_MEDIA_BUCKET_NAME, "lms-media"]

# File Management Settings
FILE_NAME_MAX_LENGTH = 255  # Độ dài tối đa cho tên file


# Thiết lập Comment, Rating, Topic
COMMENT_CACHE_TTL = 300  # 5 minutes
COMMENT_MAX_ALLOWED_IMG = 10
RATING_CACHE_TTL = 300  # 5 minutes
RATING_MAX_ALLOWED_IMG = 5
FEATURED_RATING = 10
TOPIC_CACHE_TTL = 300  # 5 minutes

# Content type mappings
CONTENT_TYPE_MAPPING = {
    "article": "article",
    "topic": "topic",
    "comment": "comment",
}

# Core Settings
CORE_SETTINGS = {
    "API_VERSION": "v1",
    "API_PREFIX": "api",
    "API_DOCS_URL": "docs/",
    "API_OPENAPI_URL": "openapi.json",
    "API_TITLE": "GuardianX API",
    "API_DESCRIPTION": "API documentation for GuardianX",
    "API_AUTH": {
        "JWT": {
            "AUTH_HEADER_TYPES": ("Bearer",),
            "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
            "USER_ID_FIELD": "id",
            "USER_ID_CLAIM": "user_id",
            "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
            "TOKEN_TYPE_CLAIM": "token_type",
            "JTI_CLAIM": "jti",
        }
    },
}


CELERY_BROKER_URL = f"{REDIS_HOST}/{REDIS_DB}"
CELERY_RESULT_BACKEND = f"{REDIS_HOST}/{REDIS_DB}"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE


CELERY_WORKER_CONCURRENCY = 2  # Max 2 concurrent tasks per worker (prevent overload)
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # Only prefetch 1 task at a time
CELERY_TASK_ACKS_LATE = True  # Acknowledge after task completion
CELERY_WORKER_DISABLE_RATE_LIMITS = False  # Enable rate limiting


CELERY_TASK_SOFT_TIME_LIMIT = 300  # 5 minutes soft limit
CELERY_TASK_TIME_LIMIT = 600  # 10 minutes hard limit
CELERY_WORKER_MAX_TASKS_PER_CHILD = 50  # Restart worker after 50 tasks (prevent memory leaks)
CELERY_WORKER_MAX_MEMORY_PER_CHILD = 200000  # 200MB memory limit per worker


CELERY_TASK_REJECT_ON_WORKER_LOST = True  # Reject tasks if worker crashes
CELERY_TASK_DEFAULT_RETRY_DELAY = 60  # 1 minute between retries
CELERY_TASK_MAX_RETRIES = 3  # Maximum 3 retries


CELERY_SEND_TASK_EVENTS = True  # Enable task monitoring
CELERY_WORKER_SEND_TASK_EVENTS = True
CELERY_TASK_TRACK_STARTED = True  # Track when tasks start
CELERY_TASK_PUBLISH_RETRY = True  # Retry publishing failed tasks


CELERY_TASK_ROUTES = {
    # 🔧 FIX: Route optimization tasks to default queue
    # 'optimization.tasks.*': {'queue': 'default'},
    # Default queue for urgent tasks
    'celery.*': {'queue': 'celery'},
}

# Explicitly include operational data tasks
CELERY_IMPORTS = [
    'operational_data.tasks',
    'partner.tasks',
]

# 📋 QUEUE PRIORITIES & LIMITS
CELERY_TASK_PRIORITY_STEPS = list(range(10))  # Priority levels 0-9
CELERY_ACKS_LATE = True  # Safer task acknowledgment
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'priority_steps': list(range(10)),
    'visibility_timeout': 3600,  # 1 hour visibility timeout
    'fanout_prefix': True,
    'fanout_patterns': True,
}


CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_BEAT_SYNC_EVERY = 30  # Sync every 30 seconds (reduced load)
CELERY_BEAT_MAX_LOOP_INTERVAL = 300  # Max 5 minutes between checks

from celery.schedules import crontab





# Email Settings
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = env("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = int(env("EMAIL_PORT", default="587"))
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="your-email@gmail.com")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="your-app-password")
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="your-email@gmail.com")
ALLOWED_IMG_EXTENSIONS = [
    ".jpg",
    ".jpeg",
    ".png",
    ".gif",
    ".bmp",
    ".tiff",
    ".ico",
    ".webp",
]
# Django Ninja settings
NINJA_PAGINATION_CLASS = "ninja.pagination.PageNumberPagination"
NINJA_PAGINATION_PER_PAGE = 10
NINJA_PAGINATION_MAX_LIMIT = 100
NINJA_NUM_PROXIES = 0
NINJA_DEFAULT_THROTTLE_RATES = {
    "user": "10/minute",
    "anon": "5/minute",
}

# Third-party API Settings
# Anyang Integration Settings
ANYANG_SERVICE_KEY = env("ANYANG_SERVICE_KEY", default="")

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True  # Cho phép tất cả các origin trong môi trường phát triển


CORS_ALLOW_CREDENTIALS = True
CORS_EXPOSE_HEADERS = [
    "X-New-Token",
    "Token-Refreshed",
    "X-Token-Status",
    "Content-Disposition",
    "Content-Length",
    "X-Force-Password-Change"
]


# W0-10: 스트림·AI 엔드포인트도 사내 주소를 코드 기본값으로 두지 않는다
STREAM_URL = env("STREAM_URL", default="http://streaming.internal.example")

# GCS API Configuration
GCS_APIKEY = env("GCS_APIKEY", default="")
FLIGHTBRID_URL = env("FLIGHTBRID_URL", default="http://localhost:8009")
CAPTURE_URL = f"{STREAM_URL}/stream/api/streams/capture"
RECORD_URL = f"{STREAM_URL}/stream/api/streams/record"
RTSP_URL = env("RTSP_URL", default="rtsp://rtsp.internal.example:8554")
RTSP_PATH = f"{RTSP_URL}/stream"
RTSP_PATH_AI = f"{RTSP_URL}/stream"

AI_ANALYSIS_URL = env("AI_ANALYSIS_URL", default="https://ai-analysis.internal.example")
AI_RTSP_PATH = env("AI_RTSP_PATH", default="https://ai.internal.example/api/process_stream")
AI_GRPC_URL = env("AI_GRPC_URL", default="https://media-ai.internal.example")


# Environment
GUARDIANX_ENVIRONMENT = env("GUARDIANX_ENVIRONMENT", default="development")

IS_USE_WEBRTC = env("IS_USE_WEBRTC", default=True)

IMG_DIR = env("IMG_DIR", default=os.path.join(BASE_DIR, "stream_monitors", "media", "images"))

RECORD_DIR = env("RECORD_DIR", default=os.path.join(BASE_DIR, "stream_monitors", "media", "record"))
REDIS_RECORDING_STATUS_KEY = env("REDIS_RECORDING_STATUS_KEY", default="recording_status")


# ─────────────────────────────────────────────────────────────────────────────
# 테넌트 스코프 강제 (W0-14)
# ─────────────────────────────────────────────────────────────────────────────
# False = 경고 모드. 차단하지 않고 "차단됐을 요청"을 logger.warning 으로만 남긴다.
# True  = 차단 모드. group 이 없는 요청을 NoTenantGroupError 로 끊는다.
#
# 착수 시점 커버리지가 0/466 이라 기본값은 False 다. 미분류 라우트가 0 에
# 수렴한 뒤 이 값 하나로 차단으로 넘어간다 — 코드 되돌림 없이 되돌릴 수 있는
# 유일한 지점이므로, 스코프 판정을 코드 여러 곳에 흩지 말 것 (D-212).
TENANT_SCOPE_ENFORCE = env.bool("TENANT_SCOPE_ENFORCE", default=False)


# ─────────────────────────────────────────────────────────────────────────────
# 전역 관리 역할 정의 (W0-16 · D-243 · D-247)
# ─────────────────────────────────────────────────────────────────────────────
# "누가 전역 superuser 인가"를 **여기 한 곳에서만** 정의한다 (D-212).
# W0-14 의 뷰 레벨 스코프가 이 정의를 그대로 읽어 판정한다 — 판정식을 코드
# 여러 곳에 흩지 말 것. 흩는 순간 우회 지점이 그 수만큼 늘어난다.
#
# 배경(실측 · evidence/W0-16/superuser_accounts.md): 레거시 `superuser` **역할**을
# 13계정이 갖고 있고 그중 7계정이 **고객 테넌트(Anyang) 안**에 있다. 그 역할은
# dj-core 의 ORM 필터(core/base.py:308)와 권한 검사(core/role/permission.py:475)를
# 통째로 통과시킨다 — 둘 다 §0.4 라 고칠 수 없다. 그래서 **역할을 갈라낸다.**

# 전역(GAION 운영) 역할 코드. 이 역할만 테넌트 경계를 넘을 수 있다.
TENANT_GLOBAL_ADMIN_ROLE_CODES = env.list(
    "TENANT_GLOBAL_ADMIN_ROLE_CODES", default=["gaion_global_admin"]
)

# 레거시 `superuser` 역할을 전역으로 계속 인정할 것인가 (무중단 전환용 · D-243 ②).
# True  = 지금까지와 동일 동작. 대체역할 부여가 끝나기 전 단계의 기본값.
# False = `superuser` 역할은 더 이상 전역이 아니다 — 테넌트 스코프가 적용된다.
# 회수 순서: 대체역할 부여 → 이 값을 False → 검증 → 역할 회수 (evidence/W0-16/revocation_runbook.md)
TENANT_TRUST_LEGACY_SUPERUSER = env.bool("TENANT_TRUST_LEGACY_SUPERUSER", default=True)

# 테넌트 운영 역할(자기 테넌트 관리)의 코드 접두어. `<prefix>_<group_id>` 규약.
TENANT_ADMIN_ROLE_PREFIX = env.str("TENANT_ADMIN_ROLE_PREFIX", default="tenant_admin")


# ─────────────────────────────────────────────────────────────────────────────
# 외부 의존 저하 운전 (W0-17 · D-212)
# ─────────────────────────────────────────────────────────────────────────────
# 타임아웃 값을 **여기 한 곳에서만** 정한다. 호출부에 숫자를 흩지 말 것 —
# 흩어진 5초·30초가 실제로 몇 초인지 아무도 모르게 되는 것이 지금 상태다.
#
# 배경(실측 · evidence/W0-17/timeout_inventory.md): requests 호출 75건 중 17건에
# 타임아웃이 없다. 하나가 늦으면 워커가 잡히고, 잡힌 워커가 쌓이면 서비스가 선다.
# 실제로 목록 API 는 스트리밍 서버가 없으면 **통째로 HTTP 500** 이었다.

# (연결, 응답) 초. 연결은 짧게 — 죽은 호스트는 빨리 포기하는 것이 옳다.
EXTERNAL_HTTP_TIMEOUT = (
    env.float("EXTERNAL_HTTP_CONNECT_TIMEOUT", default=3.0),
    env.float("EXTERNAL_HTTP_READ_TIMEOUT", default=5.0),
)

# 업로드·다운로드처럼 본래 오래 걸리는 호출용. 그래도 무한은 아니다.
EXTERNAL_HTTP_TIMEOUT_LONG = (
    env.float("EXTERNAL_HTTP_CONNECT_TIMEOUT", default=3.0),
    env.float("EXTERNAL_HTTP_LONG_READ_TIMEOUT", default=60.0),
)
