# Generated by Django 5.1.2 on 2025-07-31 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_monitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='streammonitor',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
