# Generated by Django 5.1.2 on 2025-08-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_monitors', '0004_alter_drawingelement_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamMonitorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_id', models.CharField(max_length=255)),
            ],
        ),
    ]
