# Generated by Django 5.1.2 on 2025-08-12 02:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_monitors', '0005_streammonitorrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='streammonitorrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 1, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='streammonitorrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
