# Generated by Django 5.1.2 on 2025-08-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_monitors', '0006_streammonitorrecord_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streammonitorrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='streammonitorrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
