# Generated by Django 5.1.2 on 2025-08-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_monitors', '0007_alter_streammonitorrecord_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='streammonitorrecord',
            name='code',
            field=models.CharField(default='20250101000000SM_ALPHA_001', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='streammonitorrecord',
            name='object_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='streammonitorrecord',
            name='status',
            field=models.CharField(default='running', max_length=255),
        ),
    ]
