# Generated by Django 5.1.2 on 2025-08-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_monitors', '0008_streammonitorrecord_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='streammonitorrecord',
            name='auto_stop_task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for auto-stop', max_length=255, null=True),
        ),
    ]
