# Generated by Django 5.1.2 on 2025-10-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_monitors', '0009_streammonitorrecord_auto_stop_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='streammonitoraimodel',
            name='ai_stream_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='streammonitoraimodel',
            name='in_use',
            field=models.BooleanField(default=True),
        ),
    ]
