# Generated by Django 5.1.2 on 2025-11-17 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0052_remove_device_groups'),
        ('stream_monitors', '0011_alter_aimodel_options_aimodel_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='streammonitor',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='streammonitor',
            name='drone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.device'),
        ),
    ]
