# Generated by Django 5.1.2 on 2025-11-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_monitors', '0012_streammonitor_is_external_alter_streammonitor_drone'),
    ]

    operations = [
        migrations.AddField(
            model_name='streammonitor',
            name='external_drone_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='streammonitor',
            name='external_end_point_x',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='streammonitor',
            name='external_end_point_y',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='streammonitor',
            name='external_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='streammonitor',
            name='external_flight_altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='streammonitor',
            name='external_flight_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='streammonitor',
            name='external_flight_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='streammonitor',
            name='external_manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='streammonitor',
            name='external_operation_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='streammonitor',
            name='external_registration_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='streammonitor',
            name='external_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='streammonitor',
            name='external_start_point_x',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='streammonitor',
            name='external_start_point_y',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='streammonitor',
            name='external_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
