# Generated by Django 5.1.14 on 2026-08-28 13:18
#
# D-293 · D-294 — 판정을 지우지 않는 칸 하나 + 침수 전용 타입
# =========================================================
# 이 마이그레이션이 하는 일은 셋이다.
#
#   ① `verdict` 열 신설 — 사람의 판정을 담고, **종료가 덮지 않는다** (D-293).
#      `status` 는 수명주기라 마지막 칸(closed)이 앞 칸(confirmed/rejected)을 덮었고,
#      그래서 종료가 쌓일수록 오탐률이 **저절로 좋아졌다.**
#   ② `event_type` 열거에 `flood` 추가 — F-02(침수·수위) 전용 (D-294).
#      기존 타입에 실어 보내면 그 타입의 오탐률 분모가 오염되고 아무도 모른다.
#   ③ 기존 판정 백필 — 이미 confirmed/rejected 인 행의 판정을 `verdict` 로 옮긴다.
#      옮기지 않으면 **과거 코호트의 판정이 오늘 사라진다.** D-293 이 금지한 바로 그 일을
#      이 마이그레이션이 저지르는 셈이 된다.
#
# ★ 열 삭제·의미 변경은 없다. `status` 는 그대로 두고 읽는 곳만 `verdict` 로 옮겼다 —
#   기존 화면·질의가 status 를 보던 것은 계속 작동한다 (계약 문서 §하위 호환).
#
# 적용 절차는 D-283 을 따른다: sqlmigrate 로 DDL 을 먼저 보고, --backwards 로
# 되돌릴 수 있는지 확인하고, pg_dump 스냅샷을 뜬 뒤에야 migrate 한다.

from django.conf import settings
from django.db import migrations, models

#: 백필 대상 — 사람이 판정한 두 상태만. `new`·`closed` 는 판정이 아니다.
_VERDICTS = ("confirmed", "rejected")


def copy_status_to_verdict(apps, schema_editor):
    """이미 판정된 행의 판정을 `verdict` 로 옮긴다.

    ★ 조용히 돌지 않는다 — 영향 행 수를 출력한다. 백필이 0행을 고쳤는데 성공으로
      보고되면 "고칠 것이 없었다"와 "못 찾았다"가 같은 값이 된다 (D-290).

    ★ `closed` 는 백필하지 않는다. 종료 시점에 판정이 무엇이었는지는 이 열이 생기기
      **전에 이미 덮여 사라졌다.** 없는 것을 추측으로 채우지 않는다 (D-280) —
      그 손실은 `RateWindow.closed_without_verdict` 가 수로 계속 보고한다.
    """
    Event = apps.get_model("stream_monitors", "DetectionEvent")
    moved = 0
    for verdict in _VERDICTS:
        moved += Event.objects.filter(status=verdict, verdict__isnull=True).update(
            verdict=verdict)
    lost = Event.objects.filter(status="closed", verdict__isnull=True).count()
    print(f"  [D-293] verdict 백필 {moved}행 · 종료되며 판정이 이미 사라진 행 {lost}건")


def clear_verdict(apps, schema_editor):
    """되돌리기. 열을 지우기 전에 값을 비운다 — 되돌릴 수 있는 마이그레이션만 낸다."""
    Event = apps.get_model("stream_monitors", "DetectionEvent")
    cleared = Event.objects.exclude(verdict__isnull=True).update(verdict=None)
    print(f"  [D-293] verdict 되돌림 {cleared}행")


class Migration(migrations.Migration):

    dependencies = [
        ('stream_monitors', '0017_deliveryrecord_notificationrule'),
        ('surveillance', '0030_surveymission_hover_and_capture'),
        ('user', '0026_alter_passwordhistory_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionevent',
            name='verdict',
            field=models.CharField(blank=True, choices=[('confirmed', '확인'), ('rejected', '기각')], db_index=True, help_text='사람의 판정(confirmed/rejected). 종료해도 덮이지 않는다 (D-293)', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='detectionevent',
            name='event_type',
            field=models.CharField(choices=[('person', '사람'), ('vehicle', '차량'), ('fire', '화재'), ('smoke', '연기'), ('intrusion', '침입'), ('sos', '구조요청'), ('flood', '침수')], db_index=True, max_length=32),
        ),
        migrations.AddIndex(
            model_name='detectionevent',
            index=models.Index(fields=['verdict', '-occurred_at'], name='stream_moni_verdict_5a349d_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionevent',
            index=models.Index(fields=['event_type', 'verdict', '-occurred_at'], name='stream_moni_event_t_10aefe_idx'),
        ),
        migrations.RunPython(copy_status_to_verdict, clear_verdict),
    ]
