# Generated by Django 5.1.14 on 2026-08-28 14:52

import core.base
import core.multilanguage.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_monitors', '0018_detectionevent_verdict_and_more'),
        ('user', '0026_alter_passwordhistory_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('camera_group', '카메라 묶음'), ('polygon', '폴리곤')], db_index=True, default='camera_group', max_length=16)),
                ('geometry', models.JSONField(blank=True, help_text='F-03 폴리곤. 표현·좌표계 미확정이므로 비워 둔다 (D-280)', null=True)),
                ('geometry_status', models.CharField(choices=[('not_implemented', '미구현'), ('ready', '가동')], db_index=True, default='not_implemented', help_text='폴리곤 판정이 실제로 도는가. ready 가 하나라도 있으면 ZONE_POLYGON_READY 가 True 여야 한다 (D-299)', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('cameras', models.ManyToManyField(blank=True, help_text="이 구역에 속한 카메라. kind='camera_group' 일 때 판정의 근거다", related_name='zones', to='stream_monitors.streammonitor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
                'indexes': [models.Index(fields=['kind', 'is_active'], name='stream_moni_kind_332478_idx')],
            },
            bases=(models.Model, core.multilanguage.models.MultiLanguageContentMixin, core.base.DependencyCheckMixin),
        ),
    ]
