# Generated by Django 5.1.14 on 2026-08-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_monitors', '0019_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionevent',
            name='address',
            field=models.CharField(blank=True, help_text='도로명 주소 (FX-5). 조회 전·불가 시 null — 빈 문자열과 구별한다', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='detectionevent',
            name='address_status',
            field=models.CharField(choices=[('pending', '조회 대기'), ('resolved', '조회 완료'), ('failed', '조회 실패'), ('disabled', '조회 안 함')], db_index=True, default='pending', help_text='주소 조회 상태 (FX-5 · D-290). pending 과 failed 를 합치지 않는다', max_length=16),
        ),
    ]
