# Generated by Django 5.1.14 on 2026-08-29 08:44

import core.base
import core.multilanguage.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_monitors', '0021_eventclip'),
        ('user', '0026_alter_passwordhistory_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='streammonitor',
            name='address_source',
            field=models.CharField(choices=[('unset', '미입력'), ('manual', '수기 입력')], db_index=True, default='unset', help_text='unset = 아직 안 적음. 알림은 좌표 1줄로 나가고 지연되지 않는다 (D-330)', max_length=16),
        ),
        migrations.AddField(
            model_name='streammonitor',
            name='install_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='streammonitor',
            name='install_address_detail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ThresholdChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('key', models.CharField(db_index=True, max_length=64)),
                ('scope_level', models.CharField(db_index=True, max_length=8)),
                ('camera_label', models.CharField(blank=True, default='', max_length=255)),
                ('old_value', models.CharField(blank=True, max_length=64, null=True)),
                ('new_value', models.CharField(blank=True, max_length=64, null=True)),
                ('reason', models.CharField(max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threshold_changes', to='stream_monitors.streammonitor')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threshold_changes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'k5_threshold_change',
                'ordering': ['-changed_at', '-id'],
            },
            bases=(models.Model, core.multilanguage.models.MultiLanguageContentMixin, core.base.DependencyCheckMixin),
        ),
        migrations.CreateModel(
            name='CredentialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('absent', '이 환경에 없다'), ('present', '파일에 있다'), ('typed', '무슨 API 인지 안다'), ('verified', '호출해서 확인했다'), ('rotated', '재발급됨')], db_index=True, default='absent', max_length=16)),
                ('api_type', models.CharField(blank=True, default='', max_length=128)),
                ('capability', models.TextField(blank=True, default='')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'k5_credential_record',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status'], name='k5_credenti_status_6fc7b9_idx')],
            },
            bases=(models.Model, core.multilanguage.models.MultiLanguageContentMixin, core.base.DependencyCheckMixin),
        ),
        migrations.CreateModel(
            name='ThresholdSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('key', models.CharField(db_index=True, max_length=64)),
                ('scope_level', models.CharField(choices=[('global', '전역'), ('tenant', '테넌트'), ('camera', '카메라')], db_index=True, default='global', max_length=8)),
                ('value', models.CharField(max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threshold_settings', to='stream_monitors.streammonitor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threshold_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'k5_threshold_setting',
                'indexes': [models.Index(fields=['key', 'scope_level'], name='k5_threshol_key_b056a2_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('scope_level', 'global')), fields=('key',), name='uniq_threshold_global'), models.UniqueConstraint(condition=models.Q(('scope_level', 'tenant')), fields=('key', 'group'), name='uniq_threshold_tenant'), models.UniqueConstraint(condition=models.Q(('scope_level', 'camera')), fields=('key', 'camera'), name='uniq_threshold_camera')],
            },
            bases=(models.Model, core.multilanguage.models.MultiLanguageContentMixin, core.base.DependencyCheckMixin),
        ),
    ]
