# Generated by Django 5.1.14 on 2026-09-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_monitors', '0023_graderulechange_graderule'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionevent',
            name='response_state',
            field=models.CharField(choices=[('occurred', '발생'), ('acknowledged', '접수 확인'), ('in_progress', '조치중'), ('closed', '종결')], db_index=True, default='occurred', help_text='대응 진행(발생→접수확인→조치중→종결). status(탐지 판정)와 다른 축이다 (D-399)', max_length=16),
        ),
    ]
