# Generated by Django 5.1.14 on 2026-09-05 04:06

import core.base
import core.multilanguage.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_monitors', '0027_ops15_camera_pulse'),
        ('user', '0026_alter_passwordhistory_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('endpoint_url', models.URLField(max_length=500)),
                ('signing_key_ref', models.CharField(max_length=64)),
                ('event_types', models.JSONField(blank=True, default=list)),
                ('min_severity', models.CharField(blank=True, default='', max_length=16)),
                ('payload_format', models.CharField(choices=[('json', 'CAP 1.2 (JSON)'), ('xml', 'CAP 1.2 (XML)')], default='json', max_length=8)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gx_webhook_subscription',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['is_active'], name='gx_webhook__is_acti_fc9a99_idx')],
            },
            bases=(models.Model, core.multilanguage.models.MultiLanguageContentMixin, core.base.DependencyCheckMixin),
        ),
    ]
