# Generated by Django 5.1.14 on 2026-09-18 03:39

import core.base
import core.multilanguage.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_monitors', '0029_v11_tables'),
        ('user', '0026_alter_passwordhistory_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DsmApiKeyScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('purpose_code', models.CharField(max_length=64)),
                ('key_id', models.PositiveIntegerField(db_index=True)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dsm_api_key_scope',
                'ordering': ['-id'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('purpose_code', ''), _negated=True), name='stream_monitors_dsmapikeyscope_purpose_code_required'), models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('key_id',), name='dsm_api_key_scope_one_live_per_key')],
            },
            bases=(models.Model, core.multilanguage.models.MultiLanguageContentMixin, core.base.DependencyCheckMixin),
        ),
        migrations.CreateModel(
            name='DsmSystemRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('purpose_code', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('restart', '재시작 요청')], db_index=True, default='restart', max_length=16)),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('requested', '요청됨 — 실행은 점검 창에서'), ('scheduled', '점검 창에 잡힘'), ('done', '실행됨'), ('rejected', '반려됨')], db_index=True, default='requested', max_length=16)),
                ('handled_note', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dsm_system_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dsm_system_request',
                'ordering': ['-id'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('purpose_code', ''), _negated=True), name='stream_monitors_dsmsystemrequest_purpose_code_required'), models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='dsm_system_request_reason_required')],
            },
            bases=(models.Model, core.multilanguage.models.MultiLanguageContentMixin, core.base.DependencyCheckMixin),
        ),
    ]
