# Generated by Django 5.1.2 on 2025-05-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitemtype_is_active_orderstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sender_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
