# Generated by Django 5.1.2 on 2025-05-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_sender_name_order_sender_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='currency',
            field=models.CharField(default='KRW', max_length=3),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='dimension_unit',
            field=models.CharField(default='mm', max_length=2),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='weight_unit',
            field=models.CharField(default='g', max_length=2),
        ),
    ]
