# Generated by Django 5.1.2 on 2025-05-20 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_amount_orderitem_code_orderitem_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_address',
        ),
    ]
