# Generated by Django 5.1.2 on 2025-05-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20250520_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='dimension_h',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='dimension_l',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='dimension_w',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='weight',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
