# Generated by Django 5.1.2 on 2025-05-21 06:09

import core.multilanguage.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_orderitem_dimension_unit_and_more'),
        ('terminals', '0008_routes_total_stops'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('cancelled', 'Cancelled'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('returned', 'Returned')], max_length=20)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='orders.order')),
            ],
            options={
                'ordering': ['-created_on'],
            },
            bases=(models.Model, core.multilanguage.models.MultiLanguageContentMixin),
        ),
        migrations.CreateModel(
            name='ReturnOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('return_time_period', models.CharField(blank=True, max_length=255, null=True)),
                ('return_received_time', models.DateTimeField(blank=True, null=True)),
                ('return_days', models.IntegerField(blank=True, null=True)),
                ('return_from_date', models.DateField(blank=True, null=True)),
                ('return_to_date', models.DateField(blank=True, null=True)),
                ('return_available', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_orders', to='orders.order')),
                ('return_terminal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_orders', to='terminals.terminal')),
            ],
            options={
                'ordering': ['-created_on'],
            },
            bases=(models.Model, core.multilanguage.models.MultiLanguageContentMixin),
        ),
    ]
