# Generated by Django 5.1.2 on 2025-05-23 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_orderhistory_action_bank_refundorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
    ]
