# Generated by Django 5.1.2 on 2025-05-23 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_order_payment_method'),
        ('terminals', '0008_routes_total_stops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderassignment',
            name='order',
        ),
        migrations.AddField(
            model_name='orderassignment',
            name='order_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='orders.orderitem'),
        ),
        migrations.AlterField(
            model_name='orderassignment',
            name='route_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='terminals.routes'),
        ),
    ]
