# Generated by Django 5.1.2 on 2025-05-23 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_orderassignment_order_and_more'),
        ('terminals', '0008_routes_total_stops'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryevent',
            name='terminal_stop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_events', to='terminals.terminal'),
        ),
    ]
