# Generated by Django 5.1.2 on 2025-05-26 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_orderhistory_action'),
        ('user', '0013_alter_userprofilelink_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
    ]
