# Generated by Django 5.1.2 on 2025-05-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_remove_order_group_order_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('cancelled', 'Cancelled'), ('paid', 'Paid'), ('verified', 'Verified'), ('arrived', 'Arrived'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('returned', 'Returned'), ('refunded', 'Refunded'), ('started_delivery', 'Started Delivery'), ('arrived_at_terminal', 'Arrived at Terminal'), ('overdue', 'Overdue')], max_length=20),
        ),
    ]
