# Generated by Django 5.1.2 on 2025-06-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_orderhistory_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='another_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
