# Generated by Django 5.1.2 on 2025-06-18 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_address_note'),
        ('orders', '0018_order_another_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sender_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sender_orders', to='delivery.address'),
        ),
    ]
