# Generated by Django 5.1.2 on 2025-06-23 04:05

import core.fields.money
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_order_sender_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='currency',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=core.fields.money.EnhancedMoneyField(blank=True, decimal_places=4, help_text='Delivery/shipping fee', max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=core.fields.money.EnhancedMoneyField(blank=True, decimal_places=4, help_text='Discount amount', max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=core.fields.money.EnhancedMoneyField(blank=True, decimal_places=4, help_text='Subtotal of all order items', max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=core.fields.money.EnhancedMoneyField(blank=True, decimal_places=4, help_text='Tax amount', max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=core.fields.money.EnhancedMoneyField(blank=True, decimal_places=4, help_text='Total amount to be paid', max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='refundorder',
            name='processing_fee',
            field=core.fields.money.EnhancedMoneyField(blank=True, decimal_places=4, help_text='Processing fee for refund', max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='refundorder',
            name='refund_amount',
            field=core.fields.money.EnhancedMoneyField(blank=True, decimal_places=4, help_text='Amount to be refunded', max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='refundorder',
            name='refund_processed_at',
            field=models.DateTimeField(blank=True, help_text='When refund was processed', null=True),
        ),
        migrations.AddField(
            model_name='refundorder',
            name='refund_reference',
            field=models.CharField(blank=True, help_text='Reference number from bank/payment provider', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='refundorder',
            name='refund_status',
            field=models.CharField(default='pending', help_text='Status of refund process', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=core.fields.money.EnhancedMoneyField(decimal_places=4, help_text='Total invoice amount', max_digits=19),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='amount',
            field=core.fields.money.EnhancedMoneyField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=core.fields.money.EnhancedMoneyField(decimal_places=4, max_digits=19),
        ),
    ]
