# Generated by Django 5.1.2 on 2025-06-30 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_remove_orderitem_currency_remove_payment_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='groups',
        ),
    ]
