# Generated by Django 5.1.2 on 2025-07-21 09:41

import core.base
import core.fields.money
import core.multilanguage.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_remove_order_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(help_text='Product name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Product description', null=True)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of this product')),
                ('unit_weight', models.JSONField(blank=True, help_text='Weight per unit: {"value": float, "unit": "kg"}', null=True)),
                ('unit_price', core.fields.money.EnhancedMoneyField(blank=True, decimal_places=4, help_text='Price per unit', max_digits=19, null=True)),
                ('total_price', core.fields.money.EnhancedMoneyField(blank=True, decimal_places=4, help_text='Total price (unit_price * quantity)', max_digits=19, null=True)),
                ('product_type', models.CharField(blank=True, help_text='Product type classification', max_length=100, null=True)),
                ('is_dangerous', models.BooleanField(default=False, help_text='Whether product is dangerous goods')),
                ('is_temperature_sensitive', models.BooleanField(default=False, help_text='Requires temperature control')),
                ('manufacturer', models.CharField(blank=True, help_text='Product manufacturer', max_length=255, null=True)),
                ('model_number', models.CharField(blank=True, help_text='Product model/SKU', max_length=100, null=True)),
                ('customs_code', models.CharField(blank=True, help_text='Customs classification code', max_length=50, null=True)),
                ('origin_country', models.CharField(blank=True, help_text='Country of origin', max_length=100, null=True)),
                ('another_info', models.JSONField(blank=True, help_text='Additional product information', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='orders.orderitem')),
            ],
            options={
                'verbose_name': 'Product Item',
                'verbose_name_plural': 'Product Items',
                'ordering': ['order_item', 'id'],
            },
            bases=(models.Model, core.multilanguage.models.MultiLanguageContentMixin, core.base.DependencyCheckMixin),
        ),
    ]
