# Generated by Django 5.1.2 on 2025-08-06 04:45

import core.base
import core.multilanguage.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0019_delete_deliverystatusmapping'),
        ('orders', '0022_productitem'),
        ('user', '0022_coreuser_is_rejected_coreuser_reject_on_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='external_status_code',
            field=models.CharField(blank=True, help_text='Status code/ID received from external API', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ExternalOrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(help_text='Display name for this external order status', max_length=100)),
                ('value', models.CharField(help_text='Value/code received from external API', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of this status', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this status is active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'External Order Status',
                'verbose_name_plural': 'External Order Statuses',
                'ordering': ['group', 'name'],
                'unique_together': {('value', 'group')},
            },
            bases=(models.Model, core.multilanguage.models.MultiLanguageContentMixin, core.base.DependencyCheckMixin),
        ),
        migrations.CreateModel(
            name='OrderStatusMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this mapping is active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('delivery_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_status_mappings', to='delivery.deliverystatus')),
                ('external_order_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_mappings', to='orders.externalorderstatus')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order Status Mapping',
                'verbose_name_plural': 'Order Status Mappings',
                'ordering': ['group', 'delivery_status'],
                'unique_together': {('delivery_status', 'external_order_status', 'group')},
            },
            bases=(models.Model, core.multilanguage.models.MultiLanguageContentMixin, core.base.DependencyCheckMixin),
        ),
    ]
