# Generated by Django 5.1.2 on 2025-08-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_order_external_status_code_externalorderstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalorderstatus',
            name='background_color',
            field=models.CharField(blank=True, help_text='Background color for this status', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='externalorderstatus',
            name='border_color',
            field=models.CharField(blank=True, help_text='Border color for this status', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='externalorderstatus',
            name='text_color',
            field=models.CharField(blank=True, help_text='Text color for this status', max_length=20, null=True),
        ),
    ]
