# Generated by Django 5.1.2 on 2025-08-06 09:02

from django.db import migrations
from django.db.models import Count


def clean_duplicate_mappings(apps, schema_editor):
    """
    Clean up duplicate OrderStatusMapping records that would violate
    the new unique constraint: delivery_status + group
    """
    OrderStatusMapping = apps.get_model('orders', 'OrderStatusMapping')
    
    # Find duplicates based on delivery_status + group
    duplicates = OrderStatusMapping.objects.values(
        'delivery_status', 'group'
    ).annotate(
        count=Count('id')
    ).filter(count__gt=1)
    
    print(f"Found {len(duplicates)} duplicate groups to clean up")
    
    for duplicate in duplicates:
        delivery_status_id = duplicate['delivery_status']
        group_id = duplicate['group']
        
        # Get all mappings for this combination
        mappings = OrderStatusMapping.objects.filter(
            delivery_status_id=delivery_status_id,
            group_id=group_id
        ).order_by('id')
        
        if mappings.count() > 1:
            # Keep the first one, delete the rest
            keep_mapping = mappings.first()
            delete_mappings = mappings.exclude(id=keep_mapping.id)
            
            print(f"Keeping mapping {keep_mapping.id}, deleting {delete_mappings.count()} duplicates")
            delete_mappings.delete()


def reverse_clean_duplicate_mappings(apps, schema_editor):
    """
    Reverse migration - nothing to do as we can't restore deleted duplicates
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_externalorderstatus_background_color_and_more'),
    ]

    operations = [
        migrations.RunPython(
            clean_duplicate_mappings,
            reverse_clean_duplicate_mappings
        ),
    ]
