# Generated by Django 5.1.2 on 2025-08-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0019_delete_deliverystatusmapping'),
        ('orders', '0025_prepare_data_for_many_to_many'),
        ('user', '0022_coreuser_is_rejected_coreuser_reject_on_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderstatusmapping',
            unique_together={('delivery_status', 'group')},
        ),
        migrations.AddField(
            model_name='orderstatusmapping',
            name='external_order_statuses',
            field=models.ManyToManyField(help_text='External order statuses that map to this delivery status', related_name='delivery_mappings', to='orders.externalorderstatus'),
        ),
        migrations.RemoveField(
            model_name='orderstatusmapping',
            name='external_order_status',
        ),
    ]
