BEGIN;
--
-- Create model Zone
--
CREATE TABLE "stream_monitors_zone" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "deleted" timestamp with time zone NULL, "deleted_by_cascade" boolean NOT NULL, "created_on" timestamp with time zone NULL, "modified_on" timestamp with time zone NULL, "name" varchar(255) NOT NULL, "kind" varchar(16) NOT NULL, "geometry" jsonb NULL, "geometry_status" varchar(20) NOT NULL, "is_active" boolean NOT NULL, "created_by_id" bigint NULL, "group_id" bigint NULL, "modified_by_id" bigint NULL);
CREATE TABLE "stream_monitors_zone_cameras" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "zone_id" bigint NOT NULL, "streammonitor_id" bigint NOT NULL);
ALTER TABLE "stream_monitors_zone" ADD CONSTRAINT "stream_monitors_zone_created_by_id_cce8e1eb_fk_user_coreuser_id" FOREIGN KEY ("created_by_id") REFERENCES "user_coreuser" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "stream_monitors_zone" ADD CONSTRAINT "stream_monitors_zone_group_id_68bfe132_fk_user_usergroup_id" FOREIGN KEY ("group_id") REFERENCES "user_usergroup" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "stream_monitors_zone" ADD CONSTRAINT "stream_monitors_zone_modified_by_id_e997fee3_fk_user_core" FOREIGN KEY ("modified_by_id") REFERENCES "user_coreuser" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "stream_monitors_zone_deleted_b866a10e" ON "stream_monitors_zone" ("deleted");
CREATE INDEX "stream_monitors_zone_kind_29013815" ON "stream_monitors_zone" ("kind");
CREATE INDEX "stream_monitors_zone_kind_29013815_like" ON "stream_monitors_zone" ("kind" varchar_pattern_ops);
CREATE INDEX "stream_monitors_zone_geometry_status_9636956f" ON "stream_monitors_zone" ("geometry_status");
CREATE INDEX "stream_monitors_zone_geometry_status_9636956f_like" ON "stream_monitors_zone" ("geometry_status" varchar_pattern_ops);
CREATE INDEX "stream_monitors_zone_created_by_id_cce8e1eb" ON "stream_monitors_zone" ("created_by_id");
CREATE INDEX "stream_monitors_zone_group_id_68bfe132" ON "stream_monitors_zone" ("group_id");
CREATE INDEX "stream_monitors_zone_modified_by_id_e997fee3" ON "stream_monitors_zone" ("modified_by_id");
CREATE INDEX "stream_moni_kind_332478_idx" ON "stream_monitors_zone" ("kind", "is_active");
ALTER TABLE "stream_monitors_zone_cameras" ADD CONSTRAINT "stream_monitors_zone_cam_zone_id_streammonitor_id_4bc4c5cf_uniq" UNIQUE ("zone_id", "streammonitor_id");
ALTER TABLE "stream_monitors_zone_cameras" ADD CONSTRAINT "stream_monitors_zone_zone_id_00b0c651_fk_stream_mo" FOREIGN KEY ("zone_id") REFERENCES "stream_monitors_zone" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "stream_monitors_zone_cameras" ADD CONSTRAINT "stream_monitors_zone_streammonitor_id_394f3921_fk_stream_mo" FOREIGN KEY ("streammonitor_id") REFERENCES "stream_monitors_streammonitor" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "stream_monitors_zone_cameras_zone_id_00b0c651" ON "stream_monitors_zone_cameras" ("zone_id");
CREATE INDEX "stream_monitors_zone_cameras_streammonitor_id_394f3921" ON "stream_monitors_zone_cameras" ("streammonitor_id");
COMMIT;
