# Generated by Django 5.1.2 on 2025-05-21 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverystatus',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='deliveryitem',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='deliveryroute',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='deliveryitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='deliveryitem',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='deliveryroute',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='deliveryroute',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='deliverystatus',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='deliverystatus',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='deliverystatus',
            name='recorded_by',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='DeliveryItem',
        ),
        migrations.DeleteModel(
            name='DeliveryRoute',
        ),
        migrations.DeleteModel(
            name='DeliveryStatus',
        ),
    ]
