# Generated by Django 5.1.2 on 2025-05-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_deliverycancellationreason_deliveryoperation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryoperationitem',
            name='drone_arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryoperationitem',
            name='is_delivered_by_drone',
            field=models.BooleanField(default=False),
        ),
    ]
