# Generated by Django 5.1.2 on 2025-05-21 07:04

import core.multilanguage.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_deliveryoperationitem_drone_arrived_at_and_more'),
        ('devices', '0023_device_unit_id'),
        ('terminals', '0008_routes_total_stops'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverycancellation',
            name='cancellation_reason',
        ),
        migrations.RenameField(
            model_name='deliverycancellation',
            old_name='notes',
            new_name='reason',
        ),
        migrations.RemoveField(
            model_name='deliverycancellation',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='deliverycancellation',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='deliverycancellation',
            name='cancellation_approved',
        ),
        migrations.RemoveField(
            model_name='deliverycancellation',
            name='cancellation_type',
        ),
        migrations.RemoveField(
            model_name='deliverycancellation',
            name='penalty_applied',
        ),
        migrations.RemoveField(
            model_name='deliverycancellation',
            name='refund_amount',
        ),
        migrations.RemoveField(
            model_name='deliverycancellation',
            name='refund_processed',
        ),
        migrations.RemoveField(
            model_name='deliverycancellation',
            name='refund_processed_at',
        ),
        migrations.AlterField(
            model_name='deliveryoperationitem',
            name='delivery_operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='delivery.deliveryoperation'),
        ),
        migrations.AlterField(
            model_name='deliveryoperationitem',
            name='drone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_items', to='devices.device'),
        ),
        migrations.AlterField(
            model_name='deliveryoperationitem',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_items', to='devices.packagingspecification'),
        ),
        migrations.AlterField(
            model_name='deliveryreturn',
            name='return_reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='delivery.deliveryreturnreason'),
        ),
        migrations.AlterField(
            model_name='deliveryreturn',
            name='return_terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_returns', to='terminals.terminal'),
        ),
        migrations.CreateModel(
            name='DeliveryCancellationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('reason_default', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cancellation Reason Type',
                'verbose_name_plural': 'Cancellation Reason Types',
                'ordering': ['id'],
            },
            bases=(models.Model, core.multilanguage.models.MultiLanguageContentMixin),
        ),
        migrations.AddField(
            model_name='deliverycancellation',
            name='reason_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancellations', to='delivery.deliverycancellationtype'),
        ),
        migrations.DeleteModel(
            name='DeliveryCancellationReason',
        ),
    ]
