# Generated by Django 5.1.2 on 2025-05-21 04:08

from django.db import migrations

def seed_delivery_status(apps, schema_editor):
    DeliveryStatus = apps.get_model('delivery', 'DeliveryStatus')
    from delivery.constants import DELIVERY_STATUS_LIST

    for status in DELIVERY_STATUS_LIST:
        DeliveryStatus.objects.update_or_create(
            code=status["code"],
            defaults={
                "name": status["name"],
                "description": status.get("description", ""),
                "color_code": status.get("color_code", ""),
            }
        )
        
def seed_cancellation_types(apps, schema_editor):
    DeliveryCancellationType = apps.get_model('delivery', 'DeliveryCancellationType')
    from delivery.constants import CANCELLATION_TYPE_LIST
    
    for cancellation_type in CANCELLATION_TYPE_LIST:
        DeliveryCancellationType.objects.update_or_create(
            code=cancellation_type["code"],
            defaults={
                "reason_default": cancellation_type.get("reason_default", ""),
            }
        )

class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_remove_deliverycancellation_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_delivery_status),
        migrations.RunPython(seed_cancellation_types),
    ]
