# Generated by Django 5.1.2 on 2025-05-22 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_delivery_status_and_cancell_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryreturn',
            name='return_reason',
        ),
        migrations.RemoveField(
            model_name='deliveryreturn',
            name='condition_on_return',
        ),
        migrations.RemoveField(
            model_name='deliveryreturn',
            name='disposition',
        ),
        migrations.RemoveField(
            model_name='deliveryreturn',
            name='inspected_at',
        ),
        migrations.RemoveField(
            model_name='deliveryreturn',
            name='inspected_by',
        ),
        migrations.RemoveField(
            model_name='deliveryreturn',
            name='is_processed',
        ),
        migrations.RemoveField(
            model_name='deliveryreturn',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='deliveryreturn',
            name='processed_at',
        ),
        migrations.RemoveField(
            model_name='deliveryreturn',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='deliveryreturn',
            name='requires_inspection',
        ),
        migrations.RemoveField(
            model_name='deliveryreturn',
            name='restock_fee',
        ),
        migrations.RemoveField(
            model_name='deliveryreturn',
            name='return_photos',
        ),
        migrations.AddField(
            model_name='deliveryreturn',
            name='status_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_returns', to='delivery.deliverystatus'),
        ),
        migrations.DeleteModel(
            name='DeliveryReturnReason',
        ),
    ]
