# Generated by Django 5.1.2 on 2025-05-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_alter_deliveryoperation_order_and_more'),
        ('user', '0013_alter_userprofilelink_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryoperation',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_groups', to='user.usergroup'),
        ),
    ]
