# Generated by Django 5.1.2 on 2025-05-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_deliveryoperation_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryoperationitem',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryoperationitem',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
