# Generated by Django 5.1.2 on 2025-05-29 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_deliveryoperationitem_delivered_at_and_more'),
        ('orders', '0017_alter_orderhistory_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryoperationitem',
            name='package',
        ),
        migrations.AddField(
            model_name='deliveryoperationitem',
            name='order_item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_item', to='orders.orderitem'),
        ),
    ]
