# Generated by Django 5.1.2 on 2025-06-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_remove_deliveryoperationitem_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryoperation',
            name='another_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
