# Generated by Django 5.1.2 on 2025-06-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_deliveryoperation_another_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
