# Generated by Django 5.1.2 on 2025-06-30 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_address_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryoperation',
            name='groups',
        ),
    ]
