# Generated by Django 5.1.2 on 2025-07-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0014_remove_deliveryoperation_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryoperation',
            name='confirmation_photo',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_confirmations/'),
        ),
    ]
