# Generated by Django 5.1.2 on 2025-07-30 06:16

import core.base
import core.multilanguage.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0015_deliveryoperation_confirmation_photo'),
        ('user', '0021_remove_level_group_remove_position_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryStatusMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('custom_name', models.CharField(help_text='Custom display name for this status', max_length=100)),
                ('custom_code', models.CharField(blank=True, help_text='Custom code for this status', max_length=50, null=True)),
                ('text_color', models.CharField(blank=True, help_text='Hex color code for text (e.g. #FFFFFF)', max_length=20, null=True)),
                ('background_color', models.CharField(blank=True, help_text='Hex color code for background (e.g. #FF5733)', max_length=20, null=True)),
                ('border_color', models.CharField(blank=True, help_text='Hex color code for border (e.g. #FF5733)', max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this mapping is active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, related_name='%(class)s_groups', to='user.usergroup')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_mappings', to='delivery.deliverystatus')),
            ],
            options={
                'verbose_name': 'Delivery Status Mapping',
                'verbose_name_plural': 'Delivery Status Mappings',
                'ordering': ['status__id'],
            },
            bases=(models.Model, core.multilanguage.models.MultiLanguageContentMixin, core.base.DependencyCheckMixin),
        ),
    ]
