# Generated by Django 5.1.2 on 2025-07-30 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0016_deliverystatusmapping'),
        ('user', '0021_remove_level_group_remove_position_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverystatusmapping',
            name='groups',
        ),
        migrations.AddField(
            model_name='deliverystatusmapping',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
    ]
