# Generated by Django 5.1.2 on 2025-07-31 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0017_remove_deliverystatusmapping_groups_and_more'),
        ('user', '0021_remove_level_group_remove_position_group'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deliverystatusmapping',
            unique_together={('status', 'group')},
        ),
    ]
