# Generated by Django 5.1.2 on 2025-08-06 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0018_alter_deliverystatusmapping_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryStatusMapping',
        ),
    ]
