# Generated by Django 5.1.2 on 2025-08-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0019_delete_deliverystatusmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryoperation',
            name='is_partial_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryoperationitem',
            name='is_drone_approved',
            field=models.BooleanField(default=False),
        ),
    ]
