# Generated by Django 5.1.2 on 2025-08-12 07:01

import core.base
import core.multilanguage.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist_setting', '0002_checklistsettingcategory_and_more'),
        ('delivery', '0021_deliveryoperationapproval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOperationApprovalChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('item_name_snapshot', models.CharField(blank=True, max_length=255, null=True)),
                ('category_code_snapshot', models.CharField(blank=True, max_length=255, null=True)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='delivery.deliveryoperationapproval')),
                ('checklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_links', to='checklist_setting.checklistsetting')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delivery Operation Approval Checklist',
                'verbose_name_plural': 'Delivery Operation Approval Checklists',
                'unique_together': {('approval', 'checklist')},
            },
            bases=(models.Model, core.multilanguage.models.MultiLanguageContentMixin, core.base.DependencyCheckMixin),
        ),
    ]
