# Generated by Django 5.1.2 on 2025-08-21 07:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0022_deliveryoperationapprovalchecklist'),
        ('devices', '0044_device_color'),
        ('orders', '0027_orderstatusmapping_name'),
        ('terminals', '0043_alter_routes_two_way'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='deliveryoperation',
            index=models.Index(fields=['route'], name='delivery_de_route_i_420fc7_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryoperationitem',
            index=models.Index(fields=['delivery_operation'], name='delivery_de_deliver_f55979_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryoperationitem',
            index=models.Index(fields=['delivery_operation', 'order_item'], name='delivery_de_deliver_99983e_idx'),
        ),
    ]
