# Generated by Django 5.1.2 on 2025-09-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0023_deliveryoperation_delivery_de_route_i_420fc7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryoperationitem',
            name='upload_mission',
            field=models.BooleanField(default=False),
        ),
    ]
