# Generated by Django 5.1.2 on 2025-09-06 03:31

import core.base
import core.multilanguage.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0024_deliveryoperationitem_upload_mission'),
        ('devices', '0049_alter_devicestatus_code'),
        ('terminals', '0047_remove_routeterminal_takeoff_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('sequence_order', models.PositiveIntegerField(help_text='The order in which this terminal should be visited (1, 2, 3, ...)')),
                ('is_visited', models.BooleanField(default=False, help_text='Whether the drone has already visited this terminal')),
                ('visited_at', models.DateTimeField(blank=True, help_text='When the drone visited this terminal', null=True)),
                ('coordinates_lat', models.DecimalField(decimal_places=6, help_text='Terminal latitude at time of sequence creation', max_digits=9)),
                ('coordinates_lon', models.DecimalField(decimal_places=6, help_text='Terminal longitude at time of sequence creation', max_digits=9)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this terminal sequence', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('delivery_operation', models.ForeignKey(help_text='The delivery operation this sequence belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='terminal_sequences', to='delivery.deliveryoperation')),
                ('drone', models.ForeignKey(blank=True, help_text='The drone that visited this terminal', null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('terminal', models.ForeignKey(help_text='The terminal in the sequence', on_delete=django.db.models.deletion.CASCADE, to='terminals.terminal')),
            ],
            options={
                'verbose_name': 'Terminal Sequence',
                'verbose_name_plural': 'Terminal Sequences',
                'ordering': ['delivery_operation', 'sequence_order'],
                'indexes': [models.Index(fields=['delivery_operation', 'sequence_order'], name='delivery_te_deliver_592291_idx'), models.Index(fields=['delivery_operation', 'is_visited'], name='delivery_te_deliver_cb11ed_idx'), models.Index(fields=['terminal', 'is_visited'], name='delivery_te_termina_769716_idx')],
                'unique_together': {('delivery_operation', 'sequence_order'), ('delivery_operation', 'terminal')},
            },
            bases=(models.Model, core.multilanguage.models.MultiLanguageContentMixin, core.base.DependencyCheckMixin),
        ),
    ]
