# Generated by Django 5.1.2 on 2025-09-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0026_alter_terminalsequence_terminal_to_routeterminal'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalsequence',
            name='is_special_case',
            field=models.BooleanField(default=False, help_text='Whether this terminal sequence is marked as special case based on command_line ID'),
        ),
    ]
