# Generated by Django 5.1.2 on 2025-09-30 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0027_add_is_special_case_to_terminal_sequence'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='terminalsequence',
            unique_together=set(),
        ),
    ]
