# Generated by Django 5.1.2 on 2025-08-28 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist_setting', '0002_checklistsettingcategory_and_more'),
        ('user', '0022_coreuser_is_rejected_coreuser_reject_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistsetting',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_groups', to='user.usergroup'),
        ),
    ]
