# Generated by Django 5.1.2 on 2025-08-28 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist_setting', '0003_checklistsetting_groups'),
        ('user', '0022_coreuser_is_rejected_coreuser_reject_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistsetting',
            name='groups',
        ),
        migrations.AddField(
            model_name='checklistsetting',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
    ]
