# Generated by Django 5.1.2 on 2025-11-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist_setting', '0005_checklistsettingcategory_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistsetting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
