# Generated by Django 5.1.2 on 2025-08-25 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0014_alter_usermediafile_file_url'),
        ('operational_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationaldata',
            name='media_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_management.usermediafile'),
        ),
    ]
