# Generated by Django 5.1.2 on 2025-08-29 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0023_deliveryoperation_delivery_de_route_i_420fc7_idx_and_more'),
        ('operational_data', '0002_alter_operationaldata_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationaldata',
            name='operation_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_data', to='delivery.deliveryoperationitem'),
        ),
    ]
