# Generated by Django 5.1.2 on 2025-09-15 03:10

import core.base
import core.multilanguage.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operational_data', '0003_alter_operationaldata_operation_item'),
        ('orders', '0027_orderstatusmapping_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalDataUploadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('task_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('upload_type', models.CharField(choices=[('video', 'Video'), ('log', 'Log')], default='video', max_length=50)),
                ('device_type', models.CharField(choices=[('drone', 'Drone'), ('robot', 'Robot')], default='drone', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('partial_success', 'Partial Success'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('total_files', models.IntegerField(default=0)),
                ('uploaded_files', models.IntegerField(default=0)),
                ('failed_files', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True, null=True)),
                ('error_details', models.JSONField(blank=True, null=True)),
                ('failed_file_details', models.JSONField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_statuses', to='orders.orderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['task_id'], name='operational_task_id_76bb34_idx'), models.Index(fields=['order_item', 'upload_type', 'device_type'], name='operational_order_i_a7a27f_idx'), models.Index(fields=['user', 'status'], name='operational_user_id_dcec3a_idx')],
            },
            bases=(models.Model, core.multilanguage.models.MultiLanguageContentMixin, core.base.DependencyCheckMixin),
        ),
    ]
