# Generated by Django 5.1.2 on 2025-09-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operational_data', '0004_operationaldatauploadstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationaldatauploadstatus',
            name='is_notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
