# Generated by Django 5.1.2 on 2025-09-16 04:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operational_data', '0005_operationaldatauploadstatus_is_notification_sent'),
        ('orders', '0027_orderstatusmapping_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationaldatauploadstatus',
            options={'ordering': ['queue_position', 'queued_at']},
        ),
        migrations.AddField(
            model_name='operationaldatauploadstatus',
            name='file_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationaldatauploadstatus',
            name='queue_position',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='operationaldatauploadstatus',
            name='queued_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='operationaldatauploadstatus',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('partial_success', 'Partial Success'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
        migrations.AddIndex(
            model_name='operationaldatauploadstatus',
            index=models.Index(fields=['status', 'queue_position'], name='operational_status_b47949_idx'),
        ),
        migrations.AddIndex(
            model_name='operationaldatauploadstatus',
            index=models.Index(fields=['upload_type', 'device_type', 'status'], name='operational_upload__feb1a5_idx'),
        ),
    ]
