# Generated by Django 5.1.2 on 2025-09-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operational_data', '0006_alter_operationaldatauploadstatus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationaldatauploadstatus',
            name='donwload_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
