# Generated by Django 5.1.2 on 2025-10-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operational_data', '0008_operationalnotice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operationalnotice',
            old_name='content',
            new_name='content1',
        ),
        migrations.AddField(
            model_name='operationalnotice',
            name='content2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationalnotice',
            name='content3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
