# Generated by Django 5.1.2 on 2025-10-14 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operational_data', '0009_rename_content_operationalnotice_content1_and_more'),
        ('user', '0024_country_group_currencyformat_group_dateformat_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationaldata',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AddField(
            model_name='operationaldatauploadstatus',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AddField(
            model_name='operationalnotice',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
    ]
