/**
 * FWS F4(통합지휘본부장·상황실) 화면 언어 사전 — 턴 AO · 차선 N2 단독 소유.
 *
 * `../copy.ts`(공용, F1/F2/F5 언어)는 이 턴에 고치지 않는다 — 지휘 화면
 * (`/fws/command`)의 문구는 전부 이 파일에서 온다(`copy_office.ts` 머리말과
 * 같은 규약 — 서버 스키마 값은 여기서도 바꾸지 않는다, 표시 이름만 둔다).
 */

export const FWS_COMMAND_COPY = {
  home: {
    title: '산불 지휘',
    eventIdLabel: '사건 번호',
    loadButton: '지휘 화면 불러오기',
    loadFailed: '지휘 화면을 불러오지 못했습니다',
  },
  screen: {
    incidentTitle: '사건 개요',
    stageTitle: '대응단계',
    resourcesTitle: '자원 배정',
    clockTitle: '대응 시계',
    evacuationTitle: '대피 현황',
    commandPostTitle: '지휘본부',
    noneYet: '아직 없음',
  },
  stage: {
    title: '대응단계 확정·상향 · 지휘권 이양',
    stageLabel: '단계',
    reasonPlaceholder: '확정·상향 사유',
    commandLevelLabel: '지휘 수준(선택)',
    confirmButton: '확정',
    confirmedNotice: '대응단계 확정됨',
  },
  commandPost: {
    title: '통합지휘본부 설치 선언',
    addressPlaceholder: '설치 위치(주소)',
    orgPlaceholder: '구성 기관',
    situationRoomPhonePlaceholder: '시도 상황실 전화(선택)',
    declareButton: '설치 선언',
    declaredNotice: '지휘본부 설치 선언됨',
  },
  aircraft: {
    title: '헬기 요청 승인 · 투하구역 지정',
    orgPlaceholder: '요청 기관',
    baseLabel: '기지',
    etaLabel: '도착 예정',
    approveButton: '승인',
    approvedNotice: '헬기 요청 승인됨(30분 시계 시작)',
  },
  evacuation: {
    title: '대피 명령 승인 · 해제',
    urgencyImmediate: '즉시',
    urgencyPrepare: '준비',
    approveButton: '승인',
    releaseButton: '해제',
    approvedNotice: '대피 명령 승인됨',
    releasedNotice: '대피 해제됨',
  },
  agency: {
    title: '소방·경찰·군 협조 요청',
    agencyFire: '소방',
    agencyPolice: '경찰',
    agencyMilitary: '군',
    recordButton: '요청 기록',
    recordedNotice: '협조 요청 기록됨',
  },
  fireDeclaration: {
    title: '주불 진화·진화완료 선언',
    mainOutButton: '주불 진화 선언',
    extinguishedButton: '진화완료 선언',
    mainOutNotice: '주불 진화 선언됨',
    extinguishedNotice: '진화완료 선언됨',
  },
  hourlyReport: {
    title: '상황보고 승인(매시간)',
    approveButton: '승인',
    approvedNotice: '상황보고 승인됨',
  },
  contacts: {
    title: '연락처(1클릭)',
    forestService: '산림청 상황실',
    provincialRoom: '시도 상황실',
    unregistered: '미등록',
  },
  night: {
    title: '야간 전환',
    sunsetPlaceholder: '일몰 시각(ISO)',
    setButton: '일몰 시각 기록',
    helicopterAvailable: '헬기 가능',
    helicopterUnavailable: '헬기 불가',
  },
  meeting: {
    title: '상황판단회의 기록',
    attendeesPlaceholder: '참석자',
    decisionPlaceholder: '결정 사항',
    basisPlaceholder: '근거',
    recordButton: '기록',
    recordedNotice: '회의 기록됨',
  },
  priority: {
    title: '동시 다발 사건 우선순위',
    refreshButton: '새로고침',
  },
  postReport: {
    title: '사후 보고서 1쪽',
    downloadPdfButton: 'PDF 내려받기',
    summaryButton: '요약 보기',
    damagePending: '집계 전',
    resourcesLabel: '자원',
    evacuationLabel: '대피',
    damageLabel: '피해',
    clockLabel: '대응 시계',
    downloadFailed: '보고서를 내려받지 못했습니다',
  },
  // ── 턴 AQ · 차선 N1 · 누르는 자리의 문구 ──────────────────────────────
  action: {
    failed: '처리하지 못했습니다',
    done: '반영됐습니다 — 최신 값으로 다시 불러왔습니다',
    noteLabel: '메모(선택)',
    history: '기록',
    latest: '최근',
    count: '건',
  },
  stageExtra: {
    currentLabel: '현재 단계',
    priorLabel: '이전 단계',
    levelMunicipal: '시군구',
    levelProvincial: '시도',
  },
  aircraftExtra: {
    latPlaceholder: '투하구역 위도',
    lngPlaceholder: '투하구역 경도',
    deadlineLabel: '30분 시계 마감',
    dropZoneLabel: '투하구역',
  },
  evacuationExtra: {
    releaseReasonPlaceholder: '해제 사유',
    statusLabel: '승인 상태',
    approvedAt: '승인 시각',
    releasedAt: '해제 시각',
    villagesLabel: '대상 마을',
  },
  agencyExtra: {
    detailPlaceholder: '요청 내용',
  },
  fireExtra: {
    extinguishedReasonPlaceholder: '진화완료 근거',
    responseStateLabel: '대응 상태',
  },
  hourlyExtra: {
    hourLabel: '보고 시각',
    reflectedLabel: '지휘본부 반영',
  },
  timeline: {
    title: '대응 시계',
    reported: '신고',
    acknowledged: '확인',
    helicopter: '헬기 투하',
    mainOut: '주불',
    extinguished: '진화완료',
    goldenExceeded: '골든타임 초과 — 사유를 남겨 주세요',
    goldenOk: '골든타임 이내 또는 사유 기록됨',
    reasonPlaceholder: '골든타임 초과 사유',
    reasonButton: '사유 기록',
    reasonLabel: '기록된 사유',
  },
  nightExtra: {
    sunsetLabel: '일몰 시각',
    nightNow: '야간',
    dayNow: '주간',
    nightOk: '야간 가능',
    nightNo: '야간 불가',
  },
  // ── 턴 AQ · 차선 N3 — F4-09 연락 · F4-13 위험도 목록 · F3-16 헬기 투하 시각 ──
  contactsExtra: {
    callButton: '전화 걸기',
  },
  priorityExtra: {
    riskLabel: '산불위험지수',
    riskPlaceholder: '위험지수(0~100)',
    recordButton: '지수 기록',
    openButton: '이 사건 열기',
    unscored: '지수 미기록',
    empty: '진행 중인 사건이 없습니다',
    loadFailed: '우선순위 목록을 불러오지 못했습니다',
  },
  heliDrop: {
    title: '헬기 물 투하 시각',
    droppedAtPlaceholder: '투하 시각(비우면 지금)',
    saveButton: '투하 시각 저장',
    firstLabel: '첫 투하',
    countLabel: '기록',
  },
  // ── 턴 AQ · 차선 W2C — F2-01 자원 배치판 · F2-05 지원 요청 배지 · F1-10 철수 지시 ──
  board: {
    title: '자원 배치판',
    refreshButton: '새로 보기',
    onStandbyLabel: '대기 인원',
    statusDay: '주간 대기',
    statusNight: '야간 5분대기조',
    statusOff: '근무 외',
    noPeople: '대기 상태를 등록한 대원이 없습니다',
    deployedLabel: '출동 중',
    releasedLabel: '철수·해제',
    locationLabel: '위치',
    supportTitle: '지원 요청',
    supportPersonnel: '인력',
    supportWater: '물',
    supportHelicopter: '헬기',
    supportHeavyEquipment: '중장비',
    noSupport: '들어온 지원 요청이 없습니다',
    loadFailed: '자원 배치판을 불러오지 못했습니다',
  },
  withdrawal: {
    title: '현장 안전 알림 — 대피 지시 · 철수',
    evacNotifiedLabel: '대피 지시 알림 도달',
    evacNotYet: '대피 명령 승인 전',
    peopleSuffix: '건',
    reasonPlaceholder: '철수 사유(필수)',
    orderButton: '철수 지시 보내기',
    ordersLabel: '철수 지시',
    none: '아직 없음',
  },
};
