# Generated by Django 5.1.2 on 2025-06-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('user', '0018_remove_currencyformat_placement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard',
            options={},
        ),
        migrations.AddField(
            model_name='dashboard',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_groups', to='user.usergroup'),
        ),
    ]
