# Generated by Django 5.1.14 on 2025-12-12 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_dashboard_group_dashboardpanel_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathersetting',
            name='is_surveillance_dashboard',
            field=models.BooleanField(default=False),
        ),
    ]
