"""
Định nghĩa các mapping giữa menu path và grid data.
File này chứa các mapping cần thiết để hệ thống permission hoạt động chính xác.
"""

from typing import Dict, List, Any, Tuple

# Các trường được thêm vào tất cả các grid
field_general_setting = [
    "pagination_size",
    "google_density",
    "show_filter_panel",
    "auto_size_column",
    "refresh_time",
]

# Định nghĩa các grid cho menu dựa trên model
model_grid_data = [
    {
        "name": "Drones & Robots",
        "path": "/device",
        "app": "devices",
        "model": "Device",
        "fields": [
            "name",
            "model",
            "image",
            "active",
            "status__name",
            "unit_id",
            "main_type__name",
            "manufacturer",
            "payload_capacity",
            "rtsp",
            "color",
            "terminal__name",
            "note",
            "in_use",
        ],
        "exclude_fields": [],
    },
    {
        "name": "Libraries",
        "path": "/library",
        "app": "devices",
        "model": "Library",
        "fields": [
            "name",
            "active",
            "created_on",
            "main_type__name",
            "in_use",
            "note",
            "model",
            "manufacturer",
        ],
        "exclude_fields": [],
    },
    {
        "name": "Equipment",
        "path": "/equipment",
        "app": "devices",
        "model": "Equipment",
        "fields": [
            "id",
            "name",
            "active",
            "created_on",
            "resolution",
            "frame_rate",
            "field_of_view",
            "weight",
            "image_stabilization",
            "note",
        ],
        "exclude_fields": [],
    },
    {
        "name": "Other Equipments",
        "path": "/other-equipments",
        "app": "devices",
        "model": "CameraType",
        "fields": [
            "id",
            "name",
            "active",
            "created_on",
            "resolution",
            "frame_rate",
            "field_of_view",
            "weight",
            "image_stabilization__name",
            "note",
        ],
        "exclude_fields": [],
    },
    {
        "name": "Packaging Specification",
        "path": "/packaging-specification",
        "app": "devices",
        "model": "PackagingSpecification",
        "fields": [
            "id",
            "name",
            "active",
            "created_on",
            "dimensions",
            "max_weight",
            "package_type__name",
            "water_proof",
            "fragile",
            "note",
        ],
        "exclude_fields": [],
    },
    {
        "name": "Packaging",
        "path": "/packaging",
        "app": "devices",
        "model": "PackagingSpecification",
        "fields": [
            "id",
            "name",
            "active",
            "created_on",
            "dimensions",
            "max_weight",
            "package_type__name",
            "water_proof",
            "fragile",
            "note",
        ],
        "exclude_fields": [],
    },
    {
        "name": "Terminals",
        "path": "/terminals",
        "app": "terminals",
        "model": "Terminal",
        "fields": [
            "code",
            "image",
            "name",
            "active",
            "created_on",
            "type_name",
            "function",
            "address",
            "latitude",
            "longitude",
            "note",
        ],
        "exclude_fields": [],
    },
    {
        "name": "Delivery Hubs",
        "path": "/delivery-hubs",
        "app": "terminals",
        "model": "Terminal",
        "fields": [
            "code",
            "image",
            "name",
            "active",
            "created_on",
            "function",
            "full_address",
            "manager_name",
            "note",
        ],
        "exclude_fields": [],
    },
    {
        "name": "Infrastructure",
        "path": "/infrastructure",
        "app": "terminals",
        "model": "Terminal",
        "fields": [
            "code",
            "name",
            "image",
            "active",
            "created_on",
            "terminal_purpose__name",
            "function",
            "purpose_type__name",
            "manufacturer",
            "note",
        ],
        "exclude_fields": [],
    },
    {
        "name": "Docking Station",
        "path": "/docking-stations",
        "app": "terminals",
        "model": "Terminal",
        "fields": [
            "code",
            "image",
            "name",
            "active",
            "created_on",
            "function",
            "address",
            "manager_name",
            "time_stops",
            "linked_terminal",
            "note",
        ],
        "exclude_fields": [],
    },
    {
        "name": "Routes",
        "path": "/routes",
        "app": "terminals",
        "model": "Routes",
        "fields": [
            "id",
            "name",
            "is_active",
            "in_use",
            "route_service__name",
            "created_on",
            "note",
            "total_stops",
            "start_point",
            "end_point",
            "total_distance",
            "estimated_time",
        ],
        "exclude_fields": [],
    },
    {
        "name": "Waybill Template",
        "path": "/waybill-template",
        "app": "terminals",
        "model": "WaybillTemplate",
        "fields": [
            "id",
            "name",
            "created_on",
            "is_enabled",
            "is_default",
            "usage_count",
        ],
        "exclude_fields": [],
    },
    {
        "name": "Report Template",
        "path": "/report-template",
        "app": "terminals",
        "model": "ReportTemplate",
        "fields": ["name", "created_on", "is_enabled", "is_default", "usage_count"],
        "exclude_fields": [],
    },
    {
        "name": "Delivery Operation",
        "path": "/delivery-operation",
        "app": "delivery",
        "model": "DeliveryOperation",
        "fields": [
            "order__order_code",
            "order__created_on",
            "created_on",
            "order__sender_name",
            "order__recipient_name",
            "created_by__first_name",
            "number_of_packages",
            "mapped_status",
        ],
        "exclude_fields": [],
    },
    {
        "name": "Delivery Inquiry",
        "path": "/delivery-inquiry",
        "app": "delivery",
        "model": "Order",
        "fields": ["order_code", "created_on",  "sender_name", "recipient_name","origin","destination","status__name","cancel_reason"],
        'exclude_fields': [],
        'order':1
    },
    {
        "name": "Verification",
        "path": "/delivery-operation",
        "app": "delivery",
        "tab": "/verification",
        "model": "DeliveryOperation",
        "fields": [
            "order__order_code",
            "order__created_on",
            "order__sender_name",
            "order__recipient_name",
            "creator",
            "number_of_packages",
            "mapped_status",
        ],
        "exclude_fields": [],
        "order": 2,
    },
    {
        "name": "Processing",
        "path": "/delivery-operation",
        "app": "delivery",
        "tab": "/processing",
        "model": "DeliveryOperation",
        "fields": [
            "order__order_code",
            "order__created_on",
            "origin",
            "destination",
            "order__sender_name",
            "order__recipient_name",
            "number_of_packages",
            "delivery_device",
            "mapped_status",
        ],
        "exclude_fields": [],
        "order": 3,
    },
    {
        "name": "Completed",
        "path": "/delivery-operation",
        "app": "delivery",
        "tab": "/completed",
        "model": "DeliveryOperation",
        "fields": [
            "order__order_code",
            "order__created_on",
            "order__sender_name",
            "order__recipient_name",
            "creator",
            "number_of_packages",
            "mapped_status",
        ],
        "exclude_fields": [],
        "order": 4,
    },
    {
        "name": "Returned",
        "path": "/delivery-operation",
        "app": "delivery",
        "tab": "/returned",
        "model": "DeliveryOperation",
        "fields": [
            "order__order_code",
            "order__created_on",
            "created_on",
            "order__sender_name",
            "order__recipient_name",
            "creator",
            "number_of_packages",
            "arrival_time",
            "returned_time",
            "processing_confirmation_time",
            "return_received_time",
            "mapped_status",
        ],
        "exclude_fields": [],
        "order": 5,
    },
    {
        "name": "Cancelled",
        "path": "/delivery-operation",
        "app": "delivery",
        "tab": "/cancelled",
        "model": "DeliveryOperation",
        "fields": [
            "order__order_code",
            "order__created_on",
            "cancel_time",
            "cancel_reason",
            "cancelled_by__name",
            "refunded_time",
            "order__sender_name",
            "order__recipient_name",
            "handler",
            "number_of_packages",
            "mapped_status",
        ],
        "exclude_fields": [],
        "order": 6,
    },
    {
        "name": "Operation Settings",
        "path": "/operation-settings",
        "app": "operation_settings",
        "model": "OperationSettings",
        "fields": [
            "menu__menu_name",
            "tab__name",
            "name",
            "is_active",
            "api_url",
            "modified_on",
            "modified_by__first_name",
        ],
        "exclude_fields": [],
    },
    {
        "name": "ETRI Order",
        "path": "/etri-order",
        "app": "delivery",
        "model": "Order",
        "fields": [
            "order__order_code",
            "order__created_on",
            "created_on",
            "order__sender_name",
            "order__recipient_name",
            "created_by__first_name",
            "number_of_packages",
            "mapped_status",
            "mapped_status_color",
            "order_identifier",
            "receipt_number",
            "handler",
            "tracking_number",
        ],
        "exclude_fields": [],
    },
    {
        "name": "ETRI Tracking",
        "path": "/etri-tracking",
        "app": "delivery",
        "model": "DeliveryOperation",
        "fields": [
            "order__order_code",
            "order__created_on",
            "created_on",
            "order__sender_name",
            "order__recipient_name",
            "created_by__first_name",
            "number_of_packages",
            "mapped_status",
            "mapped_status_color",
            "order_identifier",
            "receipt_number",
            "handler",
            "tracking_number",
        ],
        "exclude_fields": [],
    },
    {
        "name": "Checklist Setting",
        "path": "/checklist-setting",
        "app": "checklist_setting",
        "model": "ChecklistSetting",
        "fields": ["item_name", "category__name", "created_on"],
        "exclude_fields": [],
    },
    {
        "name": "Order Status",
        "path": "/order-status",
        "app": "orders",
        "model": "ExternalOrderStatus",
        "fields": ["name", "value", "created_on", "text_color", "background_color", "border_color"],
        "exclude_fields": [],
    },
    {
        "name": "Mapping Status",
        "path": "/mapping-status",
        "app": "orders",
        "model": "OrderStatusMapping",
        "fields": ["name",  "created_on"],
        "exclude_fields": [],   
    },
    {
        "name": "Operational Data",
        "path": "/operational-data",
        "app": "operational_data",
        "model": "DeliveryOperationItem",
        "fields": ["delivery_operation_code", "delivered_at", "route", "delivery_point", "item_type", "item_weight", "operation_log", "video"],
        "exclude_fields": [],   
    },
    {
        "name": "Flight Log Analysis",
        "path": "/flight-log-analysis",
        "app": "flight_log",
        "model": "FlightLog",
        "fields": ["route_code", "route_name", "start_time", "end_time", "total_distance", "start_point__name", "end_point__name", "drone_anomaly_prediction__name"],
        "exclude_fields": [],   
    },
    {
        "name": "Operational Notice",
        "path": "/operational-notice",
        "app": "operational_data",
        "model": "OperationalNotice",
        "fields": ["name", "active", "created_on"],
        "exclude_fields": [],   
    },
    {
        "name": "Survey Missions",
        "path": "/survey-mission",
        "app": "surveillance",
        "model": "SurveyMission",
        "fields": [
            "id",
            "name",
            "status__name",
            "is_active",
            "created_by_full_name",
            "created_on",
            "start_point",
            "end_point",
            "total_distance",
            "estimated_time",
            "note",
        ],
        "exclude_fields": [],   
    },
    {
        "name": "Surveillance Profiles",
        "path": "/survey-profile",
        "app": "surveillance",
        "model": "SurveillanceProfile",
        "fields": [
            "code",
            "name",
            "start_time",
            "estimated_end_time",
            "actual_end_time",
            "device_count",
            "created_on",
        ],
        "exclude_fields": [],
    },
    {
        "name": "Processing",
        "path": "/survey-profile",
        "app": "surveillance",
        "tab": "/processing",
        "model": "SurveillanceProfile",
        "fields": [
            "code",
            "name",
            "start_time",
            "estimated_end_time",
            "actual_end_time",
            "device_count",
            "created_on",
        ],
        "exclude_fields": [],
        "order": 1,
    },
    {
        "name": "Completed",
        "path": "/survey-profile",
        "app": "surveillance",
        "tab": "/completed",
        "model": "SurveillanceProfile",
        "fields": [
            "code",
            "name",
            "start_time",
            "estimated_end_time",
            "actual_end_time",
            "device_count",
            "created_on",
        ],
        "exclude_fields": [],
        "order": 2,
    },
    {
        "name": "Cancelled/Rejected",
        "path": "/survey-profile",
        "app": "surveillance",
        "tab": "/cancelled",
        "model": "SurveillanceProfile",
        "fields": [
            "code",
            "name",
            "start_time",
            "estimated_end_time",
            "actual_end_time",
            "device_count",
            "created_on",
        ],
        "exclude_fields": [],
        "order": 3,
    },
    {
        "name": "Delivery Report",
        "path": "/delivery-report",
        "app": "delivery",
        "model": "DeliveryOperation",
        "fields": [
            "order__order_code",
            "order__created_on",
            "order__sender_name",
            "order__recipient_name",
            "creator",
            "number_of_packages",
        ],
        "exclude_fields": [],
    },
    {
        "name": "Handover Management",
        "path": "/handover",
        "app": "handover",
        "model": "HandoverDocument",
        "fields": [
            "date",
            "status",
            "total_content",
            "created_time",
        ],
        "exclude_fields": [],
    },
    {
        "name": "Handover Management",
        "path": "/handover",
        "app": "handover",
        "tab": "/handover-management",
        "model": "HandoverDocument",
        "fields": [
            "date",
            "status",
            "total_content",
            "created_time",
        ],
        "exclude_fields": [],
        "order": 1,
    },
    {
        "name": "Notice Management",
        "path": "/handover",
        "app": "handover",
        "tab": "/notice-management",
        "model": "HandoverNotice",
        "fields": [
            "created_time",
            "content",
            "creator__username",
            "editor_names",
            "updated_time",
            "comment_count",
        ],
        "exclude_fields": [],
        "order": 2,
    },
    {
        "name": "Completed Notice",
        "path": "/handover",
        "app": "handover",
        "tab": "/completed-notice",
        "model": "HandoverNotice",
        "fields": [
            "created_time",
            "status",
            "content",
            "creator__username",
            "editor_names",
            "updated_time",
            "comment_count",
        ],
        "exclude_fields": [],
        "order": 3,
    },
    {
        "name": "Video Analysis",
        "path": "/data-analysis",
        "app": "surveillance",
        "model": "VideoAnalysis",
        "fields": [
            "video_path", 
            "drone_name", 
            "created_at", 
            "video_size"
        ],
        "exclude_fields": [],   
    },
]

# Mapping giữa menu và grid data
user_grid_management_data = [
    {
        "name": "Drone & Robot",
        "path": "/device",
        "fields": [
            "serial_number",
            "model",
            "image",
            "active",
            "unit_id",
            "main_type__name",
            "sub_type",
            "manufacturer",
            "payload_capacity",
            "communication",
            "rtsp",
            "color",
            "terminal",
            "note",
        ],
    },
    {
        "name": "Other Equipments",
        "path": "/other-equipments",
        "app": "devices",
        "model": "CameraType",
        "fields": [
            "id",
            "name",
            "active",
            "created_on",
            "resolution",
            "frame_rate",
            "field_of_view",
            "weight",
            "image_stabilization__name",
            "note",
        ],
        "exclude_fields": [],
    },
    {
        "name": "Packaging Specification",
        "path": "/packaging-specification",
        "fields": [
            "id",
            "name",
            "active",
            "created_on",
            "dimensions",
            "max_weight",
            "package_type__name",
            "water_proof",
            "fragile",
            "note",
        ],
    },
    {
        "name": "Packaging",
        "path": "/packaging",
        "fields": [
            "id",
            "name",
            "active",
            "created_on",
            "dimensions",
            "max_weight",
            "package_type__name",
            "water_proof",
            "fragile",
            "note",
        ],
    },
    {
        "name": "Routes",
        "path": "/routes",
        "fields": [
            "id",
            "name",
            "is_active",
            "created_on",
            "note",
            "total_stops",
            "start_point",
            "end_point",
            "total_distance",
            "estimated_time",
        ],
    },
    {
        "name": "Waybill Template",
        "path": "/waybill-template",
        "fields": [
            "id",
            "name",
            "created_on",
            "is_enabled",
            "is_default",
            "usage_count",
        ],
    },
    {
        "name": "Report Template",
        "path": "/report-template",
        "fields": ["name", "created_on", "is_enabled", "is_default", "usage_count"],
    },
    {
        "name": "Checklist Setting",
        "path": "/checklist-setting",
        "fields": ["item_name", "category__name", "created_on"],
    },
    {
        "name": "Operational Data",
        "path": "/operational-data",
        "app": "operational_data",
        "model": "DeliveryOperationItem",
        "fields": ["delivery_operation_code", "delivered_at", "route", "delivery_point", "item_type", "item_weight", "operation_log", "video"],
        "exclude_fields": [],   
    },
    {
        "name": "Flight Log Analysis",
        "path": "/flight-log-analysis",
        "app": "flight_log",
        "model": "FlightLog",
        "fields": ["route_code", "route_name", "start_time", "end_time", "total_distance", "start_point", "end_point", "drone_anomaly_prediction__name"],
        "exclude_fields": [],   
    },
    {
        "name": "Video Analysis",
        "path": "/data-analysis",
        "app": "surveillance",
        "model": "VideoAnalysis",
        "fields": ["video_path", "drone_name", "created_at", "video_size"],
        "exclude_fields": [],   
    },
]

# Mapping từ menu path (trong DB) đến grid id
# Key: đường dẫn menu trong DB (Menu.path)
# Value: tên grid tương ứng, dùng để xác định dữ liệu hiển thị
MENU_TO_GRID_MAPPING = {
    "/device": "Drone & Robot",
    "/equipment": "Equipment",
    "/other-equipments": "Other Equipments",
    "/packaging-specification": "Packaging Specification",
    "/packaging": "Packaging",
    "/terminals": "Terminals",
    "/routes": "Routes",
    "/waybill-template": "Waybill Template",
    "/delivery-operation": "Delivery Operation",
    "/report-template": "Report Template",
    "/checklist-setting": "Checklist Setting",
    "/operational-data": "Operational Data",
    "/flight-log-analysis": "Flight Log Analysis",
    "/survey-missions": "Survey Missions",
    "/surveillance/profile": "Surveillance Profiles",
    "/data-analysis": "Video Analysis",
}

# Mapping từ API endpoint đến menu path
# Key: Controller path (ví dụ: 'device', 'equipment', 'packaging-specification')
# Value: Menu path tương ứng trong DB
API_TO_MENU_MAPPING = {
    "/device": "/device",
    "/equipment": "/equipment",
    "/other-equipments": "/other-equipments",
    "/packaging-specification": "/packaging-specification",
    "/packaging": "/packaging",
    "/terminals": "/terminals",
    "/routes": "/routes",
    "/print-formats": "/waybill-template",
    "/report-template": "/report-template",
    "/checklist-setting": "/checklist-setting",
    "/operational-data": "/operational-data",
    "/flight-log-analysis": "/flight-log-analysis",
    "/survey-missions": "/survey-missions",
    "/surveillance-profiles": "/surveillance/profile",
    "/operation-settings": "/operation-settings",
}

# Mapping từ action đến permission type
# Key: Action name trong path_permission
# Value: Tên field trong RoleMenu/RoleTab (permit_*)
ACTION_TO_PERMISSION_MAPPING = {
    "read": "permit_read",
    "create": "permit_create",
    "update": "permit_update",
    "delete": "permit_delete",
    "export": "permit_export",
    "import": "permit_import",
}

# Mapping chi tiết giữa controller method và action cụ thể
# Key: Regex pattern của method name
# Value: Action tương ứng
METHOD_TO_ACTION_MAPPING = {
    r"^get_": "read",
    r"^list_": "read",
    r"^search_": "read",
    r"^find_": "read",
    r"^view_": "read",
    r"^create_": "create",
    r"^add_": "create",
    r"^update_": "update",
    r"^edit_": "update",
    r"^change_": "update",
    r"^delete_": "delete",
    r"^remove_": "delete",
    r"^export_": "export",
    r"^import_": "import",
}
