# Generated by Django 5.1.2 on 2025-04-10 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightperformance',
            name='wind_resistance',
        ),
        migrations.AlterField(
            model_name='camera',
            name='image_stabilization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_stabilization', to='devices.imagestabilization'),
        ),
        migrations.AlterField(
            model_name='device',
            name='main_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_type', to='devices.devicetype'),
        ),
        migrations.AlterField(
            model_name='navigationcontrol',
            name='imu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imu', to='devices.imu'),
        ),
        migrations.AlterField(
            model_name='propulsionsystem',
            name='battery_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battery_type', to='devices.batterytype'),
        ),
        migrations.AlterField(
            model_name='propulsionsystem',
            name='motor_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motor_type', to='devices.motortype'),
        ),
    ]
