# Generated by Django 5.1.2 on 2025-04-10 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_remove_flightperformance_wind_resistance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagingspecification',
            name='device',
        ),
        migrations.RemoveField(
            model_name='propulsionsystem',
            name='charging_time',
        ),
        migrations.RemoveField(
            model_name='propulsionsystem',
            name='flight_time',
        ),
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-modified_on'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='packagingspecification',
            name='package_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_specification', to='devices.packagetype'),
        ),
    ]
