# Generated by Django 5.1.2 on 2025-04-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_remove_packagingspecification_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceinformation',
            name='current_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceinformation',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceinformation',
            name='insurance_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='insuranceinformation',
            name='insurance_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceinformation',
            name='policy_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceinformation',
            name='validity_period',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturerinformation',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturerinformation',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturerinformation',
            name='model_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturerinformation',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturerinformation',
            name='production_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturerinformation',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='safetyfeature',
            name='dual_battery',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='safetyfeature',
            name='dual_gps',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='safetyfeature',
            name='dual_imu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='safetyfeature',
            name='emergency_braking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='safetyfeature',
            name='emergency_parachute',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='safetyfeature',
            name='lidar_mapping',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='safetyfeature',
            name='obstacle_detection_360',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='safetyfeature',
            name='return_to_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='safetyfeature',
            name='stereo_cameras',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='battery_status_monitoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='gps_position_tracking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='realtime_flight_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='system_health_monitoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='video_streaming',
            field=models.BooleanField(default=False),
        ),
    ]
