# Generated by Django 5.1.2 on 2025-04-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_alter_insuranceinformation_current_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batterytype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='night_vision',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='camera',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='thermal_imaging',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='sub_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='devicegnss',
            name='config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicegnss',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='devicegnss',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deviceprotocol',
            name='config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deviceprotocol',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gnsssystem',
            name='accuracy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='gnsssystem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gnsssystem',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gnsssystem',
            name='update_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gnsssystem',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imagestabilization',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motortype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='navigationcontrol',
            name='barometric_altimeter',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='packagetype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propulsionsystem',
            name='number_of_motors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensorsuite',
            name='ads_b_receiver',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sensorsuite',
            name='ais',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sensorsuite',
            name='chemical_sensor_array',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sensorsuite',
            name='lidar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sensorsuite',
            name='optical_flow_sensor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sensorsuite',
            name='radiation_detector',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sensorsuite',
            name='rf_signal_detector',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sensorsuite',
            name='ultrasonic_sensors',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sensorsuite',
            name='weather_sensors',
            field=models.BooleanField(default=False),
        ),
    ]
