# Generated by Django 5.1.2 on 2025-04-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_alter_batterytype_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargocompartments',
            name='quick_release',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cargocompartments',
            name='secure_locking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cargocompartments',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cargocompartments',
            name='temperature_control',
            field=models.BooleanField(default=False),
        ),
    ]
