# Generated by Django 5.1.2 on 2025-04-10 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_alter_cargocompartments_quick_release_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagingspecificationdevice',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_specification_device', to='devices.device'),
        ),
    ]
