# Generated by Django 5.1.2 on 2025-04-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_alter_packagingspecificationdevice_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='batterytype',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='motortype',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='packagetype',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
