# Generated by Django 5.1.2 on 2025-04-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_batterytype_code_motortype_code_packagetype_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagingspecification',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='packagingspecification',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
