# Generated by Django 5.1.2 on 2025-04-14 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_packagingspecification_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagingspecification',
            name='package_type',
        ),
    ]
