# Generated by Django 5.1.2 on 2025-04-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_remove_packagingspecification_package_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagingspecification',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
