# Generated by Django 5.1.2 on 2025-04-14 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_alter_packagingspecification_code'),
        ('file_management', '0004_alter_usermediafile_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_avatar', to='file_management.usermediafile'),
        ),
    ]
