# Generated by Django 5.1.2 on 2025-04-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0013_device_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturerinformation',
            name='current_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='manufacturerinformation',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='manufacturerinformation',
            name='insurance_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='manufacturerinformation',
            name='policy_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='manufacturerinformation',
            name='validity_period',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
