# Generated by Django 5.1.2 on 2025-04-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0014_manufacturerinformation_current_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='model',
        ),
        migrations.AddField(
            model_name='device',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
