# Generated by Django 5.1.2 on 2025-04-18 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0015_remove_device_model_device_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorsuite',
            name='gnss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_suite_gnss', to='devices.gnsssystem'),
        ),
    ]
