# Generated by Django 5.1.2 on 2025-04-21 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0017_remove_packagingspecificationdevice_package_and_more'),
        ('user', '0006_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='type',
        ),
        migrations.AddField(
            model_name='camera',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packagingspecification',
            name='fragile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='packagingspecification',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packagingspecification',
            name='package_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packaging_specification', to='devices.packagetype'),
        ),
        migrations.AddField(
            model_name='packagingspecification',
            name='water_proof',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='manufacturerinformation',
            name='country_of_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_information', to='user.country'),
        ),
        migrations.AlterField(
            model_name='surveillancesystems',
            name='config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surveillancesystems',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='surveillancesystems',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
