# Generated by Django 5.1.2 on 2025-04-23 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0019_alter_packagingoptionspecification_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationcontrol',
            name='imu',
        ),
    ]
