# Generated by Django 5.1.2 on 2025-04-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0020_remove_navigationcontrol_imu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuranceinformation',
            name='validity_period',
        ),
        migrations.RemoveField(
            model_name='manufacturerinformation',
            name='validity_period',
        ),
        migrations.AddField(
            model_name='insuranceinformation',
            name='validity_period_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insuranceinformation',
            name='validity_period_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manufacturerinformation',
            name='validity_period_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manufacturerinformation',
            name='validity_period_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
