# Generated by Django 5.1.2 on 2025-04-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0021_remove_insuranceinformation_validity_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagingspecification',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
