# Generated by Django 5.1.2 on 2025-05-13 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0022_packagingspecification_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='unit_id',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
