# Generated by Django 5.1.2 on 2025-05-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0024_alter_device_options_device_group'),
        ('user', '0013_alter_userprofilelink_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='group',
        ),
        migrations.AddField(
            model_name='device',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_groups', to='user.usergroup'),
        ),
    ]
