# Generated by Django 5.1.2 on 2025-06-02 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0026_library_device_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargocompartments',
            name='library',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargo_compartments', to='devices.library'),
        ),
        migrations.AddField(
            model_name='devicecamera',
            name='library',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_cameras', to='devices.library'),
        ),
        migrations.AddField(
            model_name='devicegnss',
            name='library',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_gnss', to='devices.library'),
        ),
        migrations.AddField(
            model_name='deviceprotocol',
            name='library',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_protocols', to='devices.library'),
        ),
        migrations.AddField(
            model_name='dimensionsandweight',
            name='library',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dimensions_and_weight', to='devices.library'),
        ),
        migrations.AddField(
            model_name='environmentalspecification',
            name='library',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='environmental_specification', to='devices.library'),
        ),
        migrations.AddField(
            model_name='flightperformance',
            name='library',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_performance', to='devices.library'),
        ),
        migrations.AddField(
            model_name='insuranceinformation',
            name='library',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_information', to='devices.library'),
        ),
        migrations.AddField(
            model_name='manufacturerinformation',
            name='library',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_information', to='devices.library'),
        ),
        migrations.AddField(
            model_name='navigationcontrol',
            name='library',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navigation_control', to='devices.library'),
        ),
        migrations.AddField(
            model_name='packagingspecificationdevice',
            name='library',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packaging_specification_device', to='devices.library'),
        ),
        migrations.AddField(
            model_name='propulsionsystem',
            name='library',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propulsion_system', to='devices.library'),
        ),
        migrations.AddField(
            model_name='radiocommunication',
            name='library',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radio_communication', to='devices.library'),
        ),
        migrations.AddField(
            model_name='safetyfeature',
            name='library',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='safety_feature', to='devices.library'),
        ),
        migrations.AddField(
            model_name='sensorsuite',
            name='library',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_suite', to='devices.library'),
        ),
        migrations.AddField(
            model_name='telemetry',
            name='library',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='devices.library'),
        ),
    ]
