# Generated by Django 5.1.2 on 2025-06-02 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0027_cargocompartments_library_devicecamera_library_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicegnss',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_gnss', to='devices.device'),
        ),
        migrations.AlterField(
            model_name='deviceprotocol',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_protocols', to='devices.device'),
        ),
        migrations.AlterField(
            model_name='environmentalspecification',
            name='device',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='environmental_specification', to='devices.device'),
        ),
        migrations.AlterField(
            model_name='insuranceinformation',
            name='device',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_information', to='devices.device'),
        ),
        migrations.AlterField(
            model_name='manufacturerinformation',
            name='device',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_information', to='devices.device'),
        ),
        migrations.AlterField(
            model_name='navigationcontrol',
            name='device',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navigation_control', to='devices.device'),
        ),
        migrations.AlterField(
            model_name='radiocommunication',
            name='device',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radio_communication', to='devices.device'),
        ),
        migrations.AlterField(
            model_name='safetyfeature',
            name='device',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='safety_feature', to='devices.device'),
        ),
        migrations.AlterField(
            model_name='sensorsuite',
            name='device',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_suite', to='devices.device'),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='device',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='devices.device'),
        ),
    ]
