# Generated by Django 5.1.2 on 2025-06-02 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0028_alter_devicegnss_device_alter_deviceprotocol_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicegnss',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='library_gnss', to='devices.library'),
        ),
    ]
