# Generated by Django 5.1.2 on 2025-06-02 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0029_alter_devicegnss_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargocompartments',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargo_compartments', to='devices.library'),
        ),
    ]
