# Generated by Django 5.1.2 on 2025-06-02 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0031_alter_cargocompartments_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecamera',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_cameras', to='devices.device'),
        ),
        migrations.AlterField(
            model_name='devicecamera',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='library_cameras', to='devices.library'),
        ),
    ]
