# Generated by Django 5.1.2 on 2025-06-02 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0032_alter_devicecamera_device_alter_devicecamera_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceprotocol',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='library_protocols', to='devices.library'),
        ),
    ]
