# Generated by Django 5.1.2 on 2025-06-03 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0033_alter_deviceprotocol_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propulsionsystem',
            name='device',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propulsion_system', to='devices.device'),
        ),
    ]
