# Generated by Django 5.1.2 on 2025-06-03 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0034_alter_propulsionsystem_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightperformance',
            name='device',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_performance', to='devices.device'),
        ),
    ]
