# Generated by Django 5.1.2 on 2025-06-04 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0035_alter_flightperformance_device'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'ordering': ['-modified_on']},
        ),
        migrations.RemoveField(
            model_name='library',
            name='groups',
        ),
    ]
