# Generated by Django 5.1.2 on 2025-06-04 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0036_alter_library_options_remove_library_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimensionsandweight',
            name='device',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dimensions_and_weight', to='devices.device'),
        ),
    ]
