# Generated by Django 5.1.2 on 2025-06-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0037_alter_dimensionsandweight_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
