# Generated by Django 5.1.2 on 2025-06-04 07:58

import core.multilanguage.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_statuses(apps, schema_editor):
    """Create default DeviceStatus records"""
    DeviceStatus = apps.get_model('devices', 'DeviceStatus')
    
    # Create default statuses
    default_statuses = [
        {'code': 'available', 'name': 'Available', 'description': 'Available'},
        {'code': 'on_mission', 'name': 'On mission', 'description': 'On mission'},
        {'code': 'operational', 'name': 'Operational', 'description': 'Operational'},
        {'code': 'maintenance', 'name': 'Maintenance', 'description': 'Under maintenance'},
        {'code': 'inactive', 'name': 'Inactive', 'description': 'Inactive'},
        {'code': 'retired', 'name': 'Retired', 'description': 'Retired'},
    ]
    
    for status_data in default_statuses:
        DeviceStatus.objects.get_or_create(code=status_data['code'], defaults=status_data)


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0038_library_is_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Create the DeviceStatus model
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(default='Available', max_length=255)),
                ('code', models.CharField(choices=[('available', 'Available'), ('on_mission', 'On mission'), ('operational', 'Operational'), ('maintenance', 'Maintenance'), ('inactive', 'Inactive'), ('retired', 'Retired')], default='available', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-modified_on'],
                'abstract': False,
            },
            bases=(models.Model, core.multilanguage.models.MultiLanguageContentMixin),
        ),
        
        # Create default DeviceStatus records
        migrations.RunPython(create_default_statuses, migrations.RunPython.noop),
    ] 