# Generated by Django 5.1.2 on 2025-06-04 08:30

import django.db.models.deletion
from django.db import migrations, models


def migrate_device_status_data(apps, schema_editor):
    """Migrate existing Device status CharField values to ForeignKey references"""
    Device = apps.get_model('devices', 'Device')
    DeviceStatus = apps.get_model('devices', 'DeviceStatus')
    
    # Mapping of old string values to new status codes
    status_mapping = {
        'operational': 'operational',
        'active': 'available',
        'inactive': 'inactive', 
        'maintenance': 'maintenance',
        'retired': 'retired',
        'available': 'available',
        'on_mission': 'on_mission',
        '': 'available',  # Handle empty strings
        None: 'available',  # Handle null values
    }
    
    # Get default status for unmapped values
    default_status = DeviceStatus.objects.filter(code='available').first()
    
    for device in Device.objects.all():
        old_status = getattr(device, 'status', None)
        if old_status:
            old_status = str(old_status).lower().strip()
        
        # Map the old status to new status code
        status_code = status_mapping.get(old_status, 'available')
        
        try:
            new_status = DeviceStatus.objects.get(code=status_code)
            # Store the new status ID in the new field
            device.new_status_id = new_status.id
            device.save(update_fields=['new_status_id'])
        except DeviceStatus.DoesNotExist:
            # Fallback to default status
            if default_status:
                device.new_status_id = default_status.id
                device.save(update_fields=['new_status_id'])


def reverse_migrate_device_status_data(apps, schema_editor):
    """Reverse migration - convert ForeignKey values back to CharField"""
    Device = apps.get_model('devices', 'Device')
    DeviceStatus = apps.get_model('devices', 'DeviceStatus')
    
    for device in Device.objects.all():
        if hasattr(device, 'new_status_id') and device.new_status_id:
            try:
                status = DeviceStatus.objects.get(id=device.new_status_id)
                device.status = status.code
                device.save(update_fields=['status'])
            except DeviceStatus.DoesNotExist:
                device.status = 'available'
                device.save(update_fields=['status'])


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0039_create_devicestatus_model'),
    ]

    operations = [
        # Add temporary field to store the new status ID
        migrations.AddField(
            model_name='device',
            name='new_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_devices', to='devices.devicestatus'),
        ),
        
        # Migrate the data
        migrations.RunPython(migrate_device_status_data, reverse_migrate_device_status_data),
        
        # Remove the old CharField status field
        migrations.RemoveField(
            model_name='device',
            name='status',
        ),
        
        # Rename new_status to status
        migrations.RenameField(
            model_name='device',
            old_name='new_status',
            new_name='status',
        ),
        
        # Update the related_name to the final one
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='devices.devicestatus'),
        ),
    ] 