# Generated by Django 5.1.2 on 2025-06-04 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0040_migrate_device_status_to_foreignkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagingspecificationdevice',
            name='library',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packaging_specification_library', to='devices.library'),
        ),
    ]
