# Generated by Django 5.1.2 on 2025-06-05 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0041_alter_packagingspecificationdevice_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagingspecificationdevice',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packaging_specification_library', to='devices.library'),
        ),
    ]
