# Generated by Django 5.1.2 on 2025-07-22 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0042_alter_packagingspecificationdevice_library'),
        ('terminals', '0023_terminal_terminal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='terminals.terminal'),
        ),
    ]
