# Generated by Django 5.1.2 on 2025-07-30 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0043_device_terminal'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
