# Generated by Django 5.1.2 on 2025-08-21 07:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('devices', '0044_device_color'),
        ('file_management', '0014_alter_usermediafile_file_url'),
        ('terminals', '0043_alter_routes_two_way'),
        ('user', '0022_coreuser_is_rejected_coreuser_reject_on_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicestatus',
            options={},
        ),
        migrations.AlterModelOptions(
            name='devicetype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='packagingoption',
            options={},
        ),
        migrations.AlterModelOptions(
            name='packagingoptionspecification',
            options={},
        ),
        migrations.AlterModelOptions(
            name='packagingspecificationdevice',
            options={},
        ),
        migrations.AddField(
            model_name='measurement',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='devicestatus',
            name='code',
            field=models.CharField(choices=[('available', 'Available'), ('on_mission', 'On mission'), ('operational', 'Operational'), ('maintenance', 'Maintenance'), ('inactive', 'Inactive'), ('retired', 'Retired')], db_index=True, default='available', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='measurement_type',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='packagingoption',
            name='order',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='packagingspecification',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='packagingspecification',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['status', 'active'], name='devices_dev_status__875e18_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['main_type', 'active'], name='devices_dev_main_ty_148426_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['terminal', 'active'], name='devices_dev_termina_8759e3_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['status', 'main_type', 'active'], name='devices_dev_status__a84951_idx'),
        ),
        migrations.AddIndex(
            model_name='devicestatus',
            index=models.Index(fields=['code'], name='devices_dev_code_60532a_idx'),
        ),
        migrations.AddIndex(
            model_name='devicetype',
            index=models.Index(fields=['name'], name='devices_dev_name_a4d620_idx'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['measurement_type'], name='devices_mea_measure_1ad5da_idx'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['content_type', 'object_id'], name='devices_mea_content_0fd5e1_idx'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['measurement_type', 'content_type', 'object_id'], name='devices_mea_measure_3624b2_idx'),
        ),
        migrations.AddIndex(
            model_name='packagingoption',
            index=models.Index(fields=['order'], name='devices_pac_order_493454_idx'),
        ),
        migrations.AddIndex(
            model_name='packagingoptionspecification',
            index=models.Index(fields=['option'], name='devices_pac_option__2759a2_idx'),
        ),
        migrations.AddIndex(
            model_name='packagingoptionspecification',
            index=models.Index(fields=['package'], name='devices_pac_package_f35b68_idx'),
        ),
        migrations.AddIndex(
            model_name='packagingoptionspecification',
            index=models.Index(fields=['option', 'package'], name='devices_pac_option__93104c_idx'),
        ),
        migrations.AddIndex(
            model_name='packagingspecification',
            index=models.Index(fields=['code'], name='devices_pac_code_1d182e_idx'),
        ),
        migrations.AddIndex(
            model_name='packagingspecification',
            index=models.Index(fields=['active'], name='devices_pac_active_c3c1ca_idx'),
        ),
        migrations.AddIndex(
            model_name='packagingspecification',
            index=models.Index(fields=['code', 'active'], name='devices_pac_code_047c6f_idx'),
        ),
        migrations.AddIndex(
            model_name='packagingspecificationdevice',
            index=models.Index(fields=['device'], name='devices_pac_device__b16b94_idx'),
        ),
        migrations.AddIndex(
            model_name='packagingspecificationdevice',
            index=models.Index(fields=['option'], name='devices_pac_option__f229ba_idx'),
        ),
        migrations.AddIndex(
            model_name='packagingspecificationdevice',
            index=models.Index(fields=['device', 'option'], name='devices_pac_device__474d79_idx'),
        ),
    ]
