# Generated by Django 5.1.2 on 2025-08-21 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0045_alter_devicestatus_options_alter_devicetype_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='unit',
        ),
    ]
