# Generated by Django 5.1.2 on 2025-08-26 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0046_remove_measurement_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='approve_flight_now',
            field=models.BooleanField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
