# Generated by Django 5.1.2 on 2025-08-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0047_device_approve_flight_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='on_approve_flight',
            field=models.BooleanField(blank=True, db_index=True, default=False, null=True),
        ),
    ]
