# Generated by Django 5.1.2 on 2025-08-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0048_device_on_approve_flight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicestatus',
            name='code',
            field=models.CharField(choices=[('available', 'Available'), ('on_mission', 'On mission'), ('operational', 'Operational'), ('maintenance', 'Maintenance'), ('inactive', 'Inactive'), ('retired', 'Retired'), ('warning', 'Warning')], db_index=True, default='available', max_length=255, unique=True),
        ),
    ]
