# Generated by Django 5.1.2 on 2025-10-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0049_alter_devicestatus_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagingspecification',
            name='water_proof',
            field=models.CharField(blank=True, null=True),
        ),
    ]
