# Generated by Django 5.1.2 on 2025-10-14 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0050_alter_packagingspecification_water_proof'),
        ('user', '0024_country_group_currencyformat_group_dateformat_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batterytype',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AddField(
            model_name='cameratype',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AddField(
            model_name='cargocompartments',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AddField(
            model_name='device',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AddField(
            model_name='devicecamera',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AddField(
            model_name='devicegnss',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AddField(
            model_name='deviceprotocol',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AddField(
            model_name='devicestatus',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AddField(
            model_name='dimensionsandweight',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AddField(
            model_name='environmentalspecification',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AddField(
            model_name='flightperformance',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AddField(
            model_name='gnsssystem',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AddField(
            model_name='imagestabilization',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AddField(
            model_name='imu',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AddField(
            model_name='insuranceinformation',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AddField(
            model_name='library',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AddField(
            model_name='manufacturerinformation',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AddField(
            model_name='motortype',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AddField(
            model_name='navigationcontrol',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AddField(
            model_name='packagetype',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AddField(
            model_name='packagingoption',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AddField(
            model_name='packagingoptionspecification',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AddField(
            model_name='packagingspecification',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AddField(
            model_name='packagingspecificationdevice',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AddField(
            model_name='propulsionsystem',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AddField(
            model_name='radiocommunication',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AddField(
            model_name='safetyfeature',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AddField(
            model_name='sensorsuite',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AddField(
            model_name='telemetry',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AddField(
            model_name='unit',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
    ]
