# Generated by Django 5.1.2 on 2025-10-15 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0051_batterytype_group_cameratype_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='groups',
        ),
    ]
