# Generated by Django 5.1.2 on 2025-11-20 01:23

import core.base
import core.multilanguage.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0052_remove_device_groups'),
        ('user', '0024_country_group_currencyformat_group_dateformat_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicestatus',
            name='code',
            field=models.CharField(choices=[('available', 'Available'), ('on_mission', 'On mission'), ('operational', 'Operational'), ('maintenance', 'Maintenance'), ('inactive', 'Inactive'), ('retired', 'Retired'), ('warning', 'Warning'), ('return', 'Return')], db_index=True, default='available', max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='FrameClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('code', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0, help_text='Thứ tự hiển thị')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
            bases=(models.Model, core.multilanguage.models.MultiLanguageContentMixin, core.base.DependencyCheckMixin),
        ),
        migrations.AddField(
            model_name='dimensionsandweight',
            name='frame_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dimensions_and_weights', to='devices.frameclass'),
        ),
        migrations.CreateModel(
            name='FrameType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('code', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0, help_text='Thứ tự hiển thị')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
            bases=(models.Model, core.multilanguage.models.MultiLanguageContentMixin, core.base.DependencyCheckMixin),
        ),
        migrations.AddField(
            model_name='dimensionsandweight',
            name='frame_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dimensions_and_weights', to='devices.frametype'),
        ),
        migrations.AddIndex(
            model_name='frameclass',
            index=models.Index(fields=['name'], name='devices_fra_name_177a63_idx'),
        ),
        migrations.AddIndex(
            model_name='frameclass',
            index=models.Index(fields=['code'], name='devices_fra_code_c75a39_idx'),
        ),
        migrations.AddIndex(
            model_name='frameclass',
            index=models.Index(fields=['order'], name='devices_fra_order_03fdf5_idx'),
        ),
        migrations.AddIndex(
            model_name='frametype',
            index=models.Index(fields=['name'], name='devices_fra_name_70ead0_idx'),
        ),
        migrations.AddIndex(
            model_name='frametype',
            index=models.Index(fields=['code'], name='devices_fra_code_2b4f32_idx'),
        ),
        migrations.AddIndex(
            model_name='frametype',
            index=models.Index(fields=['order'], name='devices_fra_order_13eb5c_idx'),
        ),
    ]
