# Generated by Django 5.1.2 on 2025-11-24 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0052_remove_device_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='registration_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
