# Generated by Django 5.1.2 on 2025-11-24 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0053_alter_devicestatus_code_frameclass_and_more'),
        ('devices', '0053_device_registration_number'),
    ]

    operations = [
    ]
