# Generated by Django 5.1.2 on 2025-11-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0054_merge_20251124_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='registration_number',
        ),
        migrations.AddField(
            model_name='manufacturerinformation',
            name='registration_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
