# Generated by Django 5.1.2 on 2025-06-10 10:05

import core.multilanguage.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0006_delete_menutranslation'),
        ('user', '0014_profile_coreuser_is_account_lock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(help_text='Name of this operation setting', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('api_url', models.URLField(max_length=1000)),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')], default='GET', max_length=10)),
                ('api_params', models.JSONField(blank=True, help_text='API parameters in JSON format', null=True)),
                ('expected_response', models.JSONField(blank=True, help_text='Expected response structure in JSON format', null=True)),
                ('timeout_seconds', models.IntegerField(default=30, help_text='API timeout in seconds')),
                ('retry_count', models.IntegerField(default=3, help_text='Number of retries on failure')),
                ('description', models.TextField(blank=True, help_text='Description of this operation setting', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('last_tested_on', models.DateTimeField(blank=True, null=True)),
                ('last_test_status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(help_text='Related user group from core user system', on_delete=django.db.models.deletion.CASCADE, related_name='operation_settings', to='user.usergroup')),
                ('groups', models.ManyToManyField(blank=True, related_name='%(class)s_groups', to='user.usergroup')),
                ('menu', models.ForeignKey(help_text='Related menu from core menu system', on_delete=django.db.models.deletion.CASCADE, related_name='operation_settings', to='menu.menu')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('tab', models.ForeignKey(blank=True, help_text='Related tab from core menu system (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation_settings', to='menu.tab')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_operation_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operation Setting',
                'verbose_name_plural': 'Operation Settings',
                'ordering': ['menu__menu_name', 'tab__name', 'name'],
                'unique_together': {('menu', 'tab', 'name', 'group')},
            },
            bases=(models.Model, core.multilanguage.models.MultiLanguageContentMixin),
        ),
    ]
