# Generated by Django 5.1.2 on 2025-06-11 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation_settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationsettings',
            name='updated_by',
        ),
    ]
