# Generated by Django 5.1.2 on 2025-06-11 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_delete_menutranslation'),
        ('operation_settings', '0002_remove_operationsettings_updated_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='operationsettings',
            unique_together={('menu', 'tab', 'name')},
        ),
        migrations.RemoveField(
            model_name='operationsettings',
            name='group',
        ),
    ]
