# Generated by Django 5.1.2 on 2025-06-11 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation_settings', '0003_alter_operationsettings_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='operationsettings',
            unique_together=set(),
        ),
    ]
