# Generated by Django 5.1.2 on 2025-06-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_settings', '0004_alter_operationsettings_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsettings',
            name='receive_data',
            field=models.BooleanField(default=False, help_text='Receive data from API'),
        ),
        migrations.AddField(
            model_name='operationsettings',
            name='send_data',
            field=models.BooleanField(default=False, help_text='Send data to API'),
        ),
    ]
