# Generated by Django 5.1.2 on 2025-06-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_settings', '0005_operationsettings_receive_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationsettings',
            name='name',
            field=models.CharField(blank=True, help_text='Name of this operation setting', max_length=100, null=True),
        ),
    ]
