# Generated by Django 5.1.2 on 2025-06-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_settings', '0006_alter_operationsettings_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationsettings',
            name='api_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='operationsettings',
            name='http_method',
            field=models.CharField(blank=True, choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')], default='GET', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='operationsettings',
            name='retry_count',
            field=models.IntegerField(blank=True, default=3, help_text='Number of retries on failure', null=True),
        ),
        migrations.AlterField(
            model_name='operationsettings',
            name='timeout_seconds',
            field=models.IntegerField(blank=True, default=30, help_text='API timeout in seconds', null=True),
        ),
    ]
