# Generated by Django 5.1.2 on 2025-06-12 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_delete_menutranslation'),
        ('operation_settings', '0007_alter_operationsettings_api_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationsettings',
            name='menu',
            field=models.ForeignKey(blank=True, default=None, help_text='Related menu from core menu system', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation_settings', to='menu.menu'),
        ),
        migrations.AlterField(
            model_name='operationsettings',
            name='tab',
            field=models.ForeignKey(blank=True, default=None, help_text='Related tab from core menu system (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation_settings', to='menu.tab'),
        ),
    ]
