# Generated by Django 5.1.2 on 2025-06-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_settings', '0008_alter_operationsettings_menu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsettings',
            name='body_params',
            field=models.JSONField(blank=True, help_text='Body parameters in JSON format', null=True),
        ),
    ]
