# Generated by Django 5.1.2 on 2025-10-17 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation_settings', '0010_operationsettings_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationsettings',
            name='groups',
        ),
    ]
