# Generated by Django 5.1.2 on 2025-09-08 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='partner',
            table=None,
        ),
    ]
