# Generated by Django 5.1.2 on 2025-09-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_alter_partner_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
