# Generated by Django 5.1.2 on 2025-09-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_alter_partner_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='expired_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
