# Generated by Django 5.1.2 on 2025-09-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_partner_expired_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='service_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
