BEGIN;
--
-- Add field address_source to streammonitor
--
ALTER TABLE "stream_monitors_streammonitor" ADD COLUMN "address_source" varchar(16) DEFAULT 'unset' NOT NULL;
ALTER TABLE "stream_monitors_streammonitor" ALTER COLUMN "address_source" DROP DEFAULT;
--
-- Add field install_address to streammonitor
--
ALTER TABLE "stream_monitors_streammonitor" ADD COLUMN "install_address" varchar(255) NULL;
--
-- Add field install_address_detail to streammonitor
--
ALTER TABLE "stream_monitors_streammonitor" ADD COLUMN "install_address_detail" varchar(255) NULL;
--
-- Create model ThresholdChange
--
CREATE TABLE "k5_threshold_change" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "deleted" timestamp with time zone NULL, "deleted_by_cascade" boolean NOT NULL, "created_on" timestamp with time zone NULL, "modified_on" timestamp with time zone NULL, "key" varchar(64) NOT NULL, "scope_level" varchar(8) NOT NULL, "camera_label" varchar(255) NOT NULL, "old_value" varchar(64) NULL, "new_value" varchar(64) NULL, "reason" varchar(255) NOT NULL, "changed_at" timestamp with time zone NOT NULL, "camera_id" bigint NULL, "changed_by_id" bigint NULL, "created_by_id" bigint NULL, "group_id" bigint NULL, "modified_by_id" bigint NULL);
--
-- Create model CredentialRecord
--
CREATE TABLE "k5_credential_record" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "deleted" timestamp with time zone NULL, "deleted_by_cascade" boolean NOT NULL, "created_on" timestamp with time zone NULL, "modified_on" timestamp with time zone NULL, "name" varchar(64) NOT NULL UNIQUE, "status" varchar(16) NOT NULL, "api_type" varchar(128) NOT NULL, "capability" text NOT NULL, "verified_at" timestamp with time zone NULL, "verified_by" varchar(255) NOT NULL, "note" text NOT NULL, "created_by_id" bigint NULL, "group_id" bigint NULL, "modified_by_id" bigint NULL);
--
-- Create model ThresholdSetting
--
CREATE TABLE "k5_threshold_setting" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "deleted" timestamp with time zone NULL, "deleted_by_cascade" boolean NOT NULL, "created_on" timestamp with time zone NULL, "modified_on" timestamp with time zone NULL, "key" varchar(64) NOT NULL, "scope_level" varchar(8) NOT NULL, "value" varchar(64) NOT NULL, "updated_at" timestamp with time zone NOT NULL, "camera_id" bigint NULL, "created_by_id" bigint NULL, "group_id" bigint NULL, "modified_by_id" bigint NULL, "updated_by_id" bigint NULL);
CREATE INDEX "stream_monitors_streammonitor_address_source_58810324" ON "stream_monitors_streammonitor" ("address_source");
CREATE INDEX "stream_monitors_streammonitor_address_source_58810324_like" ON "stream_monitors_streammonitor" ("address_source" varchar_pattern_ops);
ALTER TABLE "k5_threshold_change" ADD CONSTRAINT "k5_threshold_change_camera_id_e846db90_fk_stream_mo" FOREIGN KEY ("camera_id") REFERENCES "stream_monitors_streammonitor" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "k5_threshold_change" ADD CONSTRAINT "k5_threshold_change_changed_by_id_f418fcc5_fk_user_coreuser_id" FOREIGN KEY ("changed_by_id") REFERENCES "user_coreuser" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "k5_threshold_change" ADD CONSTRAINT "k5_threshold_change_created_by_id_cb6fa656_fk_user_coreuser_id" FOREIGN KEY ("created_by_id") REFERENCES "user_coreuser" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "k5_threshold_change" ADD CONSTRAINT "k5_threshold_change_group_id_0cf85681_fk_user_usergroup_id" FOREIGN KEY ("group_id") REFERENCES "user_usergroup" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "k5_threshold_change" ADD CONSTRAINT "k5_threshold_change_modified_by_id_1874706a_fk_user_coreuser_id" FOREIGN KEY ("modified_by_id") REFERENCES "user_coreuser" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "k5_threshold_change_deleted_5ea15340" ON "k5_threshold_change" ("deleted");
CREATE INDEX "k5_threshold_change_key_7c83d76a" ON "k5_threshold_change" ("key");
CREATE INDEX "k5_threshold_change_key_7c83d76a_like" ON "k5_threshold_change" ("key" varchar_pattern_ops);
CREATE INDEX "k5_threshold_change_scope_level_aaec8be7" ON "k5_threshold_change" ("scope_level");
CREATE INDEX "k5_threshold_change_scope_level_aaec8be7_like" ON "k5_threshold_change" ("scope_level" varchar_pattern_ops);
CREATE INDEX "k5_threshold_change_changed_at_8062d923" ON "k5_threshold_change" ("changed_at");
CREATE INDEX "k5_threshold_change_camera_id_e846db90" ON "k5_threshold_change" ("camera_id");
CREATE INDEX "k5_threshold_change_changed_by_id_f418fcc5" ON "k5_threshold_change" ("changed_by_id");
CREATE INDEX "k5_threshold_change_created_by_id_cb6fa656" ON "k5_threshold_change" ("created_by_id");
CREATE INDEX "k5_threshold_change_group_id_0cf85681" ON "k5_threshold_change" ("group_id");
CREATE INDEX "k5_threshold_change_modified_by_id_1874706a" ON "k5_threshold_change" ("modified_by_id");
ALTER TABLE "k5_credential_record" ADD CONSTRAINT "k5_credential_record_created_by_id_25cc900a_fk_user_coreuser_id" FOREIGN KEY ("created_by_id") REFERENCES "user_coreuser" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "k5_credential_record" ADD CONSTRAINT "k5_credential_record_group_id_927a2d1d_fk_user_usergroup_id" FOREIGN KEY ("group_id") REFERENCES "user_usergroup" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "k5_credential_record" ADD CONSTRAINT "k5_credential_record_modified_by_id_7a0855c2_fk_user_core" FOREIGN KEY ("modified_by_id") REFERENCES "user_coreuser" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "k5_credential_record_deleted_0b166f6c" ON "k5_credential_record" ("deleted");
CREATE INDEX "k5_credential_record_name_6640419e_like" ON "k5_credential_record" ("name" varchar_pattern_ops);
CREATE INDEX "k5_credential_record_status_5db93abe" ON "k5_credential_record" ("status");
CREATE INDEX "k5_credential_record_status_5db93abe_like" ON "k5_credential_record" ("status" varchar_pattern_ops);
CREATE INDEX "k5_credential_record_created_by_id_25cc900a" ON "k5_credential_record" ("created_by_id");
CREATE INDEX "k5_credential_record_group_id_927a2d1d" ON "k5_credential_record" ("group_id");
CREATE INDEX "k5_credential_record_modified_by_id_7a0855c2" ON "k5_credential_record" ("modified_by_id");
CREATE INDEX "k5_credenti_status_6fc7b9_idx" ON "k5_credential_record" ("status");
ALTER TABLE "k5_threshold_setting" ADD CONSTRAINT "k5_threshold_setting_camera_id_31d8ca0a_fk_stream_mo" FOREIGN KEY ("camera_id") REFERENCES "stream_monitors_streammonitor" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "k5_threshold_setting" ADD CONSTRAINT "k5_threshold_setting_created_by_id_66763839_fk_user_coreuser_id" FOREIGN KEY ("created_by_id") REFERENCES "user_coreuser" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "k5_threshold_setting" ADD CONSTRAINT "k5_threshold_setting_group_id_904af61b_fk_user_usergroup_id" FOREIGN KEY ("group_id") REFERENCES "user_usergroup" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "k5_threshold_setting" ADD CONSTRAINT "k5_threshold_setting_modified_by_id_485c68a3_fk_user_core" FOREIGN KEY ("modified_by_id") REFERENCES "user_coreuser" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "k5_threshold_setting" ADD CONSTRAINT "k5_threshold_setting_updated_by_id_d3afdea2_fk_user_coreuser_id" FOREIGN KEY ("updated_by_id") REFERENCES "user_coreuser" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE UNIQUE INDEX "uniq_threshold_global" ON "k5_threshold_setting" ("key") WHERE "scope_level" = 'global';
CREATE UNIQUE INDEX "uniq_threshold_tenant" ON "k5_threshold_setting" ("key", "group_id") WHERE "scope_level" = 'tenant';
CREATE UNIQUE INDEX "uniq_threshold_camera" ON "k5_threshold_setting" ("key", "camera_id") WHERE "scope_level" = 'camera';
CREATE INDEX "k5_threshold_setting_deleted_cf9cfe67" ON "k5_threshold_setting" ("deleted");
CREATE INDEX "k5_threshold_setting_key_0dcca7ec" ON "k5_threshold_setting" ("key");
CREATE INDEX "k5_threshold_setting_key_0dcca7ec_like" ON "k5_threshold_setting" ("key" varchar_pattern_ops);
CREATE INDEX "k5_threshold_setting_scope_level_ae78d897" ON "k5_threshold_setting" ("scope_level");
CREATE INDEX "k5_threshold_setting_scope_level_ae78d897_like" ON "k5_threshold_setting" ("scope_level" varchar_pattern_ops);
CREATE INDEX "k5_threshold_setting_camera_id_31d8ca0a" ON "k5_threshold_setting" ("camera_id");
CREATE INDEX "k5_threshold_setting_created_by_id_66763839" ON "k5_threshold_setting" ("created_by_id");
CREATE INDEX "k5_threshold_setting_group_id_904af61b" ON "k5_threshold_setting" ("group_id");
CREATE INDEX "k5_threshold_setting_modified_by_id_485c68a3" ON "k5_threshold_setting" ("modified_by_id");
CREATE INDEX "k5_threshold_setting_updated_by_id_d3afdea2" ON "k5_threshold_setting" ("updated_by_id");
CREATE INDEX "k5_threshol_key_b056a2_idx" ON "k5_threshold_setting" ("key", "scope_level");
COMMIT;
