# Generated by Django 5.1.2 on 2025-05-12 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0002_routes_routeterminal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminal',
            name='time_stops',
        ),
    ]
