# Generated by Django 5.1.2 on 2025-05-12 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0003_remove_terminal_time_stops'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terminal',
            options={},
        ),
    ]
