# Generated by Django 5.1.2 on 2025-05-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0004_alter_terminal_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
