# Generated by Django 5.1.2 on 2025-05-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0005_terminal_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='code',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
