# Generated by Django 5.1.2 on 2025-05-14 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0006_terminal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='code',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
