# Generated by Django 5.1.2 on 2025-05-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0007_routes_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='total_stops',
            field=models.IntegerField(default=0),
        ),
    ]
