# Generated by Django 5.1.2 on 2025-05-26 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0008_routes_total_stops'),
        ('user', '0013_alter_userprofilelink_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AddField(
            model_name='terminal',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
    ]
