# Generated by Django 5.1.2 on 2025-06-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0010_remove_routes_group_remove_terminal_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminal',
            name='city_county_district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='city_province',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='street_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='ward_town_township',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
