# Generated by Django 5.1.2 on 2025-06-18 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0011_alter_terminal_city_county_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='postal_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
