# Generated by Django 5.1.2 on 2025-06-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0012_terminal_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminal',
            name='latitude',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='longitude',
            field=models.CharField(blank=True, null=True),
        ),
    ]
