# Generated by Django 5.1.2 on 2025-07-01 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0014_locationtype_terminal_location_type'),
        ('user', '0020_alter_timezone_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terminaltype',
            options={},
        ),
        migrations.AddField(
            model_name='terminaltype',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
    ]
