# Generated by Django 5.1.2 on 2025-07-03 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0015_alter_terminaltype_options_terminaltype_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routes',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='terminal',
            name='groups',
        ),
    ]
