# Generated by Django 5.1.2 on 2025-07-07 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0017_alter_terminaltype_options_remove_terminaltype_group_and_more'),
        ('user', '0020_alter_timezone_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dockingstationtype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='infrastructuretype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='terminalbasetype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='terminaltype',
            options={},
        ),
        migrations.AddField(
            model_name='dockingstationtype',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AddField(
            model_name='infrastructuretype',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AddField(
            model_name='terminalbasetype',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AddField(
            model_name='terminaltype',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
    ]
