# Generated by Django 5.1.2 on 2025-07-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0019_terminalpurpose_terminal_terminal_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='manufacturer',
            field=models.CharField(blank=True, null=True),
        ),
    ]
