# Generated by Django 5.1.2 on 2025-07-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0021_remove_terminal_purpose_purposetype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='address_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
