# Generated by Django 5.1.2 on 2025-07-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0022_terminal_address_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='terminal_id',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
