# Generated by Django 5.1.2 on 2025-07-22 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0023_terminal_terminal_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminal',
            name='terminal_id',
        ),
    ]
