# Generated by Django 5.1.2 on 2025-07-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0024_remove_terminal_terminal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeterminal',
            name='for_robot',
            field=models.BooleanField(default=False),
        ),
    ]
