# Generated by Django 5.1.2 on 2025-07-29 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0025_routeterminal_for_robot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terminal',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='terminal',
            name='parent_terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='terminals.terminal'),
        ),
    ]
