# Generated by Django 5.1.2 on 2025-07-31 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0029_remove_old_terminal_type_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routeterminal',
            options={},
        ),
    ]
