# Generated by Django 5.1.2 on 2025-08-04 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0034_alter_function_options_remove_function_group_and_more'),
        ('user', '0022_coreuser_is_rejected_coreuser_reject_on_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='function',
            options={},
        ),
        migrations.AddField(
            model_name='function',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
    ]
