# Generated by Django 5.1.2 on 2025-08-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0035_alter_function_options_function_group'),
        ('user', '0022_coreuser_is_rejected_coreuser_reject_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_groups', to='user.usergroup'),
        ),
    ]
