# Generated by Django 5.1.2 on 2025-08-13 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0040_remove_terminal_group_terminal_groups'),
        ('user', '0022_coreuser_is_rejected_coreuser_reject_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminal',
            name='groups',
        ),
        migrations.AddField(
            model_name='terminal',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
    ]
