# Generated by Django 5.1.2 on 2025-08-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0041_remove_terminal_groups_terminal_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='two_way',
            field=models.BooleanField(default=False),
        ),
    ]
