# Generated by Django 5.1.2 on 2025-08-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0042_routes_two_way'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='two_way',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
