# Generated by Django 5.1.2 on 2025-08-21 07:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0014_alter_usermediafile_file_url'),
        ('terminals', '0043_alter_routes_two_way'),
        ('user', '0022_coreuser_is_rejected_coreuser_reject_on_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='code',
            field=models.CharField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='routes',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='routes',
            name='status',
            field=models.CharField(db_index=True, default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='code',
            field=models.CharField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='status',
            field=models.CharField(db_index=True, default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='terminaltype',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='routes',
            index=models.Index(fields=['code'], name='terminals_r_code_8c69ba_idx'),
        ),
        migrations.AddIndex(
            model_name='routes',
            index=models.Index(fields=['is_active'], name='terminals_r_is_acti_623627_idx'),
        ),
        migrations.AddIndex(
            model_name='routes',
            index=models.Index(fields=['status'], name='terminals_r_status_982034_idx'),
        ),
        migrations.AddIndex(
            model_name='routes',
            index=models.Index(fields=['code', 'is_active'], name='terminals_r_code_d15d6b_idx'),
        ),
        migrations.AddIndex(
            model_name='routes',
            index=models.Index(fields=['status', 'is_active'], name='terminals_r_status_7b891d_idx'),
        ),
        migrations.AddIndex(
            model_name='terminal',
            index=models.Index(fields=['code'], name='terminals_t_code_04275e_idx'),
        ),
        migrations.AddIndex(
            model_name='terminal',
            index=models.Index(fields=['active'], name='terminals_t_active_c5eb23_idx'),
        ),
        migrations.AddIndex(
            model_name='terminal',
            index=models.Index(fields=['status'], name='terminals_t_status_d81145_idx'),
        ),
        migrations.AddIndex(
            model_name='terminal',
            index=models.Index(fields=['code', 'active'], name='terminals_t_code_2cd7ea_idx'),
        ),
        migrations.AddIndex(
            model_name='terminal',
            index=models.Index(fields=['status', 'active'], name='terminals_t_status_133c84_idx'),
        ),
        migrations.AddIndex(
            model_name='terminaltype',
            index=models.Index(fields=['code'], name='terminals_t_code_065f1e_idx'),
        ),
    ]
