# Generated by Django 5.1.2 on 2025-08-26 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0044_alter_routes_code_alter_routes_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeterminal',
            name='command_line',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routeterminal',
            name='takeoff_support',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
