# Generated by Django 5.1.2 on 2025-08-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0045_routeterminal_command_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeterminal',
            name='frame',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
