# Generated by Django 5.1.2 on 2025-08-26 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0046_routeterminal_frame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routeterminal',
            name='takeoff_support',
        ),
    ]
