# Generated by Django 5.1.2 on 2025-09-15 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0014_alter_usermediafile_file_url'),
        ('terminals', '0047_remove_routeterminal_takeoff_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='img_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes_img_map', to='file_management.usermediafile'),
        ),
    ]
