# Generated by Django 5.1.2 on 2025-10-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0048_routes_img_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='compatible_drone',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terminal',
            name='swap_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
