# Generated by Django 5.1.2 on 2025-10-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0049_terminal_compatible_drone_terminal_swap_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='weather_resistant',
            field=models.CharField(blank=True, null=True),
        ),
    ]
