# Generated by Django 5.1.2 on 2025-10-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0050_terminal_weather_resistant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminal',
            name='swap_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
