# Generated by Django 5.1.2 on 2025-10-14 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0051_alter_terminal_swap_time'),
        ('user', '0024_country_group_currencyformat_group_dateformat_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationtype',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AddField(
            model_name='purposetype',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AddField(
            model_name='routes',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AddField(
            model_name='routeterminal',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AlterField(
            model_name='function',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AlterField(
            model_name='terminalpurpose',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AlterField(
            model_name='terminaltype',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
    ]
