# Generated by Django 5.1.2 on 2025-10-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0052_locationtype_group_purposetype_group_routes_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminal',
            name='swap_time',
            field=models.CharField(blank=True, null=True),
        ),
    ]
