# Generated by Django 5.1.2 on 2025-11-05 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0054_deactivatereason'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='deactivate_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terminals', to='terminals.deactivatereason'),
        ),
    ]
