# Generated by Django 5.1.2 on 2025-11-18 10:05

import core.base
import core.multilanguage.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0055_terminal_deactivate_reason'),
        ('user', '0024_country_group_currencyformat_group_dateformat_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('order', models.IntegerField(db_index=True, default=0, help_text='Thứ tự hiển thị (0=Monday, 6=Sunday)')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
            },
            bases=(models.Model, core.multilanguage.models.MultiLanguageContentMixin, core.base.DependencyCheckMixin),
        ),
        migrations.CreateModel(
            name='TerminalException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('exception_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_all_day', models.BooleanField(db_index=True, default=False)),
                ('reason', models.CharField(blank=True, max_length=500, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='terminals.terminal')),
            ],
            options={
                'ordering': ['terminal', 'exception_date'],
            },
            bases=(models.Model, core.multilanguage.models.MultiLanguageContentMixin, core.base.DependencyCheckMixin),
        ),
        migrations.CreateModel(
            name='TerminalOperatingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('day_of_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_times', to='terminals.dayofweek')),
                ('group', models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_times', to='terminals.terminal')),
            ],
            options={
                'ordering': ['terminal', 'day_of_week__order'],
            },
            bases=(models.Model, core.multilanguage.models.MultiLanguageContentMixin, core.base.DependencyCheckMixin),
        ),
        migrations.AddIndex(
            model_name='dayofweek',
            index=models.Index(fields=['code'], name='terminals_d_code_3c2379_idx'),
        ),
        migrations.AddIndex(
            model_name='dayofweek',
            index=models.Index(fields=['order'], name='terminals_d_order_0e1e74_idx'),
        ),
        migrations.AddIndex(
            model_name='dayofweek',
            index=models.Index(fields=['is_active'], name='terminals_d_is_acti_06f8f4_idx'),
        ),
        migrations.AddIndex(
            model_name='terminalexception',
            index=models.Index(fields=['terminal', 'exception_date'], name='terminals_t_termina_9da97c_idx'),
        ),
        migrations.AddIndex(
            model_name='terminalexception',
            index=models.Index(fields=['exception_date'], name='terminals_t_excepti_1c9f43_idx'),
        ),
        migrations.AddIndex(
            model_name='terminalexception',
            index=models.Index(fields=['terminal', 'is_all_day'], name='terminals_t_termina_e5505f_idx'),
        ),
        migrations.AddIndex(
            model_name='terminaloperatingtime',
            index=models.Index(fields=['terminal', 'day_of_week'], name='terminals_t_termina_4af504_idx'),
        ),
        migrations.AddIndex(
            model_name='terminaloperatingtime',
            index=models.Index(fields=['terminal', 'is_active'], name='terminals_t_termina_3eb087_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='terminaloperatingtime',
            unique_together={('terminal', 'day_of_week')},
        ),
    ]
