# Generated by Django 5.1.2 on 2025-11-25 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0015_usermediafile_group_usermediafileitem_group'),
        ('terminals', '0056_dayofweek_terminalexception_terminaloperatingtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='img_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes_img_route', to='file_management.usermediafile'),
        ),
    ]
