BASE_DIR /app
[MinIO Init] Warning: HTTPConnectionPool(host='minio.invalid', port=80): Max retries exceeded with url: /guardianx-dev?location= (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x78b0c3c84b50>: Failed to resolve 'minio.invalid' ([Errno -2] Name or service not known)"))
🚀 [DJANGO_READY] Applying backend optimizations...
🌍 [DJANGO_READY] Universal optimization system initialized for ALL models & views
🔗 [DJANGO_READY] Cache invalidation signals registered manually
🧵 [DJANGO_READY] Thread request context propagation installed
BEGIN;
--
-- Create model DeliveryRecord
--
CREATE TABLE "stream_monitors_deliveryrecord" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "deleted" timestamp with time zone NULL, "deleted_by_cascade" boolean NOT NULL, "created_on" timestamp with time zone NULL, "modified_on" timestamp with time zone NULL, "recipient_address" varchar(255) NOT NULL, "channel" varchar(16) NOT NULL, "occurred_at" timestamp with time zone NOT NULL, "sent_at" timestamp with time zone NULL, "succeeded" boolean NOT NULL, "failure_reason" varchar(255) NULL, "retry_count" integer NOT NULL CHECK ("retry_count" >= 0), "created_by_id" bigint NULL, "event_id" bigint NOT NULL, "group_id" bigint NULL, "modified_by_id" bigint NULL, "recipient_id" bigint NULL);
--
-- Create model NotificationRule
--
CREATE TABLE "stream_monitors_notificationrule" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "deleted" timestamp with time zone NULL, "deleted_by_cascade" boolean NOT NULL, "created_on" timestamp with time zone NULL, "modified_on" timestamp with time zone NULL, "severity" varchar(16) NOT NULL, "zone" varchar(64) NULL, "channels" jsonb NOT NULL, "is_active" boolean NOT NULL, "created_by_id" bigint NULL, "group_id" bigint NULL, "modified_by_id" bigint NULL, "role_id" bigint NOT NULL);
ALTER TABLE "stream_monitors_deliveryrecord" ADD CONSTRAINT "stream_monitors_deli_created_by_id_89bf8453_fk_user_core" FOREIGN KEY ("created_by_id") REFERENCES "user_coreuser" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "stream_monitors_deliveryrecord" ADD CONSTRAINT "stream_monitors_deli_event_id_70baa9bb_fk_stream_mo" FOREIGN KEY ("event_id") REFERENCES "stream_monitors_detectionevent" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "stream_monitors_deliveryrecord" ADD CONSTRAINT "stream_monitors_deli_group_id_0b18c8b6_fk_user_user" FOREIGN KEY ("group_id") REFERENCES "user_usergroup" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "stream_monitors_deliveryrecord" ADD CONSTRAINT "stream_monitors_deli_modified_by_id_bdc9aaae_fk_user_core" FOREIGN KEY ("modified_by_id") REFERENCES "user_coreuser" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "stream_monitors_deliveryrecord" ADD CONSTRAINT "stream_monitors_deli_recipient_id_dd9e6d01_fk_user_core" FOREIGN KEY ("recipient_id") REFERENCES "user_coreuser" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "stream_monitors_deliveryrecord_deleted_61f9caa2" ON "stream_monitors_deliveryrecord" ("deleted");
CREATE INDEX "stream_monitors_deliveryrecord_channel_0287cc3e" ON "stream_monitors_deliveryrecord" ("channel");
CREATE INDEX "stream_monitors_deliveryrecord_channel_0287cc3e_like" ON "stream_monitors_deliveryrecord" ("channel" varchar_pattern_ops);
CREATE INDEX "stream_monitors_deliveryrecord_occurred_at_a0a70147" ON "stream_monitors_deliveryrecord" ("occurred_at");
CREATE INDEX "stream_monitors_deliveryrecord_sent_at_1e0a0443" ON "stream_monitors_deliveryrecord" ("sent_at");
CREATE INDEX "stream_monitors_deliveryrecord_succeeded_29522e96" ON "stream_monitors_deliveryrecord" ("succeeded");
CREATE INDEX "stream_monitors_deliveryrecord_created_by_id_89bf8453" ON "stream_monitors_deliveryrecord" ("created_by_id");
CREATE INDEX "stream_monitors_deliveryrecord_event_id_70baa9bb" ON "stream_monitors_deliveryrecord" ("event_id");
CREATE INDEX "stream_monitors_deliveryrecord_group_id_0b18c8b6" ON "stream_monitors_deliveryrecord" ("group_id");
CREATE INDEX "stream_monitors_deliveryrecord_modified_by_id_bdc9aaae" ON "stream_monitors_deliveryrecord" ("modified_by_id");
CREATE INDEX "stream_monitors_deliveryrecord_recipient_id_dd9e6d01" ON "stream_monitors_deliveryrecord" ("recipient_id");
CREATE INDEX "stream_moni_event_i_aee7ba_idx" ON "stream_monitors_deliveryrecord" ("event_id", "occurred_at" DESC);
CREATE INDEX "stream_moni_succeed_e5d893_idx" ON "stream_monitors_deliveryrecord" ("succeeded", "occurred_at" DESC);
ALTER TABLE "stream_monitors_notificationrule" ADD CONSTRAINT "stream_monitors_noti_created_by_id_b28d4a83_fk_user_core" FOREIGN KEY ("created_by_id") REFERENCES "user_coreuser" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "stream_monitors_notificationrule" ADD CONSTRAINT "stream_monitors_noti_group_id_8d04a62d_fk_user_user" FOREIGN KEY ("group_id") REFERENCES "user_usergroup" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "stream_monitors_notificationrule" ADD CONSTRAINT "stream_monitors_noti_modified_by_id_35175bf5_fk_user_core" FOREIGN KEY ("modified_by_id") REFERENCES "user_coreuser" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "stream_monitors_notificationrule" ADD CONSTRAINT "stream_monitors_noti_role_id_e13b5a0a_fk_role_role" FOREIGN KEY ("role_id") REFERENCES "role_role" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "stream_monitors_notificationrule_deleted_fa6347e7" ON "stream_monitors_notificationrule" ("deleted");
CREATE INDEX "stream_monitors_notificationrule_severity_652e2bf2" ON "stream_monitors_notificationrule" ("severity");
CREATE INDEX "stream_monitors_notificationrule_severity_652e2bf2_like" ON "stream_monitors_notificationrule" ("severity" varchar_pattern_ops);
CREATE INDEX "stream_monitors_notificationrule_zone_4faa0a66" ON "stream_monitors_notificationrule" ("zone");
CREATE INDEX "stream_monitors_notificationrule_zone_4faa0a66_like" ON "stream_monitors_notificationrule" ("zone" varchar_pattern_ops);
CREATE INDEX "stream_monitors_notificationrule_is_active_2e0814dd" ON "stream_monitors_notificationrule" ("is_active");
CREATE INDEX "stream_monitors_notificationrule_created_by_id_b28d4a83" ON "stream_monitors_notificationrule" ("created_by_id");
CREATE INDEX "stream_monitors_notificationrule_group_id_8d04a62d" ON "stream_monitors_notificationrule" ("group_id");
CREATE INDEX "stream_monitors_notificationrule_modified_by_id_35175bf5" ON "stream_monitors_notificationrule" ("modified_by_id");
CREATE INDEX "stream_monitors_notificationrule_role_id_e13b5a0a" ON "stream_monitors_notificationrule" ("role_id");
CREATE INDEX "stream_moni_severit_3c38e4_idx" ON "stream_monitors_notificationrule" ("severity", "is_active");
COMMIT;
