# Generated by Django 5.1.2 on 2025-10-23 03:20

import core.base
import core.multilanguage.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terminals', '0053_alter_terminal_swap_time'),
        ('user', '0024_country_group_currencyformat_group_dateformat_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyMissionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color_code', models.CharField(blank=True, help_text='Hex color code (e.g. #FF5733)', max_length=20, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Survey Mission Status',
                'verbose_name_plural': 'Survey Mission Statuses',
                'ordering': ['id'],
            },
            bases=(models.Model, core.multilanguage.models.MultiLanguageContentMixin, core.base.DependencyCheckMixin),
        ),
        migrations.CreateModel(
            name='SurveyMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('maximum_drones', models.IntegerField(help_text='Maximum number of drones for this mission')),
                ('purpose', models.TextField(help_text='Mission purpose/objective')),
                ('polygon', models.JSONField(help_text='Survey area polygon [[lat,lon],...]')),
                ('qgc_mission_data', models.JSONField(blank=True, help_text='QGroundControl mission data for survey export', null=True)),
                ('total_waypoints', models.IntegerField(default=0, help_text='Total waypoints (takeoff + land, not including survey grid)')),
                ('log_collection', models.BooleanField(blank=True, default=False, help_text='Enable log collection', null=True)),
                ('video_recording', models.BooleanField(blank=True, default=False, help_text='Enable video recording', null=True)),
                ('video_analysis', models.BooleanField(blank=True, default=False, help_text='Enable video analysis', null=True)),
                ('return_to_home', models.BooleanField(blank=True, default=True, help_text='Return to home after mission', null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Mission is currently active')),
                ('note', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_survey_missions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_survey_missions', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='survey_missions', to='surveillance.surveymissionstatus')),
            ],
            options={
                'verbose_name': 'Survey Mission',
                'verbose_name_plural': 'Survey Missions',
            },
            bases=(models.Model, core.multilanguage.models.MultiLanguageContentMixin, core.base.DependencyCheckMixin),
        ),
        migrations.CreateModel(
            name='MissionWaypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('order', models.IntegerField(help_text='Order in mission (1=takeoff, last=land)')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('command_line', models.JSONField(blank=True, help_text='MAVLink command: {command, frame, params}', null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mission_waypoints', to='terminals.terminal')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='surveillance.surveymission')),
            ],
            options={
                'verbose_name': 'Mission Waypoint',
                'verbose_name_plural': 'Mission Waypoints',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['mission', 'order'], name='surveillanc_mission_322299_idx')],
            },
            bases=(models.Model, core.multilanguage.models.MultiLanguageContentMixin, core.base.DependencyCheckMixin),
        ),
        migrations.AddIndex(
            model_name='surveymissionstatus',
            index=models.Index(fields=['code'], name='surveillanc_code_76ce12_idx'),
        ),
        migrations.AddIndex(
            model_name='surveymission',
            index=models.Index(fields=['-created_on'], name='surveillanc_created_5020d9_idx'),
        ),
        migrations.AddIndex(
            model_name='surveymission',
            index=models.Index(fields=['status'], name='surveillanc_status__c97c9e_idx'),
        ),
        migrations.AddIndex(
            model_name='surveymission',
            index=models.Index(fields=['group', 'status'], name='surveillanc_group_i_0248cc_idx'),
        ),
        migrations.AddIndex(
            model_name='surveymission',
            index=models.Index(fields=['is_active'], name='surveillanc_is_acti_276496_idx'),
        ),
    ]
