# Generated by Django 5.1.2 on 2025-10-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveymission',
            name='polygon',
            field=models.JSONField(blank=True, help_text='Survey area polygon [[lat,lon],...]', null=True),
        ),
    ]
