# Generated by Django 5.1.2 on 2025-10-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0002_alter_surveymission_polygon'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionwaypoint',
            name='frame',
            field=models.JSONField(blank=True, help_text='MAVLink command: {command, frame, params}', null=True),
        ),
    ]
