# Generated by Django 5.1.2 on 2025-10-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0003_missionwaypoint_frame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveymission',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, help_text='Mission is currently active', null=True),
        ),
    ]
