# Generated by Django 5.1.2 on 2025-10-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0004_alter_surveymission_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveymission',
            name='is_active',
            field=models.BooleanField(db_index=True, help_text='Mission is currently active', null=True),
        ),
    ]
