# Generated by Django 5.1.2 on 2025-10-28 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0006_missionpurpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveymission',
            name='purpose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='survey_missions', to='surveillance.missionpurpose'),
        ),
    ]
