# Generated by Django 5.1.2 on 2025-10-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0007_alter_surveymission_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveymission',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
