# Generated by Django 5.1.2 on 2025-10-29 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0008_surveymission_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionwaypoint',
            name='latitude',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='missionwaypoint',
            name='longitude',
            field=models.CharField(),
        ),
    ]
