# Generated by Django 5.1.2 on 2025-10-31 07:49

import core.base
import core.multilanguage.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0052_remove_device_groups'),
        ('surveillance', '0009_alter_missionwaypoint_latitude_and_more'),
        ('user', '0024_country_group_currencyformat_group_dateformat_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveillanceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('code', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('estimated_end_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('repeat_until_date', models.DateField(blank=True, null=True)),
                ('repeat_occurrences', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('repeat_metadata', models.JSONField(blank=True, null=True)),
                ('color_code', models.CharField(default='#1D9BE2', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('device_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surveillance_profiles', to='surveillance.surveymission')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_surveillance_profiles', to=settings.AUTH_USER_MODEL)),
                ('repeat_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_children', to='surveillance.surveillanceprofile')),
            ],
            options={
                'verbose_name': 'Surveillance Profile',
                'verbose_name_plural': 'Surveillance Profiles',
                'ordering': ['-created_on'],
            },
            bases=(models.Model, core.multilanguage.models.MultiLanguageContentMixin, core.base.DependencyCheckMixin),
        ),
        migrations.CreateModel(
            name='SurveillanceProfileDrone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('callsign', models.CharField(blank=True, max_length=100, null=True)),
                ('scheduled_start_time', models.DateTimeField(blank=True, null=True)),
                ('log_collection', models.BooleanField(default=True)),
                ('video_recording', models.BooleanField(default=True)),
                ('video_analysis', models.BooleanField(default=True)),
                ('estimated_distance_km', models.FloatField(blank=True, null=True)),
                ('estimated_time_minutes', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveillance_profile_assignments', to='devices.device')),
                ('end_waypoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_end_assignments', to='surveillance.missionwaypoint')),
                ('group', models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drone_assignments', to='surveillance.surveillanceprofile')),
                ('start_waypoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_start_assignments', to='surveillance.missionwaypoint')),
            ],
            options={
                'verbose_name': 'Surveillance Profile Drone',
                'verbose_name_plural': 'Surveillance Profile Drones',
                'ordering': ['order', 'id'],
            },
            bases=(models.Model, core.multilanguage.models.MultiLanguageContentMixin, core.base.DependencyCheckMixin),
        ),
        migrations.AddField(
            model_name='surveillanceprofile',
            name='devices',
            field=models.ManyToManyField(blank=True, related_name='surveillance_profiles', through='surveillance.SurveillanceProfileDrone', to='devices.device'),
        ),
        migrations.CreateModel(
            name='SurveillanceProfileRepeatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Surveillance Profile Repeat Type',
                'verbose_name_plural': 'Surveillance Profile Repeat Types',
                'ordering': ['id'],
            },
            bases=(models.Model, core.multilanguage.models.MultiLanguageContentMixin, core.base.DependencyCheckMixin),
        ),
        migrations.AddField(
            model_name='surveillanceprofile',
            name='repeat_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='surveillance.surveillanceprofilerepeattype'),
        ),
        migrations.CreateModel(
            name='SurveillanceProfileRepeatUntilType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Surveillance Profile Repeat Until Type',
                'verbose_name_plural': 'Surveillance Profile Repeat Until Types',
                'ordering': ['id'],
            },
            bases=(models.Model, core.multilanguage.models.MultiLanguageContentMixin, core.base.DependencyCheckMixin),
        ),
        migrations.AddField(
            model_name='surveillanceprofile',
            name='repeat_until_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='surveillance.surveillanceprofilerepeatuntiltype'),
        ),
        migrations.CreateModel(
            name='SurveillanceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color_code', models.CharField(blank=True, help_text='Hex color code (e.g. #FF5733)', max_length=20, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Surveillance Status',
                'verbose_name_plural': 'Surveillance Statuses',
                'ordering': ['id'],
            },
            bases=(models.Model, core.multilanguage.models.MultiLanguageContentMixin, core.base.DependencyCheckMixin),
        ),
        migrations.AddField(
            model_name='surveillanceprofile',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='surveillance_profiles', to='surveillance.surveillancestatus'),
        ),
        migrations.AddIndex(
            model_name='surveillanceprofiledrone',
            index=models.Index(fields=['profile', 'order'], name='surveillanc_profile_76d3bd_idx'),
        ),
        migrations.AddIndex(
            model_name='surveillanceprofiledrone',
            index=models.Index(fields=['device'], name='surveillanc_device__9088f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='surveillanceprofiledrone',
            constraint=models.UniqueConstraint(fields=('profile', 'order'), name='unique_profile_drone_order'),
        ),
        migrations.AddIndex(
            model_name='surveillanceprofilerepeattype',
            index=models.Index(fields=['code'], name='surveillanc_code_ce35c1_idx'),
        ),
        migrations.AddIndex(
            model_name='surveillanceprofilerepeatuntiltype',
            index=models.Index(fields=['code'], name='surveillanc_code_861818_idx'),
        ),
        migrations.AddIndex(
            model_name='surveillancestatus',
            index=models.Index(fields=['code'], name='surveillanc_code_704344_idx'),
        ),
        migrations.AddIndex(
            model_name='surveillanceprofile',
            index=models.Index(fields=['code'], name='surveillanc_code_26b22f_idx'),
        ),
        migrations.AddIndex(
            model_name='surveillanceprofile',
            index=models.Index(fields=['mission', 'status'], name='surveillanc_mission_2949ed_idx'),
        ),
        migrations.AddIndex(
            model_name='surveillanceprofile',
            index=models.Index(fields=['status', 'start_time'], name='surveillanc_status__4b3a29_idx'),
        ),
        migrations.AddIndex(
            model_name='surveillanceprofile',
            index=models.Index(fields=['repeat_type'], name='surveillanc_repeat__d3af40_idx'),
        ),
        migrations.AddIndex(
            model_name='surveillanceprofile',
            index=models.Index(fields=['repeat_until_type'], name='surveillanc_repeat__f1632f_idx'),
        ),
        migrations.AddIndex(
            model_name='surveillanceprofile',
            index=models.Index(fields=['-created_on'], name='surveillanc_created_186bdb_idx'),
        ),
    ]
