# Generated by Django 5.1.2 on 2025-11-04 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0010_surveillanceprofile_surveillanceprofiledrone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveillanceprofiledrone',
            name='callsign',
        ),
        migrations.RemoveField(
            model_name='surveillanceprofiledrone',
            name='metadata',
        ),
    ]
