# Generated by Django 5.1.2 on 2025-11-06 07:47

import core.base
import core.multilanguage.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist_setting', '0005_checklistsettingcategory_group_and_more'),
        ('devices', '0052_remove_device_groups'),
        ('surveillance', '0011_remove_surveillanceprofiledrone_callsign_and_more'),
        ('user', '0024_country_group_currencyformat_group_dateformat_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveillanceProfileChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('is_not_yet', models.BooleanField(default=False, help_text='Profile start time has not been reached')),
                ('order_ids', models.JSONField(blank=True, null=True)),
                ('auto_check_data', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveillance_profile_checks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveillance_profile_checklists', to='devices.device')),
                ('group', models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_checklists', to='surveillance.surveillanceprofile')),
                ('profile_drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='surveillance.surveillanceprofiledrone')),
            ],
            options={
                'verbose_name': 'Surveillance Profile Checklist',
                'verbose_name_plural': 'Surveillance Profile Checklists',
            },
            bases=(models.Model, core.multilanguage.models.MultiLanguageContentMixin, core.base.DependencyCheckMixin),
        ),
        migrations.CreateModel(
            name='SurveillanceProfileChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('item_name_snapshot', models.CharField(blank=True, max_length=255, null=True)),
                ('category_code_snapshot', models.CharField(blank=True, max_length=255, null=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='surveillance.surveillanceprofilechecklist')),
                ('checklist_setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveillance_profile_items', to='checklist_setting.checklistsetting')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Surveillance Profile Checklist Item',
                'verbose_name_plural': 'Surveillance Profile Checklist Items',
            },
            bases=(models.Model, core.multilanguage.models.MultiLanguageContentMixin, core.base.DependencyCheckMixin),
        ),
        migrations.AddIndex(
            model_name='surveillanceprofilechecklist',
            index=models.Index(fields=['profile', 'profile_drone'], name='surveillanc_profile_bf705b_idx'),
        ),
        migrations.AddConstraint(
            model_name='surveillanceprofilechecklist',
            constraint=models.UniqueConstraint(fields=('profile', 'profile_drone'), name='unique_profile_checklist_per_drone'),
        ),
        migrations.AddConstraint(
            model_name='surveillanceprofilechecklistitem',
            constraint=models.UniqueConstraint(fields=('checklist', 'checklist_setting'), name='unique_profile_checklist_item'),
        ),
    ]
