# Generated by Django 5.1.2 on 2025-11-07 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0013_surveillanceprofile_reject_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveillanceprofiledrone',
            name='estimated_distance_km',
        ),
        migrations.RemoveField(
            model_name='surveillanceprofiledrone',
            name='estimated_time_minutes',
        ),
    ]
