# Generated by Django 5.1.2 on 2025-11-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0014_remove_surveillanceprofiledrone_estimated_distance_km_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveillanceprofilechecklist',
            name='is_not_yet',
        ),
        migrations.AddField(
            model_name='surveillanceprofile',
            name='not_yet',
            field=models.BooleanField(db_index=True, default=False, help_text='Profile start time has not been reached'),
        ),
    ]
