# Generated by Django 5.1.2 on 2025-11-10 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0015_remove_surveillanceprofilechecklist_is_not_yet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveillanceprofilechecklist',
            name='device',
        ),
        migrations.RemoveField(
            model_name='surveillanceprofilechecklist',
            name='order_ids',
        ),
    ]
