# Generated by Django 5.1.2 on 2025-11-10 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0052_remove_device_groups'),
        ('surveillance', '0016_remove_surveillanceprofilechecklist_device_and_more'),
        ('user', '0024_country_group_currencyformat_group_dateformat_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='surveillanceprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_surveillance_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='surveillanceprofile',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_surveillance_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='surveillanceprofile',
            index=models.Index(fields=['approved_by'], name='surveillanc_approve_614b08_idx'),
        ),
        migrations.AddIndex(
            model_name='surveillanceprofile',
            index=models.Index(fields=['cancelled_by'], name='surveillanc_cancell_8412c9_idx'),
        ),
    ]
