# Generated by Django 5.1.2 on 2025-11-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0017_surveillanceprofile_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveillanceprofiledrone',
            name='analysis_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='surveillanceprofiledrone',
            name='log_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='surveillanceprofiledrone',
            name='video_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
