# Generated by Django 5.1.2 on 2025-11-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0018_surveillanceprofiledrone_analysis_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveillanceprofile',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
