# Generated by Django 5.1.2 on 2025-11-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0019_surveillanceprofile_cancel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveillanceprofile',
            name='actual_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
