# Generated by Django 5.1.2 on 2025-11-18 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_monitors', '0012_streammonitor_is_external_alter_streammonitor_drone'),
        ('surveillance', '0020_surveillanceprofile_actual_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_path', models.CharField(blank=True, max_length=255, null=True)),
                ('analysis', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drone_name', models.CharField(blank=True, max_length=255, null=True)),
                ('operator_name', models.CharField(blank=True, max_length=255, null=True)),
                ('register_number', models.CharField(blank=True, max_length=255, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('flight_distance', models.FloatField(blank=True, null=True)),
                ('flight_time', models.IntegerField(blank=True, null=True)),
                ('flight_altitude', models.FloatField(blank=True, null=True)),
                ('start_point_x', models.CharField(blank=True, max_length=255, null=True)),
                ('start_point_y', models.CharField(blank=True, max_length=255, null=True)),
                ('end_point_x', models.CharField(blank=True, max_length=255, null=True)),
                ('end_point_y', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('profile_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveillance.surveillanceprofiledrone')),
                ('stream_monitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stream_monitors.streammonitor')),
            ],
        ),
    ]
