# Generated by Django 5.1.2 on 2025-11-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0021_videoanalysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoanalysis',
            name='analysis',
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='analysis_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
