# Generated by Django 5.1.2 on 2025-11-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0022_remove_videoanalysis_analysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoanalysis',
            name='deleted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
