# Generated by Django 5.1.2 on 2025-12-12 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0015_usermediafile_group_usermediafileitem_group'),
        ('surveillance', '0024_videoanalysis_created_by_videoanalysis_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoanalysis',
            name='video_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file_management.usermediafile'),
        ),
    ]
