# Generated by Django 5.1.14 on 2025-12-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0025_videoanalysis_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveymission',
            name='from_route',
            field=models.BooleanField(blank=True, default=False, help_text='Mission is created from route', null=True),
        ),
    ]
