# Generated by Django 5.1.14 on 2025-12-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0026_surveymission_from_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveymission',
            name='drone_segments',
            field=models.JSONField(blank=True, help_text="List of drone mission segments with their waypoint ranges and QGC data. Format: [{'area_index': 0, 'drone_id': None, 'start_waypoint_order': 1, 'end_waypoint_order': 10, 'qgc_mission': {...}, ...}]", null=True),
        ),
    ]
