# Generated by Django 5.1.14 on 2025-12-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0027_surveymission_drone_segments'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveillanceprofiledrone',
            name='waiting_coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
