# Generated by Django 5.1.14 on 2026-01-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0028_surveillanceprofiledrone_waiting_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveymission',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
