# Generated by Django 5.1.14 on 2026-02-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0029_surveymission_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveymission',
            name='hover_and_capture',
            field=models.BooleanField(blank=True, default=False, help_text='Hover and capture', null=True),
        ),
    ]
