import { RefObject } from 'react';

// Theme-aware styles for MultiStreamMonitor
export const getThemeStyles = (
  theme: string,
  headerRef: RefObject<HTMLDivElement>,
) => ({
  container: {
    display: 'flex',
    height: `calc(100vh - ${headerRef.current?.clientHeight}px)`,
    // backgroundColor: theme === 'dark' ? '#000' : '#ffffff',
    color: theme === 'dark' ? 'white' : '#333333',
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  sidebar: {
    backgroundColor: theme === 'dark' ? '#000' : '#f8f9fa',
    padding: '1rem 0 1rem 1rem',
    display: 'flex',
    flexDirection: 'column' as const,
    justifyContent: 'space-between',
  },
  sidebarIconWrap: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    overflowY: 'auto' as const,
    border: `1px solid ${theme === 'dark' ? '#404040' : '#e9ecef'}`,
    borderRadius: '8px',
    padding: '0.5rem 0.25rem',
    backgroundColor: theme === 'dark' ? '#1F1F20' : '#fff',
  },
  sidebarIcon: {
    width: '36px',
    height: '36px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: '0.5rem',
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'all 0.2s',
    fontSize: '12px',
    backgroundColor: 'transparent',
    border: 'none',
    color: theme === 'dark' ? '#888' : '#666',
    padding: '4px',
    whiteSpace: 'pre-line' as const,
  },
  sidebarIconActive: {
    backgroundColor: 'var(--ga-primary-2)',
    color: theme === 'dark' ? 'var(--ga-primary)' : 'var(--ga-primary-dark)',
  },
  sidebarIconHover: {
    backgroundColor: theme === 'dark' ? '#404040' : '#e9ecef',
    color: theme === 'dark' ? 'var(--ga-primary)' : 'var(--ga-primary-dark)',
    boxShadow:
      theme === 'dark'
        ? '0 2px 4px rgba(0,0,0,0.3)'
        : '0 2px 6px rgba(0,0,0,0.15)',
  },
  mainContent: {
    flex: 1,
    padding: '1rem',
    display: 'flex',
    flexDirection: 'column' as const,
    overflow: 'hidden',
    minHeight: '38rem',
  },
  header: {
    marginBottom: '20px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexShrink: 0,
  },
  title: {
    fontSize: '24px',
    fontWeight: 'bold',
    margin: 0,
    color: theme === 'dark' ? 'white' : '#333',
  },
  layoutInfo: {
    fontSize: '14px',
    color: theme === 'dark' ? '#888' : '#666',
  },
  gridContainer: {
    flex: 1,
    display: 'grid',
    gap: '1rem',
    overflow: 'auto',
    height: '100%',
  },
  gridItem: {
    position: 'relative' as const,
    backgroundColor: theme === 'dark' ? '#2a2a2a' : '#f8f9fa',
    borderRadius: '8px',
    overflow: 'hidden',
    border: `1px solid ${theme === 'dark' ? '#404040' : '#e9ecef'}`,
    minHeight: '200px',
    height: '100%',
    display: 'flex',
    flexDirection: 'column' as const,
  },
  emptyGridItem: {
    position: 'relative' as const,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2a2a2a ',
    borderRadius: '8px',
    border: `1px solid #404040`,
    color: '#666',
    fontSize: '13px',
    flexDirection: 'column' as const,
    gap: '8px',
    minHeight: '200px',
  },
  addStreamButton: {
    padding: '6px 12px',
    backgroundColor: theme === 'dark' ? '#404040' : '#6c757d',
    color: theme === 'dark' ? '#ccc' : 'white',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '12px',
    transition: 'all 0.2s',
  },
  performanceInfo: {
    position: 'absolute' as const,
    bottom: '20px',
    left: '20px',
    backgroundColor:
      theme === 'dark' ? 'rgba(0, 0, 0, 0.8)' : 'rgba(255, 255, 255, 0.9)',
    color: theme === 'dark' ? '#0f0' : '#28a745',
    padding: '8px 12px',
    borderRadius: '4px',
    fontSize: '11px',
    fontFamily: 'monospace',
    zIndex: 3000,
    border: `1px solid ${theme === 'dark' ? '#404040' : '#dee2e6'}`,
  },
  loadingContainer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    color: theme === 'dark' ? '#888' : '#666',
    fontSize: '16px',
  },
  errorContainer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    color: '#ff4444',
    fontSize: '16px',
    flexDirection: 'column' as const,
    gap: '16px',
  },
  retryButton: {
    padding: '8px 16px',
    backgroundColor: '#007bff',
    color: 'white',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '14px',
  },
  emptySlotLabel: {
    position: 'absolute' as const,
    top: '10px',
    left: '10px',
    backgroundColor: theme === 'dark' ? '#3C3D3E' : '#e9ecef',
    color: theme === 'dark' ? '#9C9D9D' : '#6c757d',
    padding: '6px 10px',
    borderRadius: '4px',
    fontSize: '12px',
    fontWeight: 'bold',
    zIndex: 1000,
    boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
    display: 'flex',
    alignItems: 'center',
    gap: '0.375rem',
  },
  emptySlotDot: {
    width: '0.625rem',
    height: '0.625rem',
    backgroundColor: theme === 'dark' ? '#9C9D9D' : '#6c757d',
    borderRadius: '50%',
    display: 'inline-block',
  },
  settingsButton: {
    // position: 'fixed' as const,
    // bottom: '1.5rem',
    // left: '1.5rem',
    width: '48px',
    height: '48px',
    // borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    backgroundColor: 'transparent',
    border: 'none',
    color: theme === 'dark' ? '#888' : '#666',
    transition: 'all 0.2s',
    // boxShadow:
    //   theme === 'dark'
    //     ? '0 4px 12px rgba(0,0,0,0.5)'
    //     : '0 4px 12px rgba(0,0,0,0.15)',
    zIndex: 99,
  },
  settingsButtonActive: {
    color: theme === 'dark' ? 'var(--ga-primary)' : 'var(--ga-primary-dark)',
    boxShadow:
      theme === 'dark'
        ? '0 6px 16px rgba(0,0,0,0.6)'
        : '0 6px 16px rgba(0,0,0,0.2)',
  },
});
