# Generated by Django 5.1.2 on 2025-11-17 10:29

import core.base
import core.multilanguage.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file_management', '0015_usermediafile_group_usermediafileitem_group'),
        ('user', '0024_country_group_currencyformat_group_dateformat_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoverDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('date_create_shift', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup')),
                ('handover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handover_documents_as_handover', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Handover Document',
                'verbose_name_plural': 'Handover Documents',
                'ordering': ['-created_time'],
            },
            bases=(models.Model, core.multilanguage.models.MultiLanguageContentMixin, core.base.DependencyCheckMixin),
        ),
        migrations.CreateModel(
            name='HandoverDocumentAcceptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('acceptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_handover_documents', to=settings.AUTH_USER_MODEL)),
                ('handover_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptors', to='handover.handoverdocument')),
            ],
            options={
                'verbose_name': 'Handover Document Acceptor',
                'verbose_name_plural': 'Handover Document Acceptors',
                'ordering': ['-created_time'],
            },
        ),
        migrations.AddField(
            model_name='handoverdocument',
            name='acceptor',
            field=models.ManyToManyField(related_name='handover_documents_as_acceptor', through='handover.HandoverDocumentAcceptor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HandoverNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('content', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('processed_time', models.DateTimeField(blank=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_handover_notices', to=settings.AUTH_USER_MODEL)),
                ('editors', models.ManyToManyField(blank=True, related_name='edited_handover_notices', to=settings.AUTH_USER_MODEL)),
                ('files', models.ManyToManyField(blank=True, related_name='handover_notices', to='file_management.usermediafile')),
                ('group', models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('user_processed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_handover_notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Handover Notice',
                'verbose_name_plural': 'Handover Notices',
                'ordering': ['-created_time'],
            },
            bases=(models.Model, core.multilanguage.models.MultiLanguageContentMixin, core.base.DependencyCheckMixin),
        ),
        migrations.CreateModel(
            name='HandoverNoticeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('content', models.TextField()),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='handover.handovernotice')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='handover.handovernoticecomment')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handover_notice_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Handover Notice Comment',
                'verbose_name_plural': 'Handover Notice Comments',
                'ordering': ['-updated_time'],
            },
            bases=(models.Model, core.multilanguage.models.MultiLanguageContentMixin, core.base.DependencyCheckMixin),
        ),
        migrations.CreateModel(
            name='HandoverShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=32)),
                ('start_time', models.CharField(max_length=32)),
                ('end_time', models.CharField(max_length=32)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Handover Shift',
                'verbose_name_plural': 'Handover Shifts',
                'ordering': ['id'],
            },
            bases=(models.Model, core.multilanguage.models.MultiLanguageContentMixin, core.base.DependencyCheckMixin),
        ),
        migrations.AddField(
            model_name='handoverdocument',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handover_documents', to='handover.handovershift'),
        ),
        migrations.CreateModel(
            name='HandoverContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('content', models.TextField()),
                ('is_notice', models.BooleanField(default=False)),
                ('is_report', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_handover_contents', to=settings.AUTH_USER_MODEL)),
                ('editors', models.ManyToManyField(blank=True, related_name='edited_handover_contents', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='Auto-populated from created_by.group during migration', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('handover_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='handover.handoverdocument')),
            ],
            options={
                'verbose_name': 'Handover Content',
                'verbose_name_plural': 'Handover Contents',
                'ordering': ['-created_time'],
                'indexes': [models.Index(fields=['handover_doc'], name='handover_ha_handove_362826_idx'), models.Index(fields=['creator'], name='handover_ha_creator_d5e35d_idx'), models.Index(fields=['is_notice'], name='handover_ha_is_noti_683640_idx')],
            },
            bases=(models.Model, core.multilanguage.models.MultiLanguageContentMixin, core.base.DependencyCheckMixin),
        ),
        migrations.AddIndex(
            model_name='handoverdocumentacceptor',
            index=models.Index(fields=['handover_document', 'acceptor'], name='handover_ha_handove_9ffc1c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='handoverdocumentacceptor',
            unique_together={('handover_document', 'acceptor')},
        ),
        migrations.AddIndex(
            model_name='handovernotice',
            index=models.Index(fields=['creator'], name='handover_ha_creator_9ef34a_idx'),
        ),
        migrations.AddIndex(
            model_name='handovernotice',
            index=models.Index(fields=['is_processed'], name='handover_ha_is_proc_863ddb_idx'),
        ),
        migrations.AddIndex(
            model_name='handovernotice',
            index=models.Index(fields=['created_time'], name='handover_ha_created_2f19ea_idx'),
        ),
        migrations.AddIndex(
            model_name='handovernoticecomment',
            index=models.Index(fields=['notice'], name='handover_ha_notice__608ee5_idx'),
        ),
        migrations.AddIndex(
            model_name='handovernoticecomment',
            index=models.Index(fields=['writer'], name='handover_ha_writer__f5fab8_idx'),
        ),
        migrations.AddIndex(
            model_name='handovernoticecomment',
            index=models.Index(fields=['parent'], name='handover_ha_parent__944eba_idx'),
        ),
        migrations.AddIndex(
            model_name='handoverdocument',
            index=models.Index(fields=['shift'], name='handover_ha_shift_i_61e502_idx'),
        ),
        migrations.AddIndex(
            model_name='handoverdocument',
            index=models.Index(fields=['handover'], name='handover_ha_handove_0dce41_idx'),
        ),
        migrations.AddIndex(
            model_name='handoverdocument',
            index=models.Index(fields=['date_create_shift'], name='handover_ha_date_cr_c5b218_idx'),
        ),
        migrations.AddIndex(
            model_name='handoverdocument',
            index=models.Index(fields=['start_date', 'end_date'], name='handover_ha_start_d_5e46ac_idx'),
        ),
    ]
